/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./webroot/utils/src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      screens: {
        sm: { raw: '(max-width: 799px)' },
        lg: { raw: '(min-width: 800px)' },
        mouse: { raw: '(pointer: fine)' },
        touch: { raw: '(pointer: coarse)' },
      },
      colours: {
        themeAccentColour: 'var(--tds-theme-accent-colour)',
        themeAccentColour10: 'color-mix(in srgb, var(--tds-theme-accent-colour) 10%, transparent)',
        themeAccentColour20: 'color-mix(in srgb, var(--tds-theme-accent-colour) 20%, transparent)',
        themeAccentColour30: 'color-mix(in srgb, var(--tds-theme-accent-colour) 30%, transparent)',
        themeAccentColour40: 'color-mix(in srgb, var(--tds-theme-accent-colour) 40%, transparent)',
        themeAccentColour50: 'color-mix(in srgb, var(--tds-theme-accent-colour) 50%, transparent)',
        themeAccentColour10solid: 'color-mix(in srgb, var(--tds-theme-accent-colour) 10%, white)',
        themeAccentColour20solid: 'color-mix(in srgb, var(--tds-theme-accent-colour) 20%, white)',
        themeAccentColour30solid: 'color-mix(in srgb, var(--tds-theme-accent-colour) 30%, white)',
        themeAccentColour40solid: 'color-mix(in srgb, var(--tds-theme-accent-colour) 40%, white)',
        themeAccentColour50solid: 'color-mix(in srgb, var(--tds-theme-accent-colour) 50%, white)',
        themeBackgroundColour: 'var(--tds-theme-background-colour)',
        themeBackgroundColour10: 'color-mix(in srgb, var(--tds-theme-background-colour) 10%, transparent)',
        themeBackgroundColour20: 'color-mix(in srgb, var(--tds-theme-background-colour) 20%, transparent)',
        themeBackgroundColour30: 'color-mix(in srgb, var(--tds-theme-background-colour) 30%, transparent)',
        themeBackgroundColour40: 'color-mix(in srgb, var(--tds-theme-background-colour) 40%, transparent)',
        themeBackgroundColour50: 'color-mix(in srgb, var(--tds-theme-background-colour) 50%, transparent)',
        themeBackgroundColour10solid: 'color-mix(in srgb, var(--tds-theme-background-colour) 10%, white)',
        themeBackgroundColour20solid: 'color-mix(in srgb, var(--tds-theme-background-colour) 20%, white)',
        themeBackgroundColour30solid: 'color-mix(in srgb, var(--tds-theme-background-colour) 30%, white)',
        themeBackgroundColour40solid: 'color-mix(in srgb, var(--tds-theme-background-colour) 40%, white)',
        themeBackgroundColour50solid: 'color-mix(in srgb, var(--tds-theme-background-colour) 50%, white)',
        themeBorderColour: 'var(--tds-theme-border-colour)',
        themeIconColour: 'var(--tds-theme-icon-colour)',
        themeLinkColour: 'var(--tds-theme-link-colour)',
        themeOverlayColour: 'var(--tds-theme-overlay-colour)',
        themePlaceholderColour: 'var(--tds-theme-placeholder-colour)',
        themeTextColour: 'var(--tds-theme-text-colour)',
        themeTextColour10: 'color-mix(in srgb, var(--tds-theme-text-colour) 10%, transparent)',
        themeTextColour20: 'color-mix(in srgb, var(--tds-theme-text-colour) 20%, transparent)',
        themeTextColour30: 'color-mix(in srgb, var(--tds-theme-text-colour) 30%, transparent)',
        themeTextColour40: 'color-mix(in srgb, var(--tds-theme-text-colour) 40%, transparent)',
        themeTextColour50: 'color-mix(in srgb, var(--tds-theme-text-colour) 50%, transparent)',
        themeBtnBgrdColDefault: 'var(--tds-button-background-colour-default)',
        themeBtnBgrdColHover: 'var(--tds-button-background-colour-hover)',
        themeBtnBgrdColPressed: 'var(--tds-button-background-colour-pressed)',
        themeBtnBgrdColDisabled: 'var(--tds-button-background-colour-disabled)',
        themeBtnBrdrColDefault: 'var(--tds-button-border-colour-default)',
        themeBtnBrdrColHover: 'var(--tds-button-border-colour-hover)',
        themeBtnBrdrColPressed: 'var(--tds-button-border-colour-pressed)',
        themeBtnBrdrColDisabled: 'var(--tds-button-border-colour-disabled)',
        themeBtnTextColDefault: 'var(--tds-button-text-colour-default)',
        themeBtnTextColHover: 'var(--tds-button-text-colour-hover)',
        themeBtnTextColPressed: 'var(--tds-button-text-colour-pressed)',
        themeBtnTextColDisabled: 'var(--tds-button-text-colour-disabled)',
        themeBtnIconColDefault: 'var(--tds-button-icon-colour-default)',
        themeBtnIconColHover: 'var(--tds-button-icon-colour-hover)',
        themeBtnIconColPressed: 'var(--tds-button-icon-colour-pressed)',
        themeBtnIconColDisabled: 'var(--tds-button-icon-colour-disabled)',
        themeBtnAcntColDefault: 'var(--tds-button-accent-colour-default,var(--tds-button-border-colour-default))',
        themeBtnAcntColHover: 'var(--tds-button-accent-colour-hover,var(--tds-button-border-colour-hover))',
        themeBtnAcntColPressed: 'var(--tds-button-accent-colour-pressed,var(--tds-button-border-colour-pressed))',
        themeBtnAcntColDisabled: 'var(--tds-button-accent-colour-disabled,var(--tds-button-border-colour-disabled))',
      },
      backgroundColor: ({ theme }) => ({
        ...theme('colours'),
        'ui-bg-one': {
          DEFAULT: '#FFF',
          dark: '#555',
        },
        'ui-bg-two': {
          DEFAULT: '#f6f6f6',
          dark: '#333',
        },
      }),
      borderColor: ({ theme }) => ({
        ...theme('colours'),
      }),
      transitionDuration: {
        standard: '300ms',
      },
      transitionTimingFunction: {
        sidebar: 'cubic-bezier(0.46, 0.03, 0.52, 0.96)',
      },
      boxShadow: {
        test: '0 1px 3px rgb(0 0 0 / 20%)',
      },
      borderRadius: ({ theme }) => ({
        ...theme('spacing'),
        themeCornerSize: 'min(var(--tds-theme-corner-size),25px)',
        none: '0rem',
        0: '0rem',
      }),
      spacing: {
        0: '0px',
        px: '1px',
        xxs: '2px',
        xs: '5px',
        sm: '10px',
        md: '15px',
        lg: '20px',
        xl: '30px',
        xxl: '40px',
        xxxl: '50px',
      },
      textColor: ({ theme }) => ({
        ...theme('colours'),
      }),
      containers: {
        minTableWidth: 'var(--minTableWidth)',
      },
    },
  },
  plugins: [require('@tailwindcss/container-queries')],
};
