<?php /* Smarty version 4.5.3, created on 2026-04-13 14:27:26
         compiled from 'C:\TAOPIX\MediaAlbumWeb\Branding\ubbpro\lang\zh_tw strings.conf' */ ?>
<?php
/* Smarty version 4.5.3, created on 2026-04-13 14:27:26
  from 'C:\TAOPIX\MediaAlbumWeb\Branding\ubbpro\lang\zh_tw strings.conf' */

/* @var Smarty_Internal_Template $_smarty_tpl */
if ($_smarty_tpl->_decodeProperties($_smarty_tpl, array (
  'version' => '4.5.3',
  'unifunc' => 'content_69dcfd4e891513_19795281',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
    '68e3101b4b4be6e8c65cbe9f2d75d8c9f4d74dbb' => 
    array (
      0 => 'C:\\TAOPIX\\MediaAlbumWeb\\Branding\\ubbpro\\lang\\zh_tw strings.conf',
      1 => 1653715006,
      2 => 'file',
    ),
  ),
  'includes' => 
  array (
  ),
),false)) {
function content_69dcfd4e891513_19795281 (Smarty_Internal_Template $_smarty_tpl) {
$_smarty_tpl->smarty->ext->configLoad->_loadConfigVars($_smarty_tpl, array (
  'sections' => 
  array (
    'Admin' => 
    array (
      'vars' => 
      array (
        'str_Title' => '管理員',
        'str_LabelBuidInformation' => '建立信息',
        'str_LabelUseExternalShoppingCart' => '使用外部購物車',
      ),
    ),
    'AdminConstants' => 
    array (
      'vars' => 
      array (
        'str_Title' => '系統設定',
        'str_LabelLocation' => '區域',
        'str_LabelCurrency' => '貨幣',
        'str_LabelDefaultLanguage' => '預設語言',
        'str_LabelDefaultPaymentMethods' => '預設付款方式',
        'str_LabelDefaultCreditLimit' => '預設信用額度',
        'str_LabelEmailSettings' => '電子郵件設定',
        'str_MessageEmailSent' => '電子郵件已經成功發送，請查看郵箱確認.',
        'str_MessageUpdated' => '已成功更新系統常數.',
        'str_MessageError' => '錯誤，尚未更新的系統常數.',
        'str_ConfirmationUpdateConstants' => '確認.\\n您確定是否更新系統設置?',
        'str_LabelIPAccessList' => 'IP 存取列表',
      ),
    ),
    'AdminCurrencies' => 
    array (
      'vars' => 
      array (
        'str_DeleteConfirmation' => '確認.\\n刪除貨幣\'^0\'嗎?',
        'str_MessageCurrencyDeleted' => '選擇貨幣已被刪除.',
        'str_TitleNewCurrency' => '新增貨幣',
        'str_TitleEditCurrency' => '編輯貨幣',
        'str_ErrorCurrencyExists' => '此貨幣代碼已存在.',
        'str_LabelISONumber' => 'ISO代碼',
        'str_LabelSymbolAtFront' => '符號在前',
        'str_LabelDecimalPlaces' => '小數點位數',
        'str_LabelExchangeRate' => '匯率',
        'str_LabelExchangeRateSet' => '匯率設定',
        'str_ErrorNoSymbol' => '錯誤.\\n請輸數貨幣符號.',
        'str_ErrorNoISONumber' => '錯誤.ISO代碼必須是3個字.',
        'str_ErrorUsedInConstants' => '貨幣不能被刪除，因為它是預設的貨幣.',
        'str_ErrorCurrencyUsedInCustomer' => '此貨幣不能被刪除，因為已經分配給客戶進行使用',
        'str_ErrorUsedInLicenseKey' => '貨幣不能被刪除，因為它已經被一個授權碼使用了',
      ),
    ),
    'AdminTaxRates' => 
    array (
      'vars' => 
      array (
        'str_DeleteConfirmation' => '確認\\n刪除稅率\'^0\'嗎?',
        'str_TitleNewTaxRate' => '新增稅率',
        'str_TitleEditTaxRate' => '編輯稅率',
        'str_LabelTaxRate' => '稅率',
        'str_MessageTaxRatesDeleted' => '選定的稅率已被刪除.',
        'str_ErrorTaxRateExists' => '稅率代碼已存在.',
        'str_ErrorNoRate' => '錯誤.\\n請輸入稅率.',
        'str_ErrorUsedInTaxZone' => '稅率不能刪除，因為它被用使於稅區.',
        'str_ErrorUsedInProduct' => '此稅率不能被刪除，因為它已經被應用到一個產品上了.',
        'str_ErrorUsedInOrder' => '此稅率不能被刪除，因為它已經被應用到一個訂單上了.',
        'str_ErrorAssignedToCustomer' => '此稅率不能被刪除，因為它已被分配給客戶。',
        'str_ErrorAssignedToLicenseKey' => '此稅率不能被刪除，因為它已被分配給壹個授權碼。',
      ),
    ),
    'AdminTaxZones' => 
    array (
      'vars' => 
      array (
        'str_DeleteConfirmation' => '確認\\n刪除稅區域\'^0\'嗎?',
        'str_TitleNewTaxZone' => '新增稅區',
        'str_TitleEditTaxZone' => '編輯稅區',
        'str_LabelTaxCode1' => '稅率等級1',
        'str_LabelTaxCode2' => '稅率等級2',
        'str_LabelTaxCode3' => '稅率等級3',
        'str_LabelTaxCode4' => '稅率等級4',
        'str_LabelTaxCode5' => '稅率等級5',
        'str_LabelUseTaxScript' => '稅務計算',
        'str_LabelUseVerificationScript' => '地址驗證',
        'str_LabelExternalDataLink' => '外部數據鏈接',
        'str_LabelShippingTaxCode' => '貨運稅代碼',
        'str_ErrorTaxZoneExists' => '稅區代碼已經存在.',
        'str_ErrorNoCountries' => '錯誤.\\n請選擇在這個稅區域內的國家.',
        'str_ErrorDuplicateCountries' => '請在繼續前刪除在此稅區域內的重複的國家.',
        'str_ErrorDuplicateCountriesCompany' => '此公司的一個或多個在這個稅區域內的國家已經被用在另外一個稅區域了.',
        'str_ErrorNoTaxCode' => '錯誤.\\n請選擇稅率代碼.',
        'str_ErrorNoShippingTaxCode' => '錯誤.\\n請選擇貨運稅代碼.',
        'str_MessageTaxZonesDeleted' => '選擇稅區已被刪除.',
      ),
    ),
    'AdminShippingMethods' => 
    array (
      'vars' => 
      array (
        'str_DeleteConfirmation' => '確認\\n刪除送貨方式\'^0\'嗎?',
        'str_TitleNewShippingMethod' => '新增貨運方式',
        'str_TitleEditShippingMethod' => '編輯貨運方式',
        'str_TitleSelectLogo' => '選擇商標',
        'str_LabelRequiresDelivery' => '需要交付',
        'str_ErrorShippingMethodExists' => '貨運方式代碼已存在.',
        'str_ErrorUsedInShippingRates' => '此送貨方式不能被刪除，因為它已經被一個送貨費率使用了.',
        'str_ErrorUsedInOrder' => '此送貨方式不能被刪除，因為它已經被一個訂購使用了.',
        'str_ErrorLogoUpload' => '上傳商標出現錯誤.',
        'str_LabelStoreGroupLabel' => '商店群組標籤',
        'str_LabelAllowCountryGrouping' => '允許按國別名稱分組',
        'str_LabelAllowRegionGrouping' => '允許按區域名稱分組',
        'str_LabelAllowStoreGroupGrouping' => '允許按商店名稱分組',
        'str_LabelExternalDataLink' => '使用外部數據鏈接',
        'str_LabelLogo' => '商標圖像',
        'str_LabelSelectLogo' => '建議該LOGO圖像的尺寸不超過600*150像素。',
        'str_AlertUploading' => '更新中...',
        'str_ErrorNoStoreGroupLabel' => '請輸入一個商店組標籤.',
        'str_MessageShippingMethodsDeleted' => '選定的運輸方式已被刪除.',
        'str_LabelUseDefaultShippingAddress' => '使用默認送貨地址',
        'str_LabelUseDefaultBillingAddress' => '使用默認賬單地址',
        'str_LabelUseCanModifyContactDetails' => '可以修改聯繫詳情',
      ),
    ),
    'AdminShippingZones' => 
    array (
      'vars' => 
      array (
        'str_DeleteConfirmation' => '確認\\n刪除送貨區域\'^0\'嗎?',
        'str_TitleNewShippingZone' => '新增貨運區',
        'str_TitleEditShippingZone' => '編輯貨運區',
        'str_ErrorNoCountries' => '錯誤.\\n請選擇這個貨運區的國家.',
        'str_ErrorDuplicateCountries' => '執行前，請刪除任何此航運區重複的國家.',
        'str_ErrorDuplicateCountriesCompany' => '在這個航運區的一個或多個國家已經使用這家公司在另一個航運區.',
        'str_ErrorShippingZoneExists' => '貨運區代碼已存在.',
        'str_ErrorUsedInShippingRates' => '貨運區不能刪除，因為它被用於貨運稅率 .',
        'str_ErrorUsedInOrder' => '此送貨區域不能被刪除，因為它已經被一個訂購使用了.',
      ),
    ),
    'AdminShippingRates' => 
    array (
      'vars' => 
      array (
        'str_DeleteConfirmation' => '確認\\n刪除送貨費用\'^0\'嗎?',
        'str_TitleNewShippingRate' => '新增貨運稅率',
        'str_TitleEditShippingRate' => '編輯貨運稅率',
        'str_ErrorShippingRateExists' => '貨運稅率代碼已存在.',
        'str_LabelShippingZone' => '貨運區',
        'str_LabelShippingRates' => '貨運稅率',
        'str_LabelShippingCost' => '運費',
        'str_LabelShippingSell' => '貨運價格',
        'str_LabelOrderValuePercent' => '訂單價值 %',
        'str_WeightPriceRangeStart' => '起始重量',
        'str_WeightPriceRangeEnd' => '截止重量',
        'str_ErrorNoShippingMethod' => '錯誤.\\n請選擇送貨方式.',
        'str_ErrorRangeStartError1' => '起始重量必須從0開始.',
        'str_ErrorRangeStartError2' => '重量開始值不能介於先前的範圍.',
        'str_ErrorRangeEndError' => '重量結束值不能低於開始值.',
        'str_ErrorNoShippingZone' => '錯誤.\\n請選擇貨運區.',
        'str_ErrorUsedInOrder' => '此送貨費用不能被刪除，因為它已經被一個訂單使用了.',
        'str_ErrorNoLicenseKeysSelected' => '無授權碼選定.',
      ),
    ),
    'AdminUsers' => 
    array (
      'vars' => 
      array (
        'str_DeleteUserConfirmation' => '確認.\\n刪除使用者 \'^0\'?',
        'str_TitleNewUser' => '新增使用者',
        'str_TitleEditUser' => '編輯使用者',
        'str_ConfirmationDeleteUser' => '你確定要刪除選定的用戶嗎?',
        'str_MessageUserDeleted' => '所選用戶已被刪除.',
        'str_LabelTypeLogin' => '登錄類型',
        'str_LabelBrandOwner' => '品牌的擁有者',
        'str_LabelCompanyAdmin' => '公司管理員',
        'str_LabelSiteAdmin' => '網站管理員',
        'str_LabelCreatorAdmin' => '創建管理員',
        'str_LabelStoreUser' => '商店用戶',
        'str_LabelStoreFieldLabel' => '商店:',
        'str_LabelProductionUser' => '生產用戶',
        'str_LabelSystemAdministrator' => '系統管理員',
        'str_LabelDistributionCentreLogin' => '配送中心用戶',
        'str_SiteTypeDistributionCentre' => '配送中心:',
        'str_LabelAPILogin' => 'API 登入',
        'str_LabelUseDefault' => '使用默認',
        'str_LabelAppendDefault' => '添加默認',
        'str_LabelOverrideDefault' => '覆蓋默認',
      ),
    ),
    'AdminOutputFormats' => 
    array (
      'vars' => 
      array (
        'str_ErrorOutputFormatExists' => '輸出格式代碼已存在.',
      ),
    ),
    'AdminProducts' => 
    array (
      'vars' => 
      array (
        'str_DeleteProductConfirmation' => '確認\\n刪除產品\'^0\'嗎?',
        'str_TitleNewProduct' => '新增產品',
        'str_TitleEditProduct' => '編輯產品',
        'str_LabelDefaultCover' => '預設封面',
        'str_LabelDefaultPaper' => '預設用紙',
        'str_LabelDefaultPageCount' => '預設頁數',
        'str_LabelJobTicketFields' => '自訂工單說明',
        'str_LabelCanCreateNewProjects' => '可以建立新作品',
        'str_LabelFixedQuantityRange' => '固定數量範圍',
        'str_LabelValuesSetOnUpload' => '注意<br>當產品上傳時設定名稱和類別.',
        'str_ErrorDuplicateProduct' => '產品代碼已存在.',
        'str_ErrorUsedInOrder' => '此產品不能被刪除，因為它已經被訂購了.',
        'str_ErrorUsedInShippingRate' => '此產品不能被刪除，因為它已經應用在一個運送費用上面了.',
        'str_ErrorUsedInVoucher' => '此產品不能被刪除，因為它已經被應用在一個折價券上了.',
        'str_MessageProductDeleted' => '選定的產品已被刪除.',
        'str_LabelAutoFlip' => '自動翻轉',
        'str_LabelThumbnailsView' => '縮圖查看',
        'str_LabelThumbnails' => '縮圖線',
        'str_LabelCoverType' => '封面類型',
        'str_LabelCoverHard' => '精裝',
        'str_LabelCoverSoft' => '平裝',
        'str_LabelPreviewAngle' => '預覽角度',
        'str_LabelPreviewType' => '預覽類型',
        'str_LabelHorizontalPageTurning' => '橫向翻頁',
        'str_LabelVerticalPageTurning' => '垂直翻頁',
        'str_LabelSlideshow' => '幻燈片播放',
        'str_LabelProductConfiguration' => '產品配置',
        'str_LabelCurrentlyInEditMode' => '正處在編輯模式裡面',
        'str_MessageCurrentlyInEditMode' => '所有近期的產品設置改變都不被保存，您確定要繼續嗎?',
        'str_ErrorCouldNotRefreshProductTree' => '不能更新產品樹. 不能連接.',
        'str_LabelProductPreviewIcon' => '產品預覽圖標',
        'str_LabelPageTurningPreview' => '開啟預覽',
        'str_ConfirmDeleteComponent' => '您確定要刪除這個組件嗎?',
        'str_ConfirmDeleteSection' => '您確定需要刪除這段內容以及組件嗎?',
        'str_ConfirmDeleteComponentPrice' => '你確定刪除這個組件的價格紀錄嗎?',
        'str_LabelTaxLevel' => '稅率等級',
      ),
    ),
    'AdminProductPricing' => 
    array (
      'vars' => 
      array (
        'str_TitleProductPricing' => '產品 \'^0\' 價格...',
        'str_TitleNewPricing' => '為產品\'^0\'新建價格...',
        'str_TitleEditPricing' => '為產品\'^0\'編輯價格...',
        'str_LabelShoppingCart' => '購物車類型:',
        'str_LabelShoppingCartTypeTAOPIX' => 'TAOPIX? 網頁',
        'str_DeletePricingConfirmation' => '確認\\n刪除授權碼的\'^0\'產品價格嗎？',
        'str_DeleteProductPriceListConfirmation' => '確認. 刪除價目表 \'^0\'?',
        'str_ErrorPriceListUsedInProduct' => '價格表不能刪除，因為它已被分配到產品',
      ),
    ),
    'AdminPaymentMethods' => 
    array (
      'vars' => 
      array (
        'str_TitleEditPaymentMethod' => '編輯付款方式',
        'str_LabelAvailableWhenShipping' => '可用於需交付運送',
        'str_LabelAvailableWhenNotShipping' => '可用於不需交付運送',
      ),
    ),
    'AdminVouchers' => 
    array (
      'vars' => 
      array (
        'str_DeleteVoucherConfirmation' => '刪除折價券 \'^0\'?',
        'str_TitleNewVoucher' => '新增折價券',
        'str_TitleEditVoucher' => '編輯折價券',
        'str_TitleCreateVouchers' => '建立折價券',
        'str_ErrorVoucherExists' => '折價券代碼已存在.',
        'str_LabelDefaultDiscount' => '默認折扣',
        'str_LabelRepeatType' => '重複類型',
        'str_LabelRepeatTypeSINGLE' => '單次',
        'str_LabelRepeatTypeMULTI' => '多次e',
        'str_LabelRepeatTypeMULTIONCECUSTOMER' => '多次(每一客戶只可使用一次)',
        'str_LabelRepeatTypeMULTIONCEKEY' => '多次(每一授權碼只可使用一次)',
        'str_LabelDiscountSection' => '折扣範圍',
        'str_LabelDiscountSectionPRODUCT' => '產品',
        'str_LabelDiscountSectionSHIPPING' => '貨運',
        'str_LabelDiscountSectionTOTAL' => '總計',
        'str_LabelDiscountType' => '折扣類型',
        'str_LabelDiscountTypeFOC' => '免費',
        'str_LabelDiscountTypeVALUE' => '金額折抵',
        'str_LabelDiscountTypePERCENT' => '折扣折抵',
        'str_LabelDiscountTypeBOGOF' => '購買數量一本免費',
        'str_LabelDiscountTypeBOGPOFF' => '購買數量一本折扣折抵',
        'str_LabelDiscountTypeBOGVOFF' => '購買數量一本金額折抵',
        'str_LabelDiscountTypeVALUESET' => '數值',
        'str_LabelDiscountValue' => '折扣數值',
        'str_LabelVoucherTypeDISCOUNT' => '折扣',
        'str_LabelVoucherTypePREPAID' => '預付費',
        'str_LabelVoucherTypeGIFTCARD' => '禮品卡',
        'str_LabelVoucherTypeSCRIPT' => 'Script',
        'str_LabelGenerateRandomCode' => '產生隨機折價券代碼',
        'str_LabelCodePrefix' => '代碼前置文字',
        'str_LabelStartNumber' => '開始號碼',
        'str_LabelMinOrderQty' => '最少訂購數量',
        'str_LabelMaxOrderQty' => '最大訂購數量',
        'str_LabelLockOrderQty' => '鎖定訂購數量',
        'str_LabelProductCategory' => '產品類別',
        'str_LabelProductCode' => '產品代碼',
        'str_LabelProductName' => '產品名稱',
        'str_LabelUserID' => '客戶身分',
        'str_ButtonImportCodes' => '輸入代碼',
        'str_ButtonDeleteExpired' => '刪除過期',
        'str_ButtonDeleteSelected' => '刪除所選',
        'str_CreateVoucherConfirmation' => '您是否確定建立 ^0 折價券?',
        'str_ImportVoucherConfirmation' => '您確定要輸入所選的文件?',
        'str_DeleteSelectedVoucherConfirmation' => '您是否確定刪除選定的折價券?',
        'str_DeleteExpiredVoucherConfirmation' => '您是否確定要刪除所有過期的折價券?',
        'str_DeleteNewVoucherConfirmation' => '您是否確定要刪除新建立的折價券?',
        'str_TitleVoucherCreationResult' => '折價券建立的結果',
        'str_ErrorNoCustomer' => '請選擇客戶.',
        'str_ErrorNoRepeatType' => '請選擇折價券重複類型.',
        'str_ErrorNoDiscountSection' => '請選擇折價券的項目.',
        'str_ErrorNoDiscountType' => '請選擇折價券的類型.',
        'str_ErrorInvalidStartNumber' => '請輸入一個有效的折價券的開始數字.',
        'str_ErrorNoVoucherCodePrefix' => '請輸入折價券代碼的前置碼.',
        'str_ErrorInvalidDiscountValue' => '請輸入一個有效的折扣值.',
        'str_ErrorInvalidMinQuantity' => '請輸入最少訂購量 1~9999.',
        'str_ErrorInvalidMinQuantity2' => '最少訂購數量不能低於最大訂購數.',
        'str_ErrorInvalidMaxQuantity' => '請輸入最大訂購量 1~9999.',
        'str_ErrorInvalidQuantity' => '請輸入建立折價券數量 2~3000.',
        'str_ErrorInvalidMaxDiscountQuantity' => '請輸入最大的折扣值在1至9999之間',
        'str_DeletePromotionConfirmation' => '刪除促銷活動 \'^0\' 及其相關的折價券?',
        'str_TitleNewPromotion' => '添加促銷活動',
        'str_TitleEditPromotion' => '編輯促銷活動',
        'str_ErrorPromotionExists' => '擁有此代碼的促銷活動已經存在.',
        'str_LabelPromotionCode' => '促銷活動代碼',
        'str_LabelVoucherCount' => '折價券次數',
        'str_TitlePromotionVouchers' => '用于促銷活動的折價券 \'^0\'...',
        'str_VouchersDeleted' => '折價券已被刪除.',
        'str_ErrorVouchersAssignedToProductionSite' => '公司本次促銷不能改變，因為分配給公司的生產現場的折價券。',
        'str_LabelUsedTimes' => '使用',
        'str_VoucherInUse' => '此折價券不能被修改或刪除，因為它是目前使用的訂單.',
        'str_VouchersInUse' => '以下折價券不能被修改或刪除，因為他們目前正在使用的訂單:',
        'str_ErrorVouchersAssignedToOrder' => '此折價券的生產現場不能改變，因為它已經在使用的訂單.',
        'str_ErrorVouchersExist' => '下列折價券無法輸入，這些折價券的代碼已經存在:',
        'str_LabelDetails' => '詳情',
        'str_LabelSettings' => '設置',
        'str_TitleVoucherTypeChange' => '更改折價券類型',
        'str_TitleVoucherTypeMessage' => '請問妳確定要在折價券類型裏面更改預付費嗎？',
        'str_LabelDiscountMethod' => '折扣類型',
        'str_LabelDiscountQty' => '最大折扣數量',
        'str_LabelDiscountMethodMATCHINGPRODUCT' => '所有匹配範圍',
        'str_LabelDiscountMethodSPREADORDER' => '分佈在匹配範圍',
        'str_LabelDiscountMethodLOWEST' => '價格最低的匹配線',
        'str_LabelDiscountMethodHIGHEST' => '價格最高的匹配線',
      ),
    ),
    'AdminGiftCards' => 
    array (
      'vars' => 
      array (
        'str_LabelGenerateRandomCode' => '生成隨機的折價券代碼',
        'str_LabelCodePrefix' => '代碼前綴',
        'str_LabelStartNumber' => '起始號碼',
        'str_TitleNewGiftCard' => '新建禮品卡',
        'str_TitleEditGiftCard' => '編輯禮品卡',
        'str_TitleCreateGiftCard' => '創建禮品卡',
        'str_DeleteGiftcardConfirmation' => '確認要刪除禮品卡 \'^0\'嗎?',
        'str_GiftcardsDeleted' => '選擇的禮品卡已被刪除',
        'str_LabelGiftcardValue' => '禮品卡價值',
        'str_ButtonImportCodes' => '導入代碼',
        'str_ErrorGiftcardValue' => '請輸入禮品卡的價值。',
        'str_ErrorGiftcardExists' => '此代碼的禮品卡已經存在。',
        'str_ErrorNoGiftcardCodePrefix' => '请输入礼品卡的代码前缀。',
        'str_ErrorGiftcardsExist' => '不能導入這些禮品卡的代碼，因為已經存在此禮品卡：',
        'str_CreateGiftcardConfirmation' => '妳確定要創建 ^0禮品卡嗎？',
        'str_ImportGiftcardConfirmation' => '您確定您要導入選定的文件嗎？',
        'str_DeleteSelectedGiftcardConfirmation' => '妳確定要刪除選定的禮品卡嗎？',
        'str_DeleteExpiredGiftcardConfirmation' => '您確定要刪除所有過期的禮品卡嗎？',
        'str_DeleteNewGiftcardConfirmation' => '妳確定要刪除新創建的禮品卡嗎？',
        'str_TitleGiftcardCreationResult' => '禮品卡創建結果',
        'str_LabelRedeemUserID' => '使用者的用戶ID',
        'str_LabelRedeemFirstName' => '使用者的用戶姓',
        'str_LabelRedeemLastName' => '使用者的用戶名',
        'str_LabelRedeemEmailAddress' => '使用者用戶電子郵件地址',
        'str_LabelUserID' => '客戶ID',
      ),
    ),
    'AdminCustomers' => 
    array (
      'vars' => 
      array (
        'str_DeleteConfirmation' => '刪除顧客\'^0\'嗎?',
        'str_TitleNewCustomer' => '新增客戶',
        'str_TitleEditCustomer' => '編輯客戶',
        'str_LabelUseLicenseKeyAddressForShipping' => '貨運使用授權碼地址',
        'str_LabelUseLicenseKeyAddressForBilling' => '帳單使用授權碼地址',
        'str_LabelSendMarketingInformation' => '發送銷售訊息',
        'str_LabelUseLicenceKeyAddressControl' => '使用授權碼地址偏好',
        'str_ErrorInvalidAccountBalanceValue' => '錯誤.\\n請輸入一個有效已使用帳戶額度值.',
        'str_ErrorUsedInOrder' => '以下客戶不能被刪除 \'^0\' 因為他們已經下訂單了.',
        'str_CustomersDeleted' => '選定的客戶已被刪除.',
        'str_AccountSettings' => '帳戶設置',
        'str_PaymentSettings' => '付款設置',
        'str_AddressDetails' => '詳細地址',
        'str_LabelSettings' => '設置',
        'str_CreditSettings' => '信用設置',
        'str_AddressSettings' => '地址設置',
      ),
    ),
    'AdminAutoUpdateApplication' => 
    array (
      'vars' => 
      array (
        'str_LabelOperatingSystem' => '作業系統',
        'str_LabelArchiveName' => '檔案名稱',
        'str_LabelExeName' => '可執行的名稱',
        'str_DeleteMacConfirmation' => '刪除 Macintosh 客戶端?',
        'str_DeleteWindowsConfirmation' => '刪除 Windows 客戶端?',
        'str_DeleteApplicationConfirmation' => '刪除選定的應用程序更新?',
        'str_DeleteApplications' => '選定的應用程序更新已被刪除.',
      ),
    ),
    'AdminAutoUpdateApplicationFiles' => 
    array (
      'vars' => 
      array (
        'str_LabelPrivate' => '專屬的',
        'str_DeleteMaskConfirmation' => '刪除選定的遮罩?',
        'str_DeleteBackgroundConfirmation' => '刪除選定的背景?',
        'str_DeleteScrapbookPictureConfirmation' => '刪除所選的剪貼簿圖片?',
        'str_DeleteFramesConfirmation' => '刪除選定的框架?',
        'str_DeleteMaskFiles' => '選定的遮罩更新已被刪除.',
        'str_DeleteBackgroundFiles' => '選定的背景更新已被刪除.',
        'str_DeleteScrapbookFiles' => '選定的剪貼簿圖片更新已被刪除.',
        'str_DeleteFramesFiles' => '選定的框架更新已被刪除.',
      ),
    ),
    'AdminAutoUpdateLicenseKeys' => 
    array (
      'vars' => 
      array (
        'str_TitleEditLicenseKey' => '編輯授權碼',
        'str_LabelCurrencyCode' => '貨幣代碼',
        'str_LabelCurrency' => '貨幣',
        'str_DeleteLicenseKeyConfirmation' => '你確定要刪除選定的授權碼?',
        'str_DeleteLicenseKey' => '選定的授權碼已被刪除.',
        'str_WarningContinue' => '你要繼續嗎?',
        'str_ErrorLoginExists' => '這些授權碼認證細節已經存在',
        'str_ShowPricesWithTax' => '顯示含稅價格',
        'str_ShowTaxBreakdown' => '稅金明細',
        'str_ShowZeroTax' => '顯示零稅金',
        'str_ShowAlwaysTaxTotal' => '永遠顯示稅金總計',
        'str_LabelCanCreateUserAccounts' => '允許建立使用者帳戶',
        'str_LabelUseAddressForShipping' => '應用於貨運地址',
        'str_LabelUseAddressForBilling' => '應用於帳單地址',
        'str_ErrorUsedInProductPricing' => '授權碼不能刪除，因為它被用於在產品價格.',
        'str_ErrorUsedInComponentPricing' => '此授權碼不能被刪除，因為它已經應用在一個組件價格上面.',
        'str_ErrorUsedInCustomer' => '授權碼不能刪除，因為它被分配給客戶.',
        'str_ErrorUsedInVoucher' => '授權碼不能刪除，因為它被分配到折價券.',
        'str_LicenseKeyAddress' => '授權碼的地址',
        'str_LicenseKeySettings' => '授權碼的設置',
        'str_PaymentSettings' => '付款的設置',
        'str_LabelSettings' => '設置',
        'str_LabelAddressVerificationFailed' => '地址驗證失敗',
        'str_LabelAuthenticate1Required' => '認證 1 請求.',
        'str_WarningUsedLicenseKey' => '下面的授權碼不能被刪除',
        'str_LabelAuthenticate1' => '認證 1',
        'str_LabelAuthenticate2' => '認證 2',
        'str_LabelDesignerSplashScreen' => '設計端啟動畫面',
        'str_LabelBanner' => '設計端橫幅',
        'str_MessageSplashScreenFileTypes' => '只允許JPG的文件',
        'str_MessageBannerFileTypes' => '只允許png的文件',
        'str_ButtonUpdateBannerImage' => '更新橫幅圖像',
        'str_ButtonRemoveBannerImage' => '清除橫幅圖像',
        'str_ButtonResetBannerImage' => '重置橫幅圖像',
        'str_ButtonUpdateSplashScreenImage' => '更新啟動畫面圖像',
        'str_ButtonRemoveSplashScreenImage' => '清除啟動畫面圖像',
        'str_ButtonResetSplashScreenImage' => '重置啟動畫面圖像',
        'str_TitleSelectSplashScreenImage' => '選擇啟動畫面圖像',
        'str_TitleSelectBannerImage' => '選擇橫幅圖像',
        'str_MessageGuestWorkflowMode' => '訪客流程模式',
        'str_LabelDisabled' => '關閉',
        'str_LabelEnabled' => '開啓',
        'str_LabelOff' => '關閉',
        'str_LabelPrompt' => '提示',
        'str_LabelAutomatic' => '自動',
        'str_ErrorUsernameAlreadyExistsInBrand' => '授權碼不能被更新，因為更改品牌會導致那個品牌的用戶帳號重複.',
      ),
    ),
    'AdminAutoUpdateProducts' => 
    array (
      'vars' => 
      array (
        'str_DeleteProductConfirmation' => '刪除所選產品的自動更新資料?<br><br>請注意，只有在自動更新的資料將被刪除.',
        'str_DeleteProducts' => '所選產品的更新已被刪除.',
        'str_ErrorFileDoesntExist' => '一些選定的產品不能被刪除，因為它們是沒有關連的文件.',
      ),
    ),
    'AdminOutputDevices' => 
    array (
      'vars' => 
      array (
        'str_ErrorOutputDeviceExists' => '輸出裝置代碼已經存在',
        'str_ErrorUsedInOutputFormat' => '輸出設備不能刪除，因為它被分配到輸出格式.',
      ),
    ),
    'AdminExport' => 
    array (
      'vars' => 
      array (
        'str_ButtonNewExport' => '新增匯出',
        'str_ButtonSummary' => '摘要',
        'str_LabelLangOrder' => '排序',
        'str_LabelLangDefault' => ' (預設)',
        'str_LabelFormat' => '匯出格式',
        'str_LabelFormatTXT' => 'TXT (tab 分隔)',
        'str_LabelFormatXML' => 'XML (可擴展標記)',
        'str_LabelPayment' => '包含付費資料',
        'str_LabelXmlBeautify' => '優化的 XML',
        'str_LabelDateType' => '搜尋',
        'str_LabelOrdersReceived' => '訂單已接獲',
        'str_LabelOrdersPrinted' => '訂單已輸出',
        'str_LabelOrdersShipped' => '訂單已出貨',
        'str_WarningNoResult' => '無符合搜尋標準的項目.',
        'str_LabelExportParameters' => '導出參數',
        'str_LabelExportFormats' => '輸出格式',
        'str_LabelRunReport' => '運行報告',
        'str_LabelNoItemsFound' => '沒有項目尋獲！請再次嘗試用不同的參數...',
      ),
    ),
    'AdminBranding' => 
    array (
      'vars' => 
      array (
        'str_DeleteConfirmation' => '刪除品牌\'^0\'以及所有相關的自動更新數據嗎?',
        'str_TitleNewBranding' => '新增品牌',
        'str_TitleEditBranding' => '編輯品牌',
        'str_TitleEditDefaultBranding' => '編輯預設品牌',
        'str_LabelFolderName' => '檔案夾名稱',
        'str_LabelDisplayURL' => '顯示網址',
        'str_LabelWebURL' => '網頁網址',
        'str_LabelMainWebsiteURL' => '主要網址',
        'str_LabelMacDownloadLink' => 'Mac下載連接',
        'str_LabelWin32DownloadLink' => 'Win32下載連接',
        'str_LabelSupportTelephone' => '技術支援電話',
        'str_LabelSupportEmail' => '技術支援Email',
        'str_TitleBrandingAdvert' => 'Taopix設計廣告',
        'str_TitleSocialSharing' => '社交網絡共享',
        'str_TitlePageTurningPreview' => '翻頁預覽',
        'str_TitlePageTurningPreviewLimit' => '翻頁預覽限制數量',
        'str_LabelPageTurningPreviewLicense' => '翻頁預覽許可',
        'str_TitleSharingOptions' => '分享選項',
        'str_LabelShareByEmailMethod' => '通過郵件方式分享',
        'str_LabelShareByEmailDisabled' => '關閉',
        'str_LabelShareByEmailTaopixControlCentre' => 'TAOPIX控制中心',
        'str_LabelShareByEmailMailToLink' => '通過郵件發送連接',
        'str_LabelBrandEmailSettings' => '品牌郵件設定',
        'str_LabelUseDefaultEmailSettings' => '使用預設郵件設定',
        'str_MessageEmailSent' => '電子郵件已經成功發送，請檢查郵箱確認.',
        'str_MessageProductionSiteChanged' => '改變這個品牌的生產現場，會對現有的路由規則的影響. 請檢查路由表，以確保這些規則仍然是正確的.',
        'str_ErrorNoFolderName' => '錯誤.請輸入檔案夾名稱 .',
        'str_ErrorNoApplicationName' => '錯誤.請輸入應用程式名稱.',
        'str_ErrorBrandingExists' => '品牌名稱已存在.',
        'str_ErrorUsedInLicenseKey' => '品牌不能刪除，因為它被分配到授權碼.',
        'str_ErrorDisplayURLNotValid' => '顯示網址似乎不是正確的.',
        'str_ErrorWebURLNotValid' => '網站網址不出現是正確的.',
        'str_ErrorWebURLNoDisplayURL' => '您不能輸入一個網站網址而沒有顯示網址.',
        'str_ErrorWebURLEqualsDisplayURL' => '顯示的網址和網站網址是可以不一樣.',
        'str_MessageProductionSiteCompanyChanged' => '這將重新分配到不同的公司的品牌擁有者。你想繼續嗎?',
        'str_ErrorFollowingUsedInLicenseKey' => '以下的品牌不能刪除，因為它們已分配到授權碼:',
        'str_BrandingDeleted' => '選擇品牌已被刪除.',
        'str_PaymentSettings' => '付款設置',
        'str_ErrorNoSectionValue' => '請填寫 \'^0\' 電子郵件欄.',
        'str_ErrorEmailEmpty' => '因為你尚未完成的部分，無法發送測試電子郵件.',
        'str_LabelBrandEmails' => '商標品牌郵件',
        'str_LabelResetPassword' => '重置密碼',
        'str_LabelOrderUploaded' => '訂單上傳',
        'str_LabelNumberOfDays' => '已下單時間',
        'str_LabelSavePromptDelay' => '在線版設計端保存提示延時（分鐘）',
        'str_LabelOnlineDesignerURL' => '在線版設計端網址',
        'str_LabelOnlineDesignerLogoutURL' => '在線版設計端退出登入網址',
        'str_TitleOnlineDesignerSettings' => '在線版設計端設置',
        'str_TitleGoogleAnalytics' => 'Google分析',
        'str_LabelGoogleAnalyticsCode' => 'Google 分析代碼',
        'str_LabelDefaultCommunicationPreference' => '默認通訊偏好設置',
        'str_LabelSubscribed' => '簽署',
        'str_LabelUnsubscribed' => '不簽署',
      ),
    ),
    'Login' => 
    array (
      'vars' => 
      array (
        'str_LabelDontHaveAnAccount2' => '點擊這裡',
        'str_LabelForgotPassword' => '忘記了您的密碼嗎？',
        'str_TextResetPassword' => '要重置您的密碼，請輸入您的帳戶已註冊的用戶名和電子郵件地址。輸入一個新的密碼，我們會向您發送電子郵件，然後你就可以改變。',
        'str_ConfirmationResetPassword' => '您的密碼已重新設定並已電子郵件通知您新的密碼.',
        'str_ErrorAccountMisMatch' => '帳戶無法與客戶群組匹配',
        'str_ErrorSessionExpired' => '您的訂購期間已過期',
        'str_ErrorAccountNotACustomer' => '此帳戶非客戶',
        'str_ButtonCreateAccount' => '創建賬戶',
        'str_MessageUseYourAccount' => '我們的購物方便快捷，使用您的帳戶：',
        'str_LabelOrderAndShare' => '訂購以及分享你的作品',
        'str_LabelTrackOrders' => '跟蹤你的訂單',
        'str_LabelViewOrderHistory' => '查看您的訂單記錄',
        'str_LabelReorderProjects' => '重複訂購你的作品',
        'str_TitleSignIn' => '登入',
        'str_previewProtectPassword' => '此預覽圖受密碼保護',
        'str_ErrorPreviewPasswordWrong' => '您的密碼不正確',
        'str_LoginNotForControlCentre' => '您的登陸信息不能用作登陸TAOPIX控制中心',
        'str_MessageDontHaveAnAccount' => '您沒有賬戶嗎？',
      ),
    ),
    'NewAccount' => 
    array (
      'vars' => 
      array (
        'str_ErrorAccountExists' => '該用戶名已經存在',
      ),
    ),
    'CreditCardPayment' => 
    array (
      'vars' => 
      array (
        'str_OrderiPay88_2' => '信用卡',
        'str_OrderiPay88_6' => 'Maybank2U',
        'str_OrderiPay88_8' => 'Alliance Online Transfer',
        'str_OrderiPay88_10' => 'AM Bank',
        'str_OrderiPay88_14' => 'RHB',
        'str_OrderiPay88_15' => 'Hong Leong Bank Transfer',
        'str_OrderiPay88_16' => 'FPX',
        'str_OrderiPay88_17' => '移動支付',
        'str_OrderiPay88_20' => 'CIMB Click',
        'str_OrderiPay88_21' => '中國銀聯',
        'str_OrderiPay88_22' => '網絡現金',
        'str_OrderiPay88_23' => 'Meps Cash',
        'str_OrderiPay88_25' => '信用卡 (美金)',
        'str_OrderiPay88_33' => 'Paypal',
        'str_OrderPaygent_01' => 'ATM',
        'str_OrderPaygent_02' => 'Credit Card',
        'str_OrderPaygent_03' => '便利店',
        'str_OrderPayone_ELV' => '直接付款',
        'str_OrderPayone_CC' => 'Credit Card',
        'str_OrderPayone_SB' => '銀行轉賬',
        'str_OrderPayone_WLT' => 'e-Wallet (Paypal)',
        'str_OrderINILITE_CARD' => '信用卡',
        'str_OrderINILITE_DIRECTBANK' => 'DirectBank',
        'str_OrderINILITE_VBANK' => 'VBank',
        'str_OrderINILITE_HPP' => 'HPP',
        'str_OrderINILITE_VBANK_AdditionalInfo' => 'VBank Additional Information For Your Records',
        'str_OrderINILITE_VBANK_AccountNumber' => '銀行賬戶號碼',
        'str_OrderINILITE_VBANK_BankName' => '開戶行',
        'str_OrderINILITE_VBANK_AccountHolderName' => '賬戶持卡人名稱',
        'str_OrderINILITE_VBANK_SenderName' => '發件人：',
        'str_OrderINILITE_VBANK_WireTransferDate' => '電匯日期：',
        'str_OrderINILITE_VBANK_TransactionReference' => '交易參考號：',
        'str_OrderINILITE_Bank_01' => '韓國工業銀行',
        'str_OrderINILITE_Bank_02' => '農業合作社',
        'str_OrderINILITE_Bank_03' => '韓國外幣銀行',
        'str_OrderINILITE_Bank_04' => '韓國國民銀行（原韓國住宅銀行）',
        'str_OrderINILITE_Bank_05' => '朝興銀行',
        'str_OrderINILITE_Bank_06' => '全國農業協同組合聯合會（農協）',
        'str_OrderINILITE_Bank_07' => '農業合作組織（單位農協）',
        'str_OrderINILITE_Bank_08' => '友利銀行（Woori Bank）',
        'str_OrderINILITE_Bank_09' => '朝興銀行',
        'str_OrderINILITE_Bank_10' => '第一銀行',
        'str_OrderINILITE_Bank_11' => '釜山銀行',
        'str_OrderINILITE_Bank_12' => '韓國郵政',
        'str_OrderINILITE_Bank_13' => '韓亞銀行（Hana Bank）',
        'str_OrderINILITE_Bank_14' => '新韓銀行（Shinhan Bank）',
        'str_OrderPlanosci_1' => 'nowa',
        'str_OrderPlanosci_2' => 'anulowana',
        'str_OrderPlanosci_3' => 'odrzucona',
        'str_OrderPlanosci_4' => 'rozpoczÍta',
        'str_OrderPlanosci_5' => 'oczekuje na odbiÛr',
        'str_OrderPlanosci_6' => 'autoryzacja odmowna',
        'str_OrderPlanosci_7' => 'p≥atno∂Ê odrzucona',
        'str_OrderPlanosci_99' => 'p≥atno∂Ê odebrana - zakoÒczona',
        'str_OrderPlanosci_888' => 'b≥Ídny status',
        'str_OrderPlanosci_0' => 'brak statusu',
        'str_OrderDibs_0' => 'CreditCard',
        'str_OrderDibs_1' => 'Klarna發票',
        'str_GMOPrompt' => '請選擇付款方式',
        'str_GMOCreditCard' => 'CreditCard',
        'str_GMOConvinienceStore' => '便利店',
        'str_GMOEdy' => '移動EDY',
        'str_GMOSuica' => '移動Suica',
        'str_GMOPayEasy' => 'Pay-easy',
        'str_GMOPayPal' => 'PayPal',
        'str_GMONetid' => 'iD Net',
        'str_GMOWebMoney' => 'WebMoney',
        'str_TCONPrompt' => '請選擇付款方式',
        'str_TCONCreditCard' => 'CreditCard',
        'str_TCONBank' => '銀行匯款',
        'str_TCONPostalBank' => '郵政匯款',
        'str_TCONInternetBank' => '網銀匯款',
        'str_TCONCOD' => '現金支付',
        'str_TCONCorporateSettlement' => '公司結算',
        'str_TCONPaymentInvoice' => '付款發票',
        'str_TCONOnlinePaymentInvoice' => '在線付款發票',
        'str_TCONPayEasy' => 'Pay Easy',
        'str_TCONShoppingCredit' => '購物車信用度',
        'str_TCONSuicaInternetService' => 'Suica互聯網服務',
        'str_DropDownPleaseSelectAPaymentType' => '請選擇付款方式',
        'str_CIELOCreditCard' => '信用卡',
        'str_CIELODebitCard' => '轉賬卡',
        'str_CIELOTransactionIDError' => 'The Transaction ID\'s do not match!!!',
        'str_CIELOTransactionAuthError' => 'The transaction has not been authorized.',
        'str_CIELOCertificateNotApproved' => 'CERTIFICADO INVÁLIDO - O certificado da transação não foi aprovado.',
        'str_CIELOTimeout' => 'o Limite de Tempo da transação foi estourado.',
      ),
    ),
    'Order' => 
    array (
      'vars' => 
      array (
        'str_OrderBankInfo' => '<div style="margin-left: 20px;margin-top:30px;"><strong>請您就近到銀行將所購買商品的款項匯入指定帳戶</strong><br><br>開戶銀行：恆生銀行<br>帳戶名稱：Ubabybaby Limited<br>帳戶號碼： 390-287902-883<br><br><ol><li style="font-weight:bold;">請將款項存到以下戶口，並於存款收據上寫上訂單編號，然後電郵至 cs@ubabybaby.com。<br>恆生銀行戶口號碼：390-287902-883<br><p></p></li><li style="font-weight:bold;">完成訂購程序後，請於一星期內入帳於以上戶口，否則訂單作廢及檔案不獲上載。</li></ol></div>',
        'str_TitleOrderCancellation' => '取消訂單',
        'str_TitleOrderConfirmation' => '確認訂單',
        'str_TitlePayLaterConfirmation' => '延遲付款編號',
        'str_TitleOrderStageQty' => '訂單',
        'str_HeadingOrderStageQty' => '訂單明細',
        'str_TitleOrderStageShipping' => '郵寄 / 帳單',
        'str_HeadingOrderStageShipping' => '郵寄 / 帳單明細',
        'str_TitleOrderStagePayment' => '付款',
        'str_HeadingOrderStagePayment' => '付款',
        'str_TitleOrderStageCreditCardPayment' => '信用卡付款',
        'str_TitleOrderPreview' => '訂單檢視 \'^0\'',
        'str_LabelEnterOrderVoucher' => '如果您持有優惠券，請輸入代碼並點擊\'兌現\'按鈕.',
        'str_LabelEnterOrderGiftCard' => '如果您持有禮品卡，請輸入代碼並點擊\'兌現\'按鈕.',
        'str_LabelOrderVoucherAccepted' => '接受折價券',
        'str_OrderDiscountConfirmation' => '您訂單折扣已受理，將會在訂單總價中計算並顯示.',
        'str_LabelOrderItemListQty' => '數量',
        'str_LabelOrderItemListItemTotal' => '項目總價',
        'str_LabelShippingTitle' => '送貨詳細信息',
        'str_LabelOrderShipping' => '郵寄方式',
        'str_LabelOrderTax' => '總稅率',
        'str_LabelTotalTitle' => '付款詳情',
        'str_LabelOrderShippingTotal' => '運費總計',
        'str_LabelItemSubTotal' => '項目小計',
        'str_LabelSubTotal' => '小計',
        'str_LabelMetadataLegend' => '自定義您的選項',
        'str_LabelOrderFooterSubTotal' => '附加項目小計',
        'str_LabelOrderFooterTotal' => '附加項目總計',
        'str_LabelAdditionalItems' => '附加項目',
        'str_LabelOrderSubTotal' => '訂單小計',
        'str_LabelOrderTotalItems' => '項目總計',
        'str_LabelIncludesTax' => '(包含 ^0% ^1: ^2)',
        'str_LabelIncludesTaxTotal' => '(包含稅金: ^0)',
        'str_LabelOrderUpdateItemTotal' => '點擊以更新總項目',
        'str_LabelSameAsShippingAddress' => '同送貨地址',
        'str_LabelUpdateShippingAddress' => '更新貨運地址',
        'str_LabelUpdateShippingContactDetails' => '更新貨運聯絡資料',
        'str_LabelUpdateAccountDetails' => '更新帳戶信息',
        'str_LabelUpdateBillingAddress' => '更新帳單地址',
        'str_LabelUpdateBillingContactDetails' => '更新帳單聯系方式',
        'str_LabelOrderShippingCost' => '運費',
        'str_LabelAddressSearch' => '搜索商店',
        'str_LabelListOfStores' => '商店名單',
        'str_MessageNoMatchingStoresFound' => '找不到匹配的門店',
        'str_LabelSelectComponent' => '選擇 ^0',
        'str_LabelSelectStore' => '價格差異',
        'str_LabelPriceDifference' => '價格差異',
        'str_LabelAdditionalPage' => '^0 額外的頁面',
        'str_LabelAdditionalPages' => '^0 額外的頁面',
        'str_ErrorNoShippingOptionsAvailable' => '無貨運方式可供選擇.<br>如需協助，請聯繫客服人員.',
        'str_ErrorNoPrice' => '錯誤.\\n您的訂單無法受理，因為無可用的定價資料。如需協助，請聯繫客服人員.',
        'str_ErrorNoComponent' => '錯誤.\\n您的訂單不能接受，因為沒有定價。如需協助，請聯繫客服人員.',
        'str_ErrorNoComponent2' => '錯誤.\\n必須選定.',
        'str_ErrorNoStore' => '錯誤.\\n請選擇商店收集訂單.',
        'str_ErrorNoShippingRate' => '您更改了您的送貨地址，此頁面將被刷新才有效',
        'str_ErrorNoPaymentMethodsAvailable' => '無可用的付款方式.<br>如需協助，請聯繫客服人員.',
        'str_ErrorNoPaymentMethod' => '錯誤.\\n請選擇所需的付款方式.',
        'str_ErrorOverCreditLimit' => '錯誤.\\n訂單已超過您的信用額度. 請選擇其他的付款方式.',
        'str_ErrorCannotUploadOrder' => '您的訂單已在生產無法再次上傳。如需協助，請聯繫客服人員.',
        'str_ErrorCannotUploadProject' => '您的作品已經上載，我們現在正在等待付款。如需協助，請聯繫客服人員.',
        'str_ErrorProductNotAvailable' => '產品無法再使用。如需協助，請聯繫客服人員.',
        'str_ErrorDeviceNotSupported' => '當您嘗試編輯產品，此時需要高級的編輯器，它只能在大屏幕設備，如平板電腦和筆記本電腦中使用。',
        'str_ErrorProductCodeMismatch' => '你不能重新上傳您的訂單，因為你已經改變的產品。如要繼續，你必須恢復到原來的產品或與客戶服務聯絡尋求協助.',
        'str_ErrorCoverPageCountMismatch' => '無法重新上傳您的訂單，訂購的封面只適合 ^0 頁.如要繼續您必須減少頁數或聯繫客服人員.',
        'str_ErrorPaperPageCountMismatch' => '你不能重新上傳訂購，因為你僅支付了一個頁面. 要繼續比必須減少頁數或者聯繫客戶幫助.',
        'str_ErrorPaperPageCountMismatch2' => '無法重新上傳您的訂單，您支付最多 ^0 頁面.如要繼續您必須減少頁數或聯繫客服人員.',
        'str_ErrorCannotProcessOrder' => '處理您的訂單時發生了問題，請聯絡客服人員取得協助.',
        'str_ConfirmCancellation' => '確認.\\n您是否確定要取消訂購？',
        'str_ConfirmRemove' => '確認\\n你確定要刪除所選的訂單?',
        'str_ButtonConfirmOrder' => '確認訂單',
        'str_MessageTransferring' => '傳輸中...',
        'str_MessageCustomerServices' => '在订购过程中如有任何疑问请联系客户服务中心.',
        'str_ErrorPaymentFailed1' => '訂購沒有完成，因為在付款過程中發生錯誤.',
        'str_ErrorPaymentFailed2' => '如您希望詢問這個問題，請聯繫客服人員並引用下列訊息:',
        'str_MessageOrderConfirmation1' => '您的訂單號是:^0.',
        'str_MessageOrderConfirmation2' => '謝謝你的訂購，你的訂單已經接收',
        'str_MessageOrderConfirmation3' => '訂單確認的電子郵件不久後將會發送給您.',
        'str_MessageOrderCancellation1' => '您已取消訂購程序.',
        'str_MessageOrderCancellation2' => '請不要關閉此視窗並軟體自動返回應用軟體.',
        'str_MessagePayLaterConfirmation1' => '您選擇了稍後支付，參考號為^0',
        'str_MessagePayLaterConfirmation2' => '請關閉此窗口，並返回應用程式上傳您的作品.',
        'str_MessagePayLaterConfirmation3' => '一封確認電子郵件將發送給您，這可以告訴您如何完成訂購.',
        'str_MessagePayLaterCancellation1' => '您尚未完成訂單付款.',
        'str_MessagePayLaterCancellation' => '如果您有意訂購您的訂單作品，請在有效日期內{$formattedexpirydate}完成此交易',
        'str_MessagePaymentCancelled1' => '您已經取消了付款流程.',
        'str_MessagePaymentCancelled2' => '如需回到購物車並繼續您的訂購請按下面的按鈕.',
        'str_MessageQuantityChanged' => '你已經改變了一個或多個內容。本頁面現在將更新您的更改。',
        'str_MessageOptionsOrItemChanged' => '您嘗試更改產品的選擇以及高級的編輯，此頁面將會刷新您的更改。',
        'str_ErrorValueRequired' => '在提交表單之前，請填寫所有必填字段',
        'str_TooltipAddGiftcard' => '在此訂單使用您的禮品卡',
        'str_TooltipDeleteGiftcard' => '點擊,取消使用『禮品卡』餘額結賬',
        'str_TooltipReAddGiftcard' => '點擊,使用『禮品卡』餘額結賬',
        'str_OrderHide' => '隱藏',
        'str_OrderShow' => '顯示',
        'str_OrderSummaryHide' => '隱藏',
        'str_OrderSummaryShow' => '顯示',
        'str_LabelHeaderItem' => '項目',
        'str_LabelHeaderQuantity' => '數量',
        'str_LabelItemTotalShipping' => '項目小計（包括運費）',
        'str_OrderSectionChecboxes' => '選項',
        'str_OrderFooterLegend' => '更多選項',
        'str_LabelProductOptions' => '產品選項',
        'str_ErrorLicenseKeyInactive' => '授權碼不可用，請聯繫客戶服務中心',
        'str_LabelItemQuantity' => '項目數量 ^0',
        'str_LabelItemTotal' => '項目價格 ^0',
        'str_labelTotal' => '總計',
        'str_LabelTotalNotice' => '價格可能不含稅以及運費',
        'str_LabelSelectShippingMethod' => '請選擇您的送貨方式',
        'str_MessagePleaseWaitWhileWeConnectYou' => '請稍後，我們正在試圖連接您',
        'str_MessageThePaymentProvider' => '支持的支付方',
        'str_LabelOptionsAndExtras' => '選項和附加功能',
        'str_ButtonCancelOrder' => '取消訂購',
        'str_TitleLoadingInProgress' => '讀取處理中',
        'str_TitleExternalAssets' => '外部素材資產',
        'str_LabelShowOptions' => '顯示選項和附加功能',
        'str_LabelHideOptions' => '隱藏選項和附加功能',
        'str_LabelShowDetails' => '顯示詳情',
        'str_LabelHideDetails' => '隱藏詳情',
      ),
    ),
    'Computop' => 
    array (
      'vars' => 
      array (
        'str_ComputopSelectPaymentMethod' => '選擇一個付款方式',
        'str_ComputopSelectPaymentMethodError' => '請選擇一個付款方式',
        'str_ComputopCreditCard' => '信用卡',
        'str_ComputopBankTransfer' => '銀行交易',
        'str_ComputopPaypal' => '貝寶',
        'str_ComputopSelectABank' => '選擇一個銀行',
        'str_ComputopPromtPleaseSelectABank' => '請選擇一個銀行',
      ),
    ),
    'Customer' => 
    array (
      'vars' => 
      array (
        'str_MenuTitleOldOrders' => '查閱更早前的訂購紀錄',
        'str_TitleMyAccount' => '我的帳戶',
        'str_MenuTitlePayLaterOrders' => '訂單需要付款',
        'str_MenuTitleAccountDetails' => '個人檔案資料',
        'str_MenuTitleYourOrders' => '我的訂單',
        'str_MenuTitleOnlineProjects' => '我的作品',
        'str_MenuTitleChangePassword' => '變更密碼',
        'str_MenuTitleChangePreferences' => '變更偏好設定',
        'str_CreateNewOnlineProject' => '創建在線作品',
        'str_CreateNewOnlineProjectCon' => '創建在線支付作品',
        'str_CreateNewOnlineProjectPro' => '創建在線專業作品',
        'str_LabelNoActiveOrders' => '您無啟用的訂單',
        'str_LabelNoPreviousOrders' => '您無先前的訂單',
        'str_LabelNoOrders' => '您沒有訂單',
        'str_ButtonDuplicateProject' => '複製',
        'str_ButtonRenameProject' => '重命名',
        'str_ButtonDeleteProject' => '刪除',
        'str_ButtonContinueEditing' => '繼續編輯',
        'str_ButtonCompleteOrder' => '完成訂購',
        'str_MessageProjectNameAlreadyExists' => '這個作品名已經存在',
        'str_MessageDeleteProjectConfirmation' => '您確定您要刪除嗎^0',
        'str_TitlePleaseConfirm' => '請確認',
        'str_LabelOnlineProjects' => '在線作品',
        'str_LabelPageCount' => '頁',
        'str_LabelWelcomeTitle' => '您好 ^0,',
        'str_LabelWelcomeText' => 'T要進入您的帳戶請選取左邊選單的選項.',
        'str_LabelAccountDetailsUpdated' => '您的帳戶詳細資料已更新.',
        'str_LabelCurrentPassword' => '目前密碼',
        'str_LabelNewPassword' => '新密碼',
        'str_ErrorNoCurrentPassword' => '請輸入您目前的密碼.',
        'str_ErrorNoNewPassword' => '請輸入您新的密碼.',
        'str_ErrorNoNewPasswordConfirmation' => '請重新輸入你的新密碼',
        'str_ErrorPasswordNotSame' => 'n您的新密碼不能與舊密碼相同.',
        'str_ErrorPasswordsSame' => '您的新密碼不能和舊密碼相同.',
        'str_LabelPasswordUpdated' => '您的密碼已更新.',
        'str_LabelPreferencesUpdated' => '您的偏好設定已更新.',
        'str_MessageCustomerServices' => '您的訂購如有任何疑問，請聯繫客服人員.',
        'str_LabelSendToAFriend' => '發送給朋友',
        'str_LabelReorder' => '再次訂購',
        'str_MessageEmailSent' => '郵件寄送成功. 請檢查收件夾確認已送達.',
        'str_MessageSelectItemsToReorder' => '請選擇你想重新排列的項目：',
        'str_MessageSelectProductToReorder' => '要重新訂購，請選擇產品',
        'str_MessageSelectProductToShare' => '請選擇你要共享的產品',
        'str_MessagePleaseSelectAnOption' => '請選擇一個選項',
        'str_LabelUnshare' => '停止分享',
        'str_MessageSelectProductToUnshare' => '請選擇您想停止分享的產品',
        'str_MessageSelectItemsToUnshare' => '請選擇您想停止分享的項目:',
        'str_UnshareConfirmation' => '您確認想停止此項目的分享嗎?一旦停止分享，其他人將不會看到此項目.',
        'str_SuccessUnshare' => '成功停止分享',
        'str_TitleItem' => '項目',
        'str_LabelOrderNum' => '訂單號',
        'str_LabelOrderDate' => '訂購日期',
        'str_LabelSubTotalMultiLine' => '訂單總計',
        'str_LabelEnterCode' => '輸入代碼',
        'str_LabelRedeemGiftCard' => '兌換禮品卡',
        'str_MessagePasswordProtection' => '打開密碼保護然後創建一個密碼，讓您的項目只有知道密碼的人才能訪問。',
        'str_ErrorNoProjectName' => '作品名稱不能是空白',
        'str_LabelRenameProject' => '重命名作品',
        'str_TitleRenamingProject' => '重命名作品',
        'str_LabelDuplicateProject' => '複製作品',
        'str_TitleDuplicatingProject' => '複製作品',
        'str_LabelDeleteProject' => '刪除作品',
        'str_LabelEnterNewNameForTheProject' => '請為此作品輸入新的名稱',
        'str_LabelNoOnlineProject' => '您還沒有在線作品',
        'str_MessageCannotEditOnSmallScreen' => '您不能夠通過小屏幕設備編輯此作品',
        'str_TitleDeviceCompatibilityIssue' => '請使用大屏幕設備如：筆記本',
        'str_ErrorDeviceCompatibilityIssue' => '您不能使用小屏幕設備完成作品，請嘗試通過大屏幕設備如筆記本等登陸并完成',
        'str_LabelBrowserCompatibilityIssue' => '請更新您的瀏覽器',
        'str_ErrorBrowserCompatibilityIssue' => '您所使用的瀏覽器不能執行所請求的動作。請使用最新的Web瀏覽器',
        'str_ErrorProjectHasBeenDeleted' => '您所點擊的作品已被刪除',
        'str_ErrorOrderInProduction' => '您的操作不能被執行因為您的訂單已經在生產處理中',
        'str_LabelStatusInProgress' => '訂單處理中',
        'str_LabelStatusReadyToCollectAtStore' => '準備收集到店',
        'str_LabelStatusWaitingForPayment' => '等待付款',
        'str_LabelStatusWaitingForFiles' => '等待文件上傳',
        'str_LabelStatusInProduction' => '生產中',
        'str_LabelStatusShipped' => '送貨',
        'str_LabelStatusCancelled' => '取消',
        'str_LabelStatusCompleted' => '后加工',
        'str_LabelCreated' => '創建日期：',
      ),
    ),
    'AppAPI' => 
    array (
      'vars' => 
      array (
        'str_NoOwnerCode' => '沒有所有者代碼',
        'str_NoGroupCode' => '沒有群組代碼',
        'str_NoProjectName' => '沒有作品名稱',
        'str_NoGroupName' => '沒有名稱',
        'str_NoGroupAddress' => '沒有地址',
        'str_NoGroupPostCode' => '有沒郵遞區號',
        'str_NoGroupCountryCode' => '沒有國家代碼',
        'str_NoGroupContactName' => '沒有聯絡人姓名',
        'str_NoGroupEmailAddress' => '沒有電子郵件地址',
        'str_NoGroupTelephoneNumber' => '沒有電話號碼',
        'str_NoProductCode' => '沒有產品代碼',
        'str_NoProductHeight' => '沒有產品高度',
        'str_NoProductWidth' => '沒有產品寬度',
        'str_NoCoverCode' => '沒有封面代碼',
        'str_NoPaperCode' => '沒有頁面代碼',
        'str_NoPageCount' => '沒有頁面總數',
        'str_NoUploadRef' => '沒有上傳編號',
        'str_InvalidProductCode' => '無效的產品代碼',
        'str_InvalidCoverCode' => '無效的封面代碼',
        'str_InvalidPaperCode' => '無效的頁面代碼',
        'str_ProductCodeNotActive' => '產品沒有啟用',
        'str_InvalidCurrencyCode' => '無效的貨幣代碼',
        'str_InvalidTaxRate' => '無效的稅率',
        'str_InvalidPaymentMethodCode' => '無效的付款方式代碼',
        'str_NoOrder' => '無此編號的訂單',
        'str_NoUploadMethod' => '沒有上傳方式',
        'str_NoItemCount' => '沒有提供總計項目',
        'str_MissingParameter' => '遺失參數 \'^0\'',
        'str_MissingFile' => '遺失檔案 \'^0\'',
        'str_FileMoveError' => '無法移動檔案 \'^0\'',
        'str_FolderCreationError' => '無法建立檔案夾 \'^0\'',
        'str_LicenseKeyNotActive' => '授權碼沒有啟用',
        'str_InvalidAutoUpdatePath' => '無效的自動更新路徑',
      ),
    ),
    'AppProductionAPI' => 
    array (
      'vars' => 
      array (
        'str_MessageExternalWorkflowJobAborted' => '外部處理作品\'^0\'中止',
      ),
    ),
    'AdminExportEvent' => 
    array (
      'vars' => 
      array (
        'str_LabelEditEvent' => '編輯項目',
        'str_LabelEventCode' => '項目代碼',
        'str_LabelFilePath' => '文件路徑',
        'str_LabelFilenameFormat' => '文件名稱格式',
        'str_LabelExportFormat' => '輸出格式',
        'str_LabelLangOrder' => '訂單',
        'str_LabelLangDefault' => ' (預設)',
        'str_LabelFormat' => '輸出格式',
        'str_LabelFormatTXT' => 'TXT (tab 分隔)',
        'str_LabelFormatXML' => 'XML (可擴展標記)',
        'str_LabelPayment' => '包含付款資料',
        'str_LabelXmlBeautify' => '美化 XML',
        'str_ErrorEmptyFilePath' => '文件路徑不能是空白. \\n請輸入有效文件路徑.',
        'str_ErrorSystemCharacter' => '此字段不能包含特殊字符.',
        'str_LabelTask1' => '任務 1',
        'str_LabelTask2' => '任務 2',
      ),
    ),
    'AdminSitesSitesAdmin' => 
    array (
      'vars' => 
      array (
        'str_TitleSitesAdministration' => '網站管理',
        'str_TitleSiteAdministrationAdd' => '增加商店',
        'str_TitleSiteAdministrationEdit' => '編輯網站資訊',
        'str_TitleSiteAdministrationSiteAdd' => '增加網站',
        'str_LabelSiteCode' => '網站代碼',
        'str_LabelSiteName' => '網站名稱',
        'str_LabelSiteURL' => '網站網址',
        'str_LabelStoreGroup' => '商店群組',
        'str_LabelSiteType' => '網站類型',
        'str_LabelSiteOnline' => '在線',
        'str_LabelProductCode' => '產品編號',
        'str_LabelProductName' => '產品名稱',
        'str_LabelSmtpName' => 'SMTP收件人姓名',
        'str_LabelSmtpAddress' => 'SMTP電子郵件地址',
        'str_LabelAcceptAllProducts' => '接受所有產品',
        'str_ConfirmationDeleteStores' => '你確定要刪除選定網站?',
        'str_ErrorSiteExists' => '此代碼的網站已經存在.',
        'str_WarningNotAllSitesDeleted' => '並非所有的選定地點可以刪除.',
        'str_MessageSiteDeleted' => '選定網站已被刪除.',
        'str_TitleSectionSiteContact' => '網站聯繫',
        'str_TitleSectionAddress' => '網站地址',
        'str_TitleSectionStoreSettings' => '商店設置',
        'str_TitleSectionProductionSettings' => '產品設置',
        'str_SiteTypeProductionOnly' => '僅適用於生產現場',
        'str_SiteTypeProductionAndStore' => '生產現場和商店',
        'str_SiteTypeStore' => '商店',
        'str_SiteTypeDistributionCentre' => '配送中心',
        'str_ErrorNoSiteGroups' => '此區段是必需的，如果列表中沒有可用的選項，請建立一個商店群組.',
        'str_ErrorUsedInUsers' => '這網站 ^0 不能被刪除，因為分配給它的用戶.',
        'str_ErrorUsedInSites' => '這網站 ^0 不能被刪除，因為分配給它的網站.',
        'str_ErrorUsedInOrders' => '這網站 ^0 不能被刪除，因為分配給它的訂單.',
        'str_ErrorDeleteProductionSites' => '生產現場 ^0 不能被刪除.',
        'str_ErrorOnChangeProductionStoreUsed' => '有分配給它的商店用戶，不能改變這種類型的網站.',
        'str_ErrorOnChangeStoreUsed' => '有分配給它的商店用戶，不能改變這種類型的網站.',
        'str_ErrorOnChangeDistrCentreUsed' => '有配送中心分配給它的用戶，不能改變這種類型的網站.',
        'str_ErrorDistCentreAssignedToStore' => '網站類型不能改變，因為這個網站是一個商店的配送中心.',
      ),
    ),
    'AdminSitesSiteGroups' => 
    array (
      'vars' => 
      array (
        'str_DeleteConfirmation' => '確認\\n刪除站點群組\'^0\'嗎?',
        'str_TitleNewStoreGroup' => '新的商店群組',
        'str_TitleEditStoreGroup' => '編輯商店群組',
        'str_LabelStoreGroup' => '商店群組',
        'str_MessageStoreGroupsDeleted' => '選擇商店群組已被刪除.',
        'str_ErrorStoreGroupExists' => '商店群組代碼已經存在.',
        'str_ErrorUsedInShippingRate' => '商店群組不能被刪除，因為它已經使用在貨運稅率.',
        'str_ErrorUsedInSite' => '商店群組不能被刪除，因為它已經使用在網站.',
      ),
    ),
    'AdminSitesCompanies' => 
    array (
      'vars' => 
      array (
        'str_TitleEditCompany' => '編輯公司',
        'str_TitleSectionAddress' => '網站地址',
      ),
    ),
    'AdminSitesOrderRouting' => 
    array (
      'vars' => 
      array (
        'str_TitleSitesOrderRouting' => '訂購路由',
        'str_LabelRule' => '規則',
        'str_LabelCondition' => '條件',
        'str_LabelValue' => '價值',
        'str_LabelPriority' => '優先順序',
        'str_LabelProductCode' => '產品',
        'str_LabelBrandCode' => '品牌',
        'str_LabelLicenseKeyCode' => '授權碼',
        'str_LabelShippingCountryCode' => '送貨國家',
        'str_LabelVoucherSiteCode' => '發送至折價券的網站',
        'str_LabelIs' => '是',
        'str_LabelIsNot' => '否',
        'str_ConfirmationDeleteRule' => '你確定要刪除選定的規則?',
        'str_MessageRuleDeleted' => '選擇規則已被刪除.',
        'str_TitleSitesOrderAdd' => '增加路由規則',
        'str_TitleSitesOrderEdit' => '編輯路由規則',
        'str_MessageRulesDeleted' => '選擇規則已被刪除.',
        'str_WarningPriorityNotUpdated' => '路由規則的優先順序不能改變，這是由於一個數據庫錯誤.',
        'str_WarningRuleNotUpdated' => '路由規則是不能夠被保存，這是由於一個數據庫錯誤.',
        'str_AltLabelPriorityDown' => '下移',
        'str_AltLabelPriorityUp' => '上移',
        'str_AltLabelPriorityLast' => '移至最後',
        'str_AltLabelPriorityFirst' => '移至第一',
        'str_WarningRuleExists' => '一個符合這些條件的路由規則已經存在，請確保您的規則條件是正確的.',
      ),
    ),
    'AdminComponentCategories' => 
    array (
      'vars' => 
      array (
        'str_DeleteConfirmation' => '確認.\\n刪除組件分類\'^0\'嗎?',
        'str_LabelNoPricing' => '沒有定價',
        'str_LabelPerOrder' => '每個訂單',
        'str_LabelPerLine' => '每行',
        'str_LabelPerQty' => '每個數量',
        'str_LabelPerPageQty' => '每頁及數量',
        'str_LabelPerSideQty' => '每部分和數量',
        'str_LabelPerCharacter' => '每個字符',
        'str_LabelPerProductCmpQty' => '按產品以及組件總數量計價',
        'str_LabelPerPageProductCmpQty' => '按產品、組件以及頁數總量計價',
        'str_TitleNewComponentCategory' => '新的組件類別',
        'str_ErrorComponentCategoryExists' => '一個組件類別的代碼已經存在.',
        'str_TitleEditComponenetCategory' => '編輯組件類別',
        'str_MessageComponentCategoriesDeleted' => '選定的組件目錄已被刪除.',
        'str_LabelDecimalPlaces' => '小數位數',
        'str_LabelComponentCategory' => '組件類別',
        'str_ErrorComponentsAttached' => '類別不能刪除，因為它已分配組件.',
        'str_ErrorCategoryUsedInOrder' => '類別不能被刪除，因為它已經使用在訂單.',
        'str_ErrorCategoryHasPriceList' => '該分類不能被刪除，因為它已經有價格表分配使用。',
      ),
    ),
    'AdminComponents' => 
    array (
      'vars' => 
      array (
        'str_LabelPriceList' => '價目表',
        'str_LabelCustomPrice' => '自定價格',
        'str_MessageComponentDeleted' => '選定的組件已被刪除.',
      ),
    ),
    'CollectFromStore' => 
    array (
      'vars' => 
      array (
        'str_TitleCollectFromStore' => '從商店收集',
        'str_ShippedToDistributionCentre' => '運到配送中心',
        'str_ReceivedAtDistributionCentre' => '送到配送中心',
        'str_ShippedToStoreFromDistributionCentre' => '從配送中心運到商店',
        'str_ShippedToStoreDirectly' => '直接運到商店',
        'str_ReceivedAtStore' => '送到在商店',
        'str_CollectedByCustomer' => '收集客戶',
        'str_MarkBooked' => '標記為已預訂',
        'str_OrderDetails' => '訂單明細',
        'str_OrderInformation' => '訂購信息',
        'str_BillingInformation' => '帳單信息',
        'str_LabelProductName' => '產品名稱',
        'str_Qty' => '數量',
        'str_Address' => '地址',
        'str_ContactFirstName' => '聯繫人名字',
        'str_ContactLastName' => '聯繫人姓',
        'str_PaymentConfirmed' => '付款確認',
        'str_PaymentDate' => '付款日期',
        'str_Date' => '日期',
        'str_ReceivedConfirmation' => '你確定要標記選定的訂單為已收到?',
        'str_NotReceivedConfirmation' => '你確定要標記為選定的訂單為未收到?',
        'str_CollectedConfirmation' => '你確定要標記選定的訂單為已收集?',
        'str_NotCollectedConfirmation' => '你確定要標記選定的訂單為未收集?',
        'str_NotReceived' => '未收到',
        'str_Received' => '已收到',
        'str_Collected' => '收集客戶',
        'str_ShippedToStore' => '運到商店',
        'str_ConfirmPayment' => '確認付款',
        'str_CollectedNotPaidConfirmation' => '並非所有的訂單已支付，你確定要標記為收集訂單?',
        'str_NotCollected' => '未收集',
        'str_DateCollected' => '日期收集',
        'str_PaymentInfo' => '付款信息',
        'str_Paid' => '已付款',
        'str_MarkAsPaid' => '標記為已付款',
        'str_MarkAsNotPaid' => '標記為未付款',
        'str_MarkReceived' => '標記為已收到',
        'str_MarkNotReceived' => '標記為未收到',
        'str_ShippedConfirmation' => '你確定要標記選定的訂單，為運送至商店?',
        'str_NotShippedConfirmation' => '你確定要標記選定的訂單，為非運送至商店?',
        'str_MarkAsShipped' => '標記為已運到商店',
        'str_MarkAsNotShipped' => '標記為未運到商店',
        'str_Shipped' => '運送',
        'str_Store' => '商店',
        'str_DistributionCentre' => '配送中心',
        'str_MarkCollected' => '標記為已收集',
        'str_ShowDetailedStoreInformation' => '顯示詳細商店信息',
        'str_MarkNotCollected' => '標記為未收集',
        'str_ShippingReference' => '出貨編號',
      ),
    ),
    'Components' => 
    array (
      'vars' => 
      array (
        'str_DeleteConfirmation' => '確認\\n刪除組件\'^0\'嗎?',
        'str_SectionWindowTitleAddComponents' => '增加新的 \'^0\' 組件',
        'str_SectionWindowTitleEditComponents' => '編輯 \'^0\' 組件',
        'str_LabelMinPageCount' => '最少頁面計算',
        'str_LabelMaxPageCount' => '最多頁面計算',
        'str_LabelCheckedByDefault' => '預設選中',
        'str_MessagePreviewImageDimensions' => '預覽圖像的尺寸 ^w x ^h.\\n建議預覽圖像的圖像最大尺寸為620x100像素.',
        'str_ErrorComponentExists' => '此代碼的組件已經存在.',
        'str_LabelDefaultValues' => '預設值',
        'str_ErrorComponentAttachedToAProduct' => '組件可能不會被刪除，因為它們是連接到一個產品.',
        'str_LabelOrderFooterUsesProdQuantity' => '訂訂單較笨配合產品數量',
        'str_LabelOrderFooterTaxLevel' => '訂單腳本配合稅率登記1',
        'str_LabelStoreComponentWhenNotSelected' => '商店組件未選擇',
      ),
    ),
    'ComponentsPricing' => 
    array (
      'vars' => 
      array (
        'str_TitleComponentPricing' => '組件 ^0 的預設定價...',
        'str_TitleNewPricing' => '組件 ^0 的新的定價...',
        'str_TitleEditPricing' => '編輯組件 ^0 的定價...',
        'str_MessagePriceListsDeleted' => '選定的價目表已被刪除.',
        'str_ErrorPriceListUsedInPricing' => '價目表不能刪除，因為它已被分配到一個組件.',
        'str_DeleteConfirmation' => '確認\\n刪除價格列表 \'^0\'嗎?',
        'str_DeleteDefaultConfirmation' => '確認.\\n刪除預設的定價?',
      ),
    ),
    'ComponentDefaultPrices' => 
    array (
      'vars' => 
      array (
        'str_MessageDefaultPriceDeleted' => '選定的預訂價格已被刪除.',
      ),
    ),
    'AdminScheduledTasks' => 
    array (
      'vars' => 
      array (
        'str_TitleEditTask' => '編輯任務',
        'str_TitleAddTask' => '新的任務增加',
        'str_TaskCode' => '任務代碼',
        'str_TaskName' => '任務名稱',
        'str_TaskLastRunTime' => '上次運行時間',
        'str_TaskExecutionStatus' => '執行結果',
        'str_TaskNextRunTime' => '下次運行時間',
        'str_TaskInternal' => '內部',
        'str_DeleteConfirmation' => '確認刪除任務計劃 \'^0\'嗎?',
        'str_MessageTasksDeleted' => '選擇的任務已被刪除.',
        'str_ErrorDeleteInternalTask' => '以下內部任務無法刪除: \'^0\'.',
        'str_ErrorDuplicateTaskCode' => '任務的代碼已經存在.',
        'str_LabelSchedulerActive' => '調度活動',
        'str_LabelShedulerUpdated' => '調度設置已更新.',
        'str_LabelRunNow' => '重置下次運行時間',
        'str_TaskStatusCompleted' => '已完成',
        'str_LabelIntervalType' => '間隔類型',
        'str_LabelIntervalValue' => '區間值',
        'str_LabelMaxRunCount' => '最大運行計數',
        'str_LabelDeleteEventsAfterDays' => '刪除了幾天的事件',
        'str_LabelNumberOfMinutes' => '分鐘數',
        'str_LabelTimeOfTheDay' => '一天的時間',
        'str_LabelNumberOfDays' => '天數',
        'str_LabelLastRun' => '最後一次運行:',
        'str_LabelScript' => '腳本',
      ),
    ),
    'AdminScheduledEvents' => 
    array (
      'vars' => 
      array (
        'str_EventLastRunTime' => '上次運行時間',
        'str_EventExecutionStatus' => '執行結果',
        'str_EventNextRunTime' => '下次運行時間',
        'str_DeleteConfirmation' => '刪除選定的事件?',
        'str_MessageEventsDeleted' => '選定的事件已被刪除.',
        'str_LabelRunNow' => '立即執行事件',
        'str_EventRunCount' => '運行計數',
        'str_EventMaxRunCount' => '最大計數',
        'str_LabelPriority' => '優先順序',
        'str_LabelTaskCode' => '任務代碼',
        'str_TitleEditEvent' => '編輯事件',
        'str_EventStatusCompleted' => '已完成',
        'str_LabelNormal' => '正常',
        'str_LabelHigh' => '高',
        'str_LabelActiveEvents' => '活動的任務',
        'str_LabelFailedEvents' => '有問題的任務',
        'str_LabelCompletedEvents' => '已完成的任務',
      ),
    ),
    'AdminMetadataKeywords' => 
    array (
      'vars' => 
      array (
        'str_TitleEditKeyword' => '編輯關鍵字',
        'str_TitleNewKeyword' => '新的關鍵字',
        'str_ExtJsErrorNoDescription' => '請輸入描述.',
        'str_ErrorDuplicateCode' => '此代碼中的關鍵字已經存在',
        'str_WarningMaxLengthChanged' => '此元數據字段的最大長度發生改變，你要繼續嗎?',
        'str_ErrorMaxLengthMustBeGreaterThanZero' => '此類型的的關鍵字最大長度必須大於 0',
        'str_LabelUppercaseValue' => '大寫數值',
        'str_LabelValueRequired' => '需要的數值',
        'str_LabelImagePath' => '圖片路徑',
        'str_LabelEditItems' => '編輯內容',
        'str_LabelNewItem' => '新建內容',
      ),
    ),
    'AdminMetadataKeywordsGroups' => 
    array (
      'vars' => 
      array (
        'str_TitleEditKeywordGroup' => '編輯關鍵字組',
        'str_TitleNewKeywordGroup' => '新的關鍵字組',
        'str_LabelProductCode' => '產品編號',
        'str_LabelProductName' => '產品名稱',
        'str_LabelKeywordCode' => '關鍵字代碼',
        'str_LabelKeywordType' => '關鍵字類型',
        'str_ErrorNoKeywords' => '您沒有選擇任何關鍵字.<br><br>請所有關鍵字拖放到關鍵詞項目中.',
        'str_ErrorNoProducts' => '請選擇產品.',
        'str_LabelChecked' => '檢查',
        'str_LabelNotChecked' => '不檢查',
        'str_LabelNoDefault' => '沒有默認值',
      ),
    ),
    'Share' => 
    array (
      'vars' => 
      array (
        'str_LabelShareNow' => '馬上分享',
        'str_LabelPromoMessageBuy' => '這裡是一個獨一無二大作品！您馬上訂購一個吧！',
        'str_LabelPromoMessageShare' => '這是您的作品，現在您可以再次訂購或者分享給您的朋友',
        'str_LabelPromoMessageProject' => '這是您的作品',
        'str_MessageEmailSent' => '郵件寄送成功. 請檢查收件夾確認已送達.',
        'str_LabelSendToAFriend' => '發送給朋友',
        'str_MessagePreviewExpire' => '這個預覽已經過期或者訂單已經不可用，請聯繫我們獲取更多的信息',
        'str_MessagePreviewEnjoy' => '請盡情分享翻頁體驗',
        'str_MessagePreviewInstallFlash' => 'install Adobe Flash Player',
        'str_LabelOrderBookNow' => '現在訂購',
        'str_MessagePreviewOurSoftware' => '我們的服務使您可以設計、訂購和共享寫真書.',
        'str_MessagePreviewDownloadMac' => '下載 Mac版本',
        'str_MessagePreviewDownloadWindows' => '下載 Windows版',
        'str_LabelDownload' => '下載',
        'str_LabelItemDoesNotExist' => '項目不存在',
        'str_LabelItemDoesNotExistMessage' => '您需要查看該項目不存在.',
        'str_LabelPreviewNotFound' => '不能找到預覽',
        'str_LabelPreviewNotFoundMessage' => '您想查看的預覽不能找到.',
        'str_LabelPreviewNotAvailable' => '無法預覽',
        'str_LabelPreviewNotAvailableMessage' => '你想查看的預覽當前不可用',
        'str_MessagePreviewLoadingInProgress' => '預覽正在讀取中..',
      ),
    ),
    'AdminTaopixOnlineServers' => 
    array (
      'vars' => 
      array (
        'str_TitleAddImageServer' => '增加圖片伺服器',
        'str_TitleEditImageServer' => '編輯圖片伺服器',
        'str_MessageDeleteImageServer' => '您確定您要刪除選定的圖像​​服務器及其卷嗎？',
        'str_LabelServerURL' => '伺服器網址',
        'str_LabelLastConnection' => '最後一次鏈接',
        'str_LabelLastSuccess' => '最後成功',
        'str_LabelPing' => '測試',
        'str_WarningConnectToServer' => '不能連接到圖像服務器，請檢查服務器URL網址',
        'str_WarningUnableToActivateServer' => '無法激活圖片伺服器',
        'str_WarningUnableToDeactivateServer' => '無法停用圖片伺服器',
        'str_WarningUnableToUpdateServer' => '無法更新圖片服務器的詳情，請檢查服務器的URL地址',
        'str_WarningUnableToAddServer' => '無法添加圖片服務器，請檢查服務器的URL地址',
        'str_WarningUnableToDeleteServer' => '無法刪除圖片伺服器',
      ),
    ),
    'AdminTaopixOnlineVolumes' => 
    array (
      'vars' => 
      array (
        'str_TitleEditVolume' => '編輯驅動器',
        'str_TitleAddVolume' => '增加驅動器',
        'str_LabelLastUpdated' => '最後更新',
        'str_LabelRoot' => '根',
        'str_LabelHeadroom' => '清空',
        'str_LabelFree' => '空白',
        'str_LabelSize' => '尺寸',
        'str_LabelVolumeType' => '磁盤類型',
        'str_LabelStorageName' => '磁盤名稱',
        'str_LabelAccessKey' => '訪問密匙',
        'str_LabelSecret' => '保密',
        'str_LabelStorageClass' => '磁盤類',
        'str_LabelStorageClassStandard' => '標準',
        'str_LabelStorageClassReduced' => '減少冗餘',
        'str_LabelUploadURL' => '上傳網址',
        'str_LabelDownloadURL' => '下載網址',
        'str_LabelAssetType' => '素材類型',
        'str_LabelGlobalAssets' => '全局素材',
        'str_LabelProductCollectionAssets' => '產品集合的素材',
        'str_LabelUserAssets' => '用戶素材',
        'str_LabelNonSharedDisk' => '非共享磁盤',
        'str_LabelSharedDisk' => '共享磁盤',
        'str_LabelAmazonS3Bucket' => '亞馬孫S3磁盤',
        'str_MessageDeleteVolumes' => '你確定要刪除此驅動器嗎？',
        'str_WarningUnableToActivateVolume' => '無法啓動驅動器',
        'str_WarningUnableToDeactivateVolume' => '無法停用驅動器',
        'str_WarningUnableToUpdateVolume' => '不能更新驅動器信息',
        'str_WarningUnableToAddVolume' => '不能添加驅動器',
        'str_WarningUnableToDeleteVolume' => '無法刪除驅動器。',
        'str_ErrorNoAssetTypeSelected' => '沒有選擇的素材類型',
        'str_WarningUnableToUploadAssetToStorage' => '無法上傳到在線磁盤',
        'str_WarningUnableToDownloadAssetFromStorage' => '無法下載到來自在線磁盤',
        'str_WarningUnableToDeleteAssetFromStorage' => '無法刪除來自在線磁盤',
      ),
    ),
    'AdminTaopixOnlineProductURLS' => 
    array (
      'vars' => 
      array (
        'str_TitleTaopixOnlineProductURL' => 'TAOPIX在線版產品網址',
        'str_LabelCollectionCode' => '產品集合代碼',
        'str_LabelLayoutCode' => '模版代碼',
        'str_LabelLayoutName' => '模板名字',
        'str_LabelOnlineURL' => '在線版網址',
        'str_LabelURL' => '網址',
        'str_LabelDecryptedData' => '解密數據',
        'str_LabelDecryptURL' => '解密網址',
        'str_ButtonDecrypt' => '解密',
        'str_LabelProductCollectionCode' => '產品集代碼',
        'str_LabelProductLayoutCode' => '產品佈局代碼',
        'str_LabelLicenseKeyCode' => '授權碼代碼',
        'str_LabelLicenseKeyGroupDataStatus' => '授權碼群組數據狀態',
        'str_LabelLicenseKeyGroupData' => '授權碼群組數據',
        'str_LabelEncrypted' => '加密',
        'str_LabelParameter' => '參數',
        'str_LabelShowActiveOnly' => '只顯示啟用的信息',
        'str_LabelShowInActiveOnly' => '只顯示不啟用的信息',
        'str_ErrorDecryptURL' => '無法解密產品網址',
        'str_LabelNotPriced' => '沒有價格',
        'str_LabelFilter' => '過濾',
      ),
    ),
    'BrowserSupport' => 
    array (
      'vars' => 
      array (
        'str_labelWeSupport' => '我們支持最後的版本是',
        'str_titleBrowserNotSupported' => '不幸的是，您的瀏覽器不支持。',
        'str_titleRecommendBrowsers' => '瀏覽我們網站時，我們建議您使用一下的瀏覽器',
        'str_labelBrowserChrome' => '谷歌瀏覽器',
        'str_labelBrowserInternetExplorer' => 'ie瀏覽器',
        'str_labelBrowserSafari' => 'safari瀏覽器',
        'str_labelBrowserFirefox' => '火狐瀏覽器',
        'str_LabelDownload' => '下載',
      ),
    ),
    'CommunicationFailed' => 
    array (
      'vars' => 
      array (
        'str_titleCommunicationFailed' => '不能鏈接伺服器',
        'str_MessageCommunicationFailed' => '連接到服務器出現問題。有關更多信息，請聯繫客戶支持',
      ),
    ),
    'AdminErrorNotification' => 
    array (
      'vars' => 
      array (
        'str_LabelErrorTime' => '時間',
        'str_LabelErrorURL' => '網址',
        'str_LabelErrorCode' => '錯誤代碼',
        'str_LabelErrorMessage' => '錯誤信息',
        'str_TitleCommunicationFailed' => '通訊失敗',
        'str_WarningCommunicationFailed' => '鏈接伺服器出現問題',
      ),
    ),
    'ProductionAutomation' => 
    array (
      'vars' => 
      array (
        'str_ErrorNotTheSameOrder' => '此項目必須在同一個訂單',
        'str_ErrorDuplicateItem' => '該項目只能出現一次在列表中 \'^0\'。',
        'str_ErrorItemsMissing' => '不在列表中找到所有的項目\'^0\'',
        'str_ErrorIDListInvalid' => '項目列表 \'^0\' 無效.',
        'str_ErrorActionBlocked' => '動作\'^0\'已經被封鎖為的操作。',
        'str_ErrorActionNotAllowed' => '動作\'^0\'是不允許的。',
        'str_ErrorActionNotAllowedInactiveOrder' => '動作^0\'不允許在不激活的訂單中操作',
        'str_ErrorActionNotAllowedTempOrder' => '動作^0\'不允許在臨時的訂單中操作',
        'str_ErrorActionNotAllowedTooLow' => '動作^0\'不允許在設置狀態過於低',
        'str_ErrorActionNotAllowedOnHigher' => '動作^0\'不允許在狀態過於高進行操作',
        'str_ErrorActionNotAllowedRendered' => '動作^0\'不允許在輔助工具下操作',
        'str_ErrorActionNotAllowedRAW' => '動作^0\'不允許在分層作品的訂單上操作',
      ),
    ),
  ),
  'vars' => 
  array (
    'str_LangVersion' => '5.0.0.0',
    'kGUIAdminAccordionWidth' => '190',
    'str_LanguageCode' => 'zh_tw',
    'str_LanguageName' => '繁體中文',
    'str_LanguageList' => 'en 英文,cs 捷克文,da 丹麥文,de 德文,es 西班牙文,fi 芬蘭文,fr 法文,hu 匈牙利文,it 意大利文,ja 日文,ko 韓文,nl 荷蘭文,no 挪威文,pl 波蘭文,pt 葡萄牙文,ru 俄羅斯文,sl 斯諾文尼亞文,sv 瑞典文,th 泰文,zh_cn 簡體中文,zh_tw 繁體中文',
    'str_country_cn' => '中國',
    'str_country_hk' => '香港',
    'str_country_in' => '印度',
    'str_country_jp' => '日本',
    'str_country_kr' => '韓國',
    'str_country_mo' => '澳門',
    'str_country_my' => '馬來西亞',
    'str_country_ph' => '菲律賓',
    'str_country_sg' => '新加坡',
    'str_country_tw' => '台灣',
    'str_country_th' => '泰國',
    'str_country_us' => '美國',
    'str_ButtonOk' => '確定',
    'str_ButtonYes' => '是',
    'str_ButtonNo' => '否',
    'str_ButtonNew' => '新增',
    'str_ButtonEdit' => '編輯',
    'str_ButtonDelete' => '刪除',
    'str_ButtonCancel' => '取消',
    'str_ButtonSave' => '儲存',
    'str_ButtonAdd' => '增加',
    'str_ButtonUpdate' => '更新',
    'str_ButtonBack' => '上一步',
    'str_ButtonClose' => '關閉',
    'str_ButtonContinue' => '繼續',
    'str_ButtonDoNotContinue' => '不繼續',
    'str_ButtonChange' => '更改',
    'str_ButtonCreate' => '建立',
    'str_ButtonReset' => '重置',
    'str_ButtonExport' => '輸出',
    'str_ButtonPricing' => '定價',
    'str_ButtonCopy' => '複製',
    'str_ButtonView' => '檢視',
    'str_ButtonPreview' => '預覽',
    'str_ButtonDetails' => '顯示詳細訊息',
    'str_ButtonSelectStore' => '選擇商店',
    'str_ButtonSearch' => '搜尋',
    'str_ButtonUpdatePreviewImage' => '更新預覽圖片',
    'str_ButtonRemovePreviewImage' => '移除預覽圖片',
    'str_ButtonResetPreviewImage' => '重新設定預覽圖片',
    'str_ButtonSignIn' => '登入',
    'str_ButtonDone' => '完成',
    'str_LabelWelcome' => '歡迎',
    'str_LabelNewAccount' => '新帳戶',
    'str_LabelYes' => '是的',
    'str_LabelNo' => '不',
    'str_LabelCategory' => '類別',
    'str_LabelCode' => '代碼',
    'str_LabelType' => '類型',
    'str_LabelDescription' => '說明',
    'str_LabelValue' => '價值',
    'str_LabelMaxLength' => '最大長度',
    'str_LabelWeight1' => '重量',
    'str_LabelHeight' => '高度',
    'str_LabelName' => '名稱',
    'str_LabelVersion' => '版本',
    'str_LabelFileName' => '檔案名稱',
    'str_LabelActive' => '啟用',
    'str_LabelInactive' => '無效',
    'str_LabelStatus' => '狀態',
    'str_LabelMakeInactive' => '停用',
    'str_LabelMakeActive' => '啟用',
    'str_LabelLoginInformation' => '登入訊息',
    'str_LabelUserName' => '用戶名',
    'str_LabelRetypeUserName' => '重新鍵入用戶名',
    'str_LabelPassword' => '密碼',
    'str_LabelRetypePassword' => '重新輸入密碼',
    'str_LabelContactInformation' => '連繫訊息',
    'str_LabelCustomerSupport' => '支援',
    'str_LabelCustomerSupportLine' => '客服支援熱線',
    'str_LabelCustomerSupportEmail' => '客戶支援電子郵件',
    'str_LabelFirstName' => '名字',
    'str_LabelLastName' => '姓氏',
    'str_LabelCompanyName' => '公司名稱',
    'str_LabelHouseNumber' => '門牌號碼',
    'str_LabelAddressLine1' => '地址 1',
    'str_LabelAddressLine2' => '地址 2',
    'str_LabelAddressLine3' => '地址 3',
    'str_LabelAddressLine4' => '地址 4',
    'str_TaxNumber' => '稅務號碼',
    'str_TaxNumberType' => '稅務號碼類型',
    'str_LabelCustomerTaxNumberTypePersonal' => '個人',
    'str_LabelCustomerTaxNumberTypeCorporate' => '公司',
    'str_LabelTownCity' => '城市',
    'str_LabelCounty' => '縣',
    'str_LabelState' => '州別',
    'str_LabelProvince' => '省份',
    'str_LabelRegion' => '地區',
    'str_LabelPostCode' => '郵遞區號',
    'str_LabelPostalCode' => '郵政編碼',
    'str_LabelZIPCode' => '郵遞區號',
    'str_LabelCountry' => '國別',
    'str_LabelTelephoneNumber' => '電話號碼',
    'str_LabelEmailAddress' => '電子郵件',
    'str_LabelRetypeEmailAddress' => '重新輸入電子郵件',
    'str_LabelCommunicationPreferences' => '通訊偏好設定',
    'str_LabelMarketingSubscribe' => '訂閱: 請寄給我最新資訊與促銷訊息',
    'str_LabelMarketingSubscribed' => '已訂閱: 請寄給我最新資訊與促銷訊息',
    'str_LabelMarketingUnsubscribe' => '未訂閱: 請勿寄給我最新資訊與促銷訊息',
    'str_LabelMarketingUnsubscribed' => '未訂閱: 請勿寄給我最新資訊與促銷訊息',
    'str_LabelShippingAddress' => '送貨地址',
    'str_LabelBillingAddress' => '帳單地址',
    'str_LabelShippingMethod' => '送貨方式',
    'str_LabelPaymentMethod' => '付款方式',
    'str_LabelQuantity' => '數量',
    'str_LabelOrderDate' => '訂購日期',
    'str_LabelProjects' => '作品',
    'str_LabelPrintedDate' => '輸出日期',
    'str_LabelShippedDate' => '交貨日期',
    'str_LabelOrderNumber' => '訂單編號r',
    'str_LabelOrderTotal' => '訂單總價',
    'str_LabelAdministrator' => '管理員',
    'str_LabelCost' => '成本',
    'str_LabelShippingWeight' => '運送重量',
    'str_LabelDefault' => '預設',
    'str_LabelCountries' => '國家',
    'str_LabelLanguageName' => '語言名稱',
    'str_LabelAdditionalInformation' => '附加訊息',
    'str_LabelInformation' => '訊息',
    'str_LabelDetails' => '詳細資料',
    'str_LabelNotAvailable' => '無效的',
    'str_LabelInvalidVoucher' => '代碼無效',
    'str_LabelVoucherNoLonger' => '優惠劵已失效',
    'str_LabelProduct' => '產品',
    'str_LabelLicenseKey' => '授權碼',
    'str_LabelStartDate' => '開始日期',
    'str_LabelEndDate' => '截止日期',
    'str_LabelAll' => '全部',
    'str_LabelUser' => '使用者',
    'str_LabelCustomer' => '客戶',
    'str_LabelAccountCode' => '帳戶代碼',
    'str_LabelAccountBalance' => '已使用帳戶額度',
    'str_LabelAccount' => '帳戶',
    'str_LabelCreditLimit' => '信用額度',
    'str_LabelGiftCardBalance' => '禮品卡金額',
    'str_LabelGiftCardRedeemText' => '要兌換你的禮品卡，請輸入代碼:',
    'str_LabelGiftCardRemaining' => '剩餘禮品卡金額',
    'str_LabelRedeemedBy' => '使用',
    'str_LabelRedeemedDate' => '使用日期',
    'str_LabelSymbol' => '符號',
    'str_LabelWidth' => '寬度',
    'str_LabelPosition' => '位置',
    'str_LabelNone' => '忽略',
    'str_LabelFront' => '前',
    'str_LabelBack' => '後',
    'str_LabelModifyPassword' => '更改密碼',
    'str_LabelSet' => '設置',
    'str_LabelRedeem' => '兌現',
    'str_LabelAdd' => '增加',
    'str_LabelRemove' => '移除',
    'str_LabelChange' => '更改',
    'str_LabelDuplicate' => '複製',
    'str_LabelPreviewImage' => '預視圖像',
    'str_LabelClear' => '清除',
    'str_LabelLogOut' => '登出',
    'str_LabelSignOut' => '登出',
    'str_LabelModifyShippingAddress' => '修改送貨地',
    'str_LabelModifyBillingAddress' => '修改帳單地址',
    'str_LabelModifyShippingContactDetails' => '修改送貨地址細節',
    'str_LabelClientPriceDescription' => '價格說明',
    'str_LabelLineSubtract' => '扣除',
    'str_LabelCover' => '封面',
    'str_LabelPaper' => '紙張',
    'str_LabelVoucherCode' => '折價券代碼',
    'str_LabelGiftCardCode' => '禮品卡',
    'str_LabelOrderSummary' => '訂單描述',
    'str_LabelOrderSummaryPayment' => '摘要及付款',
    'str_LabelCartSummary' => '購物車摘要',
    'str_LabelErrorCode' => '錯誤代碼',
    'str_LabelErrorMessage' => '錯誤訊息',
    'str_LabelTransactionID' => '交易身分',
    'str_LabelMinimumValue' => '最小值',
    'str_LabelMaximumValue' => '最大值',
    'str_LabelIncludeDiscount' => '包含折扣',
    'str_LabelProjectName' => '作品名稱',
    'str_LabelLanguage' => '語言',
    'str_LabelUserEmailDestination' => '郵件通知至',
    'str_LabelShippingBCCBillingAddress' => '送貨地址，密件副本至帳單地址',
    'str_LabelBillingBCCShippingAddress' => '帳單地址，密件副本至送貨地址',
    'str_LabelServer' => '伺服器',
    'str_LabelPayLaterRef' => '延遲付款編號',
    'str_LabelPayNow' => '現在付款',
    'str_LabelExpiryDate' => '到期日',
    'str_LabelPaymentMethods' => '付費方式',
    'str_LabelUseDefaultPaymentMethods' => '使用預設付款方式',
    'str_LabelPaymentIntegrations' => '付款整合',
    'str_LabelTitleVouchersGiftCards' => '優惠券與禮品卡',
    'str_LabelAllowVouchers' => '允許優惠券',
    'str_LabelAllowGiftCards' => '允許禮品卡',
    'str_LabelTaxCalculationBy' => '稅務計算根據',
    'str_LabelCompulsoryFields' => '注意:標有星號必須完成.',
    'str_LabelMakeSelection' => '請選擇',
    'str_LabelSelectLanguage' => '選擇語言',
    'str_LabelBrand' => '商標品牌',
    'str_LabelFilter' => '篩選',
    'str_LabelVoucherType' => '優惠劵類型',
    'str_LabelSellPrice' => '銷售價',
    'str_LabelAgentFee' => '代理費',
    'str_LabelLicenseeValue' => '授權價值',
    'str_LabelAlive' => '敏感的',
    'str_LabelUnreachable' => '不可觸摸的',
    'str_SectionTitleAbout' => '關於',
    'str_SectionTitleConstants' => '系統設定',
    'str_SectionTitleCurrencies' => '貨幣',
    'str_SectionTitleTax' => '稅率',
    'str_SectionTitleCovers' => '封面',
    'str_SectionTitlePaper' => '紙張',
    'str_SectionTitleProducts' => '產品',
    'str_SectionTitleShipping' => '運送',
    'str_SectionTitleUsers' => '使用者',
    'str_SectionTitleAutoUpdate' => '自動更新',
    'str_SectionTitlePaymentMethods' => '付款方式',
    'str_SectionTitleVouchers' => '折價券',
    'str_SectionTitleGiftCards' => '禮品卡',
    'str_SectionTitleVouchersGiftCards' => '優惠劵和禮品卡',
    'str_SectionTitleCustomers' => '客戶',
    'str_SectionTitleBranding' => '品牌',
    'str_SectionTitleExport' => '資料匯出',
    'str_SectionTitleSites' => '網站',
    'str_SectionTitleComponents' => '組件',
    'str_SectionTitleMultiSite' => '多重站點',
    'str_SectionTitleComponentPricing' => '組件價格',
    'str_SectionTitleImageServers' => '圖像伺服器',
    'str_SectionTitleProductURLs' => '產品網址',
    'str_SectionTitleTAOPIXOnline' => 'taopix在線版',
    'str_TitleVolumes' => '驅動器',
    'str_AutoUpdateTitleApplication' => '應用程式',
    'str_AutoUpdateTitleLicenseKeys' => '授權碼',
    'str_AutoUpdateTitleProducts' => '產品',
    'str_AutoUpdateTitleProductCollections' => '產品集合',
    'str_AutoUpdateTitleBackgrounds' => '背景',
    'str_AutoUpdateTitleMasks' => '遮罩',
    'str_AutoUpdateTitleScrapbook' => '物件庫圖片',
    'str_AutoUpdateTitleFrames' => '邊框',
    'str_TaxTitleTaxRates' => '稅率',
    'str_TaxTitleTaxZones' => '稅區',
    'str_ShippingTitleShippingMethods' => '運送方式',
    'str_ShippingTitleShippingRates' => '運費',
    'str_ShippingTitleShippingZones' => '貨運區域',
    'str_VoucherTitleSingleVouchers' => '單次折價券',
    'str_VoucherTitleVoucherPromotions' => '促銷活動',
    'str_VoucherTitleGiftCards' => '禮品卡',
    'str_ExportTitleManual' => '手動匯出',
    'str_ExportTitleEvent' => '輸出項目',
    'str_SiteAdmin' => '網站管理',
    'str_SiteCompanies' => '公司管理',
    'str_StoreGroups' => '站點群組',
    'str_SectionTitleScheduledTasks' => '預定任務',
    'str_SectionTitleScheduledEvents' => '事件列表',
    'str_SectionTitleMetaData' => '自定義數據',
    'str_SectionTitleMetaDataKeyWords' => '關鍵字',
    'str_SectionTitleMetaDataAllKeyWords' => '所有關鍵字',
    'str_SectionTitleMetaDataKeyWordGroups' => '關鍵字群組',
    'str_SiteOrderRouting' => '通路',
    'str_QtyPriceRangeStart' => '數量範圍開始',
    'str_QtyPriceRangeEnd' => '數量範圍結束',
    'str_PageCountRangeStart' => '頁面數量範圍開始',
    'str_PageCountRangeEnd' => '頁面數量範圍結束',
    'str_LabelDefaultValue' => '預設值',
    'str_LabelSortOrder' => '訂單排序',
    'str_LabelSort' => '排序',
    'str_LabelOrder' => '訂單',
    'str_LabelComponent' => '組件',
    'str_SidePriceRangeStart' => '價格起始範圍',
    'str_SidePriceRangeEnd' => '價格結束範圍',
    'str_PriceRangeBasePrice' => '基本價格',
    'str_PriceRangeUnitPrice' => '單位價格',
    'str_LabelOrderValueRange' => '適用價格範圍',
    'str_ComponentPriceRangeStart' => '組件數量開始範圍',
    'str_ComponentPriceRangeEnd' => '組件數量結束範圍',
    'str_OrderValueRangeWITHOUTTAX' => '未稅',
    'str_OrderValueRangeWITHTAX' => '含稅',
    'str_InvalidVoucherPromotionCode' => '無效的促銷折價券代碼',
    'str_InvalidCompanyCode' => '無效的公司代碼',
    'str_LabelAddress' => '位址',
    'str_LabelSMTPAddress' => 'SMTP 位址',
    'str_LabelSMTPPort' => 'SMTP 埠',
    'str_LabelSMTPAuthentication' => 'SMTP 認證',
    'str_LabelSMTPType' => 'SMTP 類型',
    'str_LabelNoneSMTPType' => '無',
    'str_LabelSSLSMTPType' => 'SSL',
    'str_LabelTLSSMTPType' => 'TLS',
    'str_LabelFrom' => '來自',
    'str_LabelReplyTo' => '回覆',
    'str_LabelProduction' => '生產',
    'str_LabelConfirmation' => '確認',
    'str_LabelSaveOrder' => '保存訂單',
    'str_LabelApplicationName' => '軟體名稱',
    'str_LabelSelectCompany' => '選擇公司',
    'str_LabelCloseWindow' => '關閉窗口',
    'str_MessagePleaseWait' => '請稍候...',
    'str_LabelDefaultIPAccessList' => '默認IP訪問列表',
    'str_LabelIPAccessType' => 'IP訪問類型',
    'str_LabelUserIPAccessList' => '用戶IP訪問列表',
    'str_LabelUseDefaultAccessIPList' => '使用默認的IP訪問列表',
    'str_LabelIPAccessList' => 'IP訪問列表',
    'str_MessageCompulsoryInformationMissing' => '請閱讀標有 ^0處',
    'str_LabelGiftCard' => '禮品卡',
    'str_LabelAmountToPay' => '支付金額',
    'str_LabelAmountPaid' => '支付金額',
    'str_LabelAmountDue' => '到期金額',
    'str_LabelGiftCardAccepted' => '接受禮品卡',
    'str_LabelGiftCardUsed' => '禮品卡已被使用',
    'str_LabelGiftCardFailed' => '禮品卡使用失敗',
    'str_LabelInvalidGiftCard' => '禮品卡使用失敗',
    'str_MessageCompulsoryFirstNameMandatory' => '名字為必填項',
    'str_MessageCompulsoryLastNameMandatory' => '姓名為必填項',
    'str_MessageCompulsoryCompanyMandatory' => '公司名稱為必填項',
    'str_MessageCompulsoryAdd1Mandatory' => '地址欄第一行為必填項',
    'str_MessageCompulsoryAdd2Mandatory' => '地址欄第二行為必填項',
    'str_MessageCompulsoryAdd3Mandatory' => '地址欄第三行為必填項',
    'str_MessageCompulsoryAdd4Mandatory' => '地址欄第四行為必填項',
    'str_MessageCompulsoryCityMandatory' => '鎮/城市為必填項',
    'str_MessageCompulsoryCountyMandatory' => '縣為必填項',
    'str_MessageCompulsoryStateMandatory' => '省為必填項',
    'str_MessageCompulsoryPostCodeMandatory' => '郵政編碼為必填項',
    'str_MessageCompulsoryUserNameLength' => '用戶名必須至少 ^0字符',
    'str_MessageCompulsoryUserNameMismatch' => '用戶名必須相同',
    'str_MessageCompulsoryPasswordLength' => '密碼長度為^0個字符',
    'str_MessageCompulsoryPasswordLength2' => '密碼長度字符數範圍為^0個到^1個',
    'str_MessageCompulsoryPasswordMismatch' => '密碼與密碼驗證必須相同',
    'str_MessageCompulsoryPhoneMandatory' => '手機號碼為必填項',
    'str_MessageCompulsoryEmaiInvalid' => '電子郵件地址好像不正確',
    'str_MessageCompulsoryEmailMismatch' => '電子郵件與電子郵件認證必須相同',
    'str_MessageUpdateAddressDetails' => '請更新您的詳細地址',
    'str_MessageCompulsoryCorporateTaxNumberLength' => '您公司的稅務號碼至少^0 位數.',
    'str_MessageCompulsoryPersonalTaxNumberLength' => '您個人的稅務號碼至少^0 位數.',
    'str_MessageInvalidCorporateTaxNumber' => '無效的公司稅務號碼',
    'str_MessageInvalidPersonalTaxNumber' => '無效的個人稅務號碼',
    'str_MessageUpdating' => '更新中...',
    'str_MessageDeleting' => '刪除中...',
    'str_WarningTerminateOtherSession' => '該作品最近在另一個瀏覽器窗口中打開。再次打開該項目將阻止其在其他瀏覽器窗口被使用。<br><br>點擊查看，你確定要繼續嗎？',
    'str_WarningDeleteTerminateOtherSession' => '該項目最近在另一個窗口中打開。刪除該項目將阻止其在其他窗口被使用。<br><br>點擊查看，你確定要繼續嗎？',
    'str_WarningProjectOpenInShoppingCart' => '你最近嘗試訂購該項目。首先建議您不要繼續，先檢查打開瀏覽器窗口中的訂購。<br><br>點擊查看，你確定要繼續嗎？',
    'str_MessageExporting' => '輸出中...',
    'str_MessageSaving' => '儲存中...',
    'str_LabelProductionSite' => '生產站點',
    'str_LabelDistributionCentre' => '配送中心',
    'str_LabelSiteCode' => '站點',
    'str_LabelStore' => '商店',
    'str_LabelCompany' => '公司',
    'str_LabelEnableGrouping' => '啟用群組',
    'str_TitleZone' => '區',
    'str_TitleZones' => '區',
    'str_LabelSettings' => '設置',
    'str_LabelOptions' => '選項',
    'str_Activating' => '啟用...',
    'str_Deactivating' => '不啟用...',
    'str_LabelRate' => '比率',
    'str_LabelRates' => '比率',
    'str_Other' => '其他',
    'str_Global' => '總體的',
    'str_ShowAll' => '顯示全部',
    'str_LabelCollectFromStore' => '從商店收集',
    'str_LabelStoreGroup' => '商店群組',
    'str_LabelPayInStore' => '在商店付費',
    'str_LabelPayInStoreAllowed' => '允許店內付費',
    'str_LabelPayInStoreNotAllowed' => '不允許店內付費',
    'str_LabelPayInStoreOnly' => '只允許店內付費',
    'str_LabelShowAll' => '顯示全部',
    'str_LabelRestOfWorld' => '世界其他地區',
    'str_ExtJsErrorNoName' => '請輸入名稱.',
    'str_LabelWebSite' => '網站',
    'str_LabelStoreAddress' => '商店地址',
    'str_LabelStoreDetails' => '商店詳細資料',
    'str_LabelOpeningTimes' => '開放時間',
    'str_LabelStoreGrouping' => '商店群組',
    'str_LabelSelectCountry' => '選擇國家',
    'str_ComponentTitleComponentCategories' => '組件類別',
    'str_ComponentTitleComponentTypes' => '組件類型',
    'str_LabelPrompt' => '提示語',
    'str_LabelPricingModel' => '定價模式',
    'str_LabelDisplayType' => '顯示類型',
    'str_LabelComponentype' => '組件類型',
    'str_LabelInfo' => '訊息',
    'str_LabelSKUCode' => 'SKU 代碼',
    'str_LabelCheckBox' => '複選框',
    'str_LabelMultiLine' => '多行',
    'str_LabelSingleLine' => '單行',
    'str_LabelRadioButtonGroup' => '單選按鈕組',
    'str_LabelRadioButtonGroupPopUpList' => '單選按鈕組 / 彈出列表',
    'str_LabelPopupList' => '彈出列表',
    'str_LabelList' => '列表',
    'str_LabelRootComponent' => '根組件',
    'str_LabelComponentList' => '組件列表',
    'str_LabelComponentStructure' => '組件結構',
    'str_SectionWindowTitleComponents' => '組件類別 \'^0\'',
    'str_ErrorNoLicenseKeysSelected' => '無授權碼選定.',
    'str_LabelDiscountSectionPRODUCT' => '產品',
    'str_LabelPrice' => '價格',
    'str_LabelPrices' => '價格',
    'str_LabelTransactionAccepted' => '接受交易',
    'str_LabelTransactionRejected' => '拒絕交易',
    'str_LabelPriceList' => '價目表',
    'str_LabelCustomPrice' => '自定價格',
    'str_LabelSaveAsPriceList' => '儲存價格表',
    'str_TitleSelectPreviewImage' => '選擇預覽圖像',
    'str_LabelSelectPreviewImage' => '建議預覽圖像的尺寸不超過620x100像素.',
    'str_LabelRequiresPageCount' => '需要頁數',
    'str_LabelDefaultPricing' => '預設定價',
    'str_LabelPriceLists' => '價目表',
    'str_LabelAddPriceLists' => '新增價目表',
    'str_LabelEditPriceLists' => '編輯價目表',
    'str_TitleSavePriceAsPriceList' => '另存為價目表',
    'str_TitleAccessRestrictions' => '訪問限制',
    'str_LabelSections' => '區段',
    'str_LabelSection' => '區段',
    'str_MessageLogoFileTypes' => '只允許 PNG, JPG and GIF.',
    'str_MessageLogoSelectImage' => '請選擇一個圖像.',
    'str_MessageLogoDimensions' => 'LOGO尺寸 ^w x ^h。\\n此推薦LOGO圖像最大尺寸為600*150像素',
    'str_ButtonUpdateLogo' => '更新商標',
    'str_ButtonRemoveLogo' => '移除商標',
    'str_ButtonResetLogo' => '重置商標',
    'str_ErrorMinPageCountError' => '最少頁數必須為1.',
    'str_ErrorMaxPageCountError' => '最大頁數不能少於最少頁數.',
    'str_LabelPriority' => '優先順序',
    'str_MessageChangingPriority' => '改變優先等級',
    'str_LabelPriorityNormal' => '更新為低優先等級',
    'str_LabelPriorityCritical' => '更新為高優先等級',
    'str_LabelSelectAll' => '選擇全部',
    'str_LabelItems' => '項目',
    'str_LabelItem' => '項目',
    'str_LabelNever' => '永久',
    'str_LabelNeverRun' => '永久運行',
    'str_LabelNextRun' => '下次運行',
    'str_LabelTaxSettings' => '稅設置',
    'str_LabelTaxCode' => '稅代碼',
    'str_LabelPricingIncludesTax' => '價格包含稅',
    'str_LabelIncludesTax' => '含稅',
    'str_LabelShippingTaxCode' => '送貨稅代碼',
    'str_LabelTaxLevel1' => '稅率等級1',
    'str_LabelTaxLevel2' => '稅率等級2',
    'str_LabelTaxLevel3' => '稅率等級3',
    'str_LabelTaxLevel4' => '稅率等級4',
    'str_LabelTaxLevel5' => '稅率等級5',
    'str_MessageLoading' => '載入中...',
    'str_MessageSendingEmail' => '發送電子郵件中...',
    'str_NoInformation' => '沒有信息',
    'str_LabelHeaderPrice' => '價格',
    'str_LabelNavigationCart' => '我的購物車',
    'str_LabelNavigationShippingBilling' => '送貨/計費',
    'str_LabelNavigationPayment' => '付費',
    'str_LabelNavigationConfirmation' => '確認',
    'str_MessageNoAdditionalInformation' => '沒有組建信息',
    'str_LabelPreference' => '偏好設置',
    'str_TitleTermsAndConditions' => '條款和條件',
    'str_LabelTermsAndConditionsAgreement' => '我已閱讀並同意',
    'str_LabelEnableOnline' => '開啓在線版',
    'str_LabelDisableOnline' => '關閉在線版',
    'str_LabelAvailableOnline' => '提供在線版',
    'str_LabelOrderFromPreview' => '訂購預覽',
    'str_LabelRequiredOptions' => '所需選項',
    'str_labelShippingTotal' => '送貨總計',
    'str_CountryOptional' => '國家（可選）',
    'str_RegionOptional' => '地區（可選）',
    'str_SiteGroupOptional' => '地址組（可選）',
    'str_LabelSharePasswordProtection' => '激活密碼保護嗎？',
    'str_LabelSharePassword' => '密碼',
    'str_LabelShareConfirmPassword' => '再次輸入密碼',
    'str_LabelByEmail' => '通過郵件分享',
    'str_LabelShare' => '分享',
    'str_LabelShareProject' => '分享作品:^0',
    'str_LabelShareWithEmails' => '通過郵件分享（用逗號分開）：',
    'str_LabelShareWithEmail' => '通過郵件分享',
    'str_LabelShareMessageText' => '消息文本：',
    'str_MessageHowWouldYouLikeToShare' => '你現如何分享你的作品呢？',
    'str_MessageCantFindService' => '不能找到該服務，請聯繫客戶支援',
    'str_LabelClose' => '關閉',
    'str_MessagePasswordInformation' => '請確保密碼和確認密碼字段填寫正確，然後再寫一次',
    'str_LabelMessageTitle' => '留言標題：',
    'str_MessageSelectAService' => '選擇服務：',
    'str_MessageEnterMessageTitle' => '請輸入你的留言標題',
    'str_MessageEnterAtLeastOneEmail' => '請至少指定一個電子郵件地址',
    'str_LabelPasswordProtection' => '密碼保護',
    'str_labelShareEmail' => '郵件',
    'str_labelShareSocialNetworks' => '社交網絡',
    'str_TitleShareViaSocialNewtworks' => '通過社交網絡分享',
    'str_TitleShareViaEmail' => '通過郵件分享',
    'str_MessageCheckEmailSoftware' => '您的電子郵件準備。\\n請檢查您的電子郵件工具來發送電子郵件。',
    'str_TitleConfirmation' => '確認',
    'str_TitleError' => '錯誤',
    'str_TitleWarning' => '警告',
    'str_Error' => '錯誤',
    'str_ErrorNoJavaScript' => '錯誤. Javascript 必須在此網站啟用以正確運作.',
    'str_DatabaseError' => '資料庫錯誤 \'^0\'',
    'str_ConnectionError' => '無法連接到數據庫',
    'str_ErrorNoSessionRef' => '無Session編號',
    'str_ErrorInvalidPrice' => '無效的產品價格',
    'str_ErrorPriceNotActive' => '無效的產品價格. 如果您需要協助請聯繫客服人員.',
    'str_ErrorNoPriceForRange' => '數量範圍內無產品價格. 如果您需要協助請聯繫客服人員.',
    'str_ErrorNoAccount' => '此帳戶並無詳細內容',
    'str_ErrorAccountNotActive' => '您的帳戶未啟用. 如果您需要協助請聯繫客服人員.',
    'str_ErrorAccountTaskNotAllowed' => '您的帳戶不允許執行此工作. 如果您需要協助請聯繫客服人員.',
    'str_ErrorCannotChangePassword' => '不允許您變更密碼. 如果您需要協助請聯繫客服人員.',
    'str_ErrorNoCode' => '請輸入代碼.',
    'str_ErrorNoName' => '請輸入名稱.',
    'str_ErrorCustomer' => '請選擇一個有效的顧客',
    'str_ErrorNoCountry' => '請輸入國家.',
    'str_ErrorNoCompanyName' => '請輸入公司名稱.',
    'str_ErrorNoCity' => '請輸入鎮/市 名稱.',
    'str_ErrorNoCounty' => '請具體指定郡/縣.',
    'str_ErrorNoState' => '請具體指定州別.',
    'str_ErrorNoProvince' => '請具體指定省份.',
    'str_ErrorNoUserName' => '請輸入你的登入名稱',
    'str_ErrorNoEmailAddress' => '請輸入您的電子郵箱地址',
    'str_ErrorNoPassword' => '您必須輸入您的密碼.',
    'str_ErrorDuplicateUserName' => '該用戶名已經存在',
    'str_ErrorDuplicateEmail' => '該電子郵箱地址已經存在',
    'str_ErrorInvalidQty' => '請輸入有效的數量.',
    'str_ErrorCompulsoryInformationMissing' => '必要資訊將會遺失，因為必填項目尚未完成.',
    'str_ErrorCompulsoryFields' => '請完成所有必填選項.',
    'str_ErrorNoProduct' => '請選擇產品',
    'str_ErrorNoLicenseKey' => '請選擇授權碼.',
    'str_ErrorInvalidCreditLimitValue' => '請輸入有效的信用限制額度',
    'str_ErrorNoPaymentMethods' => '您至少必須選擇一種付款方式.',
    'str_ErrorUploadInvalidFileType' => '錯誤. 只能上傳 JPEG, GIF 或 PNG.',
    'str_ErrorRangeStartError1' => '購買數量範圍須從1開始.',
    'str_ErrorRangeStartError2' => '購買數量開始範圍不能低於之前的範圍.',
    'str_ErrorRangeEndError' => '購買數量結束範圍不能低於開始範圍.',
    'str_ErrorComponentPriceError' => '組建的數量必須高於或等於0.',
    'str_ErrorProductPriceError' => '產品的數量必須是大於或等於1.',
    'str_ErrorOrderValueRangeError1' => '最大訂購數必須大於0.',
    'str_ErrorOrderValueRangeError2' => '最大訂購數必須大於最小訂購數.',
    'str_ErrorRangeEndLimitError' => '最大數值不能超過99999999.',
    'str_ErrorTitleInvalidPricing' => '無效的價格',
    'str_ErrorEnterValidPricing' => '請輸入一個有效的定價範圍',
    'str_ErrorInvalidStartDate' => '請輸入一個有效的開始日期.',
    'str_ErrorInvalidEndDate' => '請輸入一個有效的截止日期.',
    'str_ErrorPaymentIntegrationRequiresSSL' => '付款整合 \'^0\' 必須載入 SSL, 但目前情況並非如此.',
    'str_ErrorFieldValueInvalid' => '在這一領域的值是無效的',
    'str_ErrorClientInvalid' => '不能提交表單可能是無效值',
    'str_ErrorConnectFailure' => '伺服器的通信失敗.',
    'str_ErrorProductionSiteInActive' => '此帳戶的生產現場是不啟用，請與系統管理員聯繫.',
    'str_ErrorDistributionCentreInActive' => '此帳戶的配送中心是不啟用，請與系統管理員聯繫.',
    'str_ErrorStoreInActive' => '此帳戶的商店是不啟用，請與系統管理員聯繫.',
    'str_ErrorDistributionCentreOffline' => '此帳戶的配送中心處於離線狀態，請與系統管理員聯繫.',
    'str_ErrorStoreOffline' => '此帳戶的商店處於離線狀態，請與系統管理員聯繫.',
    'str_ErrorScriptNotFound' => '在任務文件夾裡面找不到相應的腳本語言',
    'str_ErrorNoRunMethod' => '在腳本語言裡面找不到運行方式',
    'str_ErrorNoScriptName' => '在任務記錄裡面沒有腳本語言名稱',
    'str_ErrorWrongPhpPath' => '運行PHP的路徑不存在',
    'str_ErrorWrongTaskRunnerPath' => '任務執行路徑不存在',
    'str_ErrorTaskRunnerFailedAtStartup' => '任務執行進程不能啟動',
    'str_ErrorNoStartCharacter' => '沒有開始字符',
    'str_ErrorNoEndCharacter' => '沒有結束字符',
    'str_ErrorIPNotAllowed' => '不允許此IP 地址',
    'str_ErrorPricelistExists' => '此代碼的價格表已存在',
    'str_ErrorInvalidSellPrice' => '請輸入銷售價格',
    'str_ErrorInvalidAgentFee' => '代理費必須大於銷售價格',
    'str_ErrorInvalidLicenseeValue' => '被授權值必須大於或等於零',
    'str_LabelStartDateLaterEndDate' => '開始日期不能晚於結束日期.',
    'str_LabelInvalidDateFormat' => '這不是一個有效的日期- 必須按照此格式填寫^0.',
    'str_MessageInvalidEmail' => '你指定的是一個無效的電子郵箱地址',
    'str_ErrorProductNotAvailable2' => '該產品\'^0\'已不存在。如果您需要幫助，請聯繫客戶服務。',
    'str_SinglePrintNoPriceAvailableError' => '暫無報價單打印\'^0\'。如果您需要幫助，請聯系客戶服務。',
    'str_SinglePrintNoOptionProvidedError' => '沒有規定的單個打印\'^0\'選項。如果您需要幫助，請聯繫客戶服務。',
    'str_ErrorConfigMismatch' => 'taopix配置不匹配。',
    'str_ExtJsDateFormat' => '月/日/年',
    'str_ExtJsTimeFormat' => 'g:i A',
    'str_ExtJsDecimalSeparator' => '.',
    'str_ExtJsThousandsSeparator' => ',',
    'str_ExtJsNumberFieldDecimalPrecision' => '2',
    'str_ExtJsAlertLoading' => '載入中...',
    'str_ExtJsSelectedRow' => '{0} 選取 行{1}',
    'str_ExtJsMonthJanuary' => '一月',
    'str_ExtJsMonthFebruary' => '二月',
    'str_ExtJsMonthMarch' => '三月',
    'str_ExtJsMonthApril' => '四月',
    'str_ExtJsMonthMay' => '五月',
    'str_ExtJsMonthJune' => '六月',
    'str_ExtJsMonthJuly' => '七月',
    'str_ExtJsMonthAugust' => '八月',
    'str_ExtJsMonthSeptember' => '九月',
    'str_ExtJsMonthOctober' => '十月',
    'str_ExtJsMonthNovember' => '十一月',
    'str_ExtJsMonthDecember' => '十二月',
    'str_ExtJsDaySunday' => '星期日',
    'str_ExtJsDayMonday' => '星期一',
    'str_ExtJsDayTuesday' => '星期二',
    'str_ExtJsDayWednesday' => '星期三',
    'str_ExtJsDayThursday' => '星期四',
    'str_ExtJsDayFriday' => '星期五',
    'str_ExtJsDaySaturday' => '星期六',
    'str_ExtJsDatePickerToday' => '今天',
    'str_ExtJsDatePickerMin' => '此日期之前的最近日期',
    'str_ExtJsDatePickerMax' => '此日期之後的最遠日期',
    'str_ExtJsDatePickerNext' => '下個月 (Control+Right)',
    'str_ExtJsDatePickerPrev' => '上個月 (Control+Left)',
    'str_ExtJsDatePickerMonthYear' => '選擇月份 (Control+Up/Down 移動年份)',
    'str_ExtJsDatePickerTodayTip' => '{0} (Spacebar)',
    'str_ExtJsPagingToolbarBeforePage' => '頁',
    'str_ExtJsPagingToolbarAfterPage' => '的 {0}',
    'str_ExtJsPagingToolbarFirst' => '第一頁',
    'str_ExtJsPagingToolbarPrev' => '上一頁',
    'str_ExtJsPagingToolbarNext' => '下一頁',
    'str_ExtJsPagingToolbarLast' => '最後頁',
    'str_ExtJsPagingToolbarRefresh' => '刷新',
    'str_ExtJsPagingToolbarDisplay' => '顯示 {0} - {2} 的 {1}',
    'str_ExtJsPagingToolbarEmpty' => '沒有任何數據顯示',
    'str_ExtJsTextFieldMinLength' => '此區域的最小長度是 {0}',
    'str_ExtJsTextFieldMaxLength' => '此區域的最大長度是 {0}',
    'str_ExtJsTextFieldBlank' => '此區域是必需的',
    'str_ExtJsTypeValue' => '類型值',
    'str_ExtJsNumberFieldMin' => '這一區域的最低值是 {0}',
    'str_ExtJsNumberFieldMax' => '這一區域的最大值是 {0}',
    'str_ExtJsNumberFieldNan' => '{0} 不是一個有效的數字',
    'str_ExtJsDateFieldDisabledDays' => '失效的',
    'str_ExtJsDateFieldDisabledDates' => '失效的',
    'str_ExtJsDateFieldMin' => '這一領域的日期必須在 {0} 之後',
    'str_ExtJsDateFieldMax' => '這一領域的日期必須在 {0} 之前',
    'str_ExtJsDateFieldInvalid' => '{0} 不是有效的日期 - 必須是格式 {1}',
    'str_ExtJsVTypesEmail' => '這個區域應該是一個e-mail地址格式 \'user@example.com\'',
    'str_ExtJsVTypesUrl' => '這個區域應該是一個 URL的格式 \'http://www.example.com\'',
    'str_ExtJsVTypesAlpha' => '這個字段應該只包含字母和 _',
    'str_ExtJsVTypesAlphaNum' => '此字段應該只包含字母，數字和 _',
    'str_ExtJsGridViewSortAsc' => '升序',
    'str_ExtJsGridViewSortDesc' => '降序',
    'str_ExtJsGridViewColumns' => '列',
    'str_ExtJsGroupingViewEmptyGroup' => '(無)',
    'str_ExtJsGroupingViewGroupBy' => '此區群組',
    'str_ExtJsGroupingViewShowGroups' => '以群組顯示',
    'str_ExtJsPropertyColumnModelName' => '名稱',
    'str_ExtJsPropertyColumnModelValue' => '價值',
    'str_ExtJsBooleanColumnTrue' => '真',
    'str_ExtJsBooleanColumnFalse' => '假',
    'str_ExtJsBorderLayoutSplit' => '拖動以調整大小.',
    'str_ExtJsBorderLayoutCollapsibleSplit' => '拖動以調整大小，雙擊隱藏.',
    'str_ExtJsTimeFieldMin' => '在這一區域的時間必須等於 {0} 或之後',
    'str_ExtJsTimeFieldMax' => '在這一區域的時間必須等於 {0} 或之前',
    'str_ExtJsTimeFieldInvalid' => '{0} 不是一個有效的時間',
    'str_ExtJsCheckboxGroupBlank' => '在此群組裡，您必須選擇至少一個項目，',
    'str_ExtJsRadioGroupBlank' => '在此群組裡，你必須選擇一個項目',
    'str_LabelFixedQuantityRanges' => '固定數量範圍',
    'str_ExtJsErrorInvalidTrigger' => '所選擇的配置不能被激活，因為他們沒有被正確配置。',
    'str_MessageAuthMode_LoginPass' => '登錄名和密碼不存在，或者是無效的。如果您需要幫助，請聯系客戶服務人員。',
    'str_MessageAuthMode_Login' => '登錄名不存在或無效。如果您需要幫助，請聯系客戶服務人員。',
    'str_MessageAuthMode_Username' => '用戶名不存在或無效。如果您需要幫助，請聯系客戶服務人員。',
    'str_MessageAuthMode_Password' => '密碼不存在或無效。如果您需要幫助，請聯系客戶服務人員。',
    'str_MessageAuthMode_AuthKey' => '身份驗證密鑰不存在，或者是無效的。如果您需要幫助，請聯系客戶服務人員。',
    'str_MessageAuthMode_Code' => '代碼不存在或無效。如果您需要幫助，請聯系客戶服務人員。',
    'str_MessageAuthMode_SerialNumber' => '序列號不存在，或者是無效的。如果您需要幫助，請聯系客戶服務人員。',
    'str_MessageAuthMode_ActivationCode' => '激活代码不存在或无效。如果您需要帮助，请联系客户服务人员。',
  ),
));
}
}
