<?php

ini_set('display_errors', 1);
error_reporting(E_ALL);

class exportTask
{
	// define default settings for this task
	static function register()
	{
		$defaultSettings = array();

	   /*
		* $defaultSettings('type') defines type of tasks
		* 0 - scheduled
		* 1 - service
		* 2 - manual
		*/

		$defaultSettings['type'] = '0';
		$defaultSettings['code'] = TPX_EXPORT;
		$defaultSettings['name'] = 'it export in italian<p>fr export in french<p>es export in spanish';

	   /*
		* $defaultSettings('intervalType') defines inteval value
		* 1 - Number of minutes
		* 2 - Exact time of the day
		* 3 - Number of days
		*/
		$defaultSettings['intervalType']  = '1';
		$defaultSettings['intervalValue'] = '5';
		$defaultSettings['maxRunCount']  = '10';
		$defaultSettings['deleteCompletedDays'] = '5';

		return $defaultSettings;
	}


	// function to run this task
	static function run($pEventID)
	{
		$resultMessage = '';
		$result = '';

		try
		{
			$pEventID = (int)$pEventID[0];

			// get list of events for the task
			$taskCode = self::register();
			$taskCode = $taskCode['code'];

			TaskObj::writeLogEntry('Task: ' . $taskCode . '. Retrieving Events.');

			if ($pEventID > 0)
			{
				$eventsList = TaskObj::getEventByID($pEventID);
			}
			else
			{
				$eventsList = TaskObj::getEventsByTaskCode($taskCode, 200);
			}

			if ($eventsList['result'] == '')
			{
				$eventsList = $eventsList['events'];
				$eventCount = count($eventsList);

				TaskObj::writeLogEntry('Task: ' . $taskCode . '. Found ' . $eventCount . ' Events.');

				for ($i = 0; $i < $eventCount; $i++)
				{
                    UtilsObj::resetPHPScriptTimeout(30);

					$event = &$eventsList[$i];

					TaskObj::writeLogEntry('Task: ' . $taskCode . '. Executing Event ' . ($i + 1) .  ' Of ' . $eventCount . ' (' . $event['id'] . ').');

					try
       		 		{
						if ($event['parentId'] > 0)
						{
							$parentEventList = TaskObj::getEventByID($event['parentId']);
							$parentEventList = $parentEventList['events'];
							$parentEvent = $parentEventList[0];
							$event['param3'] = $parentEvent['param3'];
							$event['param1'] = $parentEvent['param1'];
						}

						$filePath = str_replace("\\", '/', $event['param3']);
						// allow eventID to be added to the filename 
						$event['param3'] = str_ireplace('[EVENTID]', $event['id'], $filePath);
						$directories = explode('/', $filePath);
						$dirCount = count($directories);

						// if the first character is a slash then it is a unix path starting with /
						$fileWritePath = '';
						if (substr($filePath, 0, 1) == '/')
						{
							$fileWritePath = '/';
						}
						else
						{
							$fileWritePath = $directories[0] . '/';
						}

						// start creating the directory structure
						$origMask = umask(0);

						//creating directories and subdirectories.
						if (($fileWritePath != '') && (! file_Exists($fileWritePath)))
						{
							@mkdir($fileWritePath, 0777, true);
							if (! file_Exists($fileWritePath))
							{
								$result = "EXPORT PATH NOT CREATED: '$php_errormsg': " . $fileWritePath;
							}
						}

						// make sure we don't have an error and can continue
						if ($result == '')
						{
							// when building the directory do not include the last trailing slash
							for ($n = 1; $n < $dirCount - 1; $n++)
							{
								if ($directories[$n] != '')
								{
									$fileWritePath .= $directories[$n] . '/';

									if (! file_Exists($fileWritePath))
									{
										@mkdir($fileWritePath, 0777, true);

										if (! file_Exists($fileWritePath))
										{
											$result = "EXPORT PATH NOT CREATED: '$php_errormsg': " . $fileWritePath;
											break;
										}
									}
								}
							}
						}
						umask($origMask);

						if ($result == '')
						{
							// check to see if file exists
							if (file_exists($event['param3']))
							{
								@unlink($event['param3']);
							}

							if (! file_exists($event['param3']))
							{
								$fileHandle = @fopen($event['param3'], 'x+');
								if ($fileHandle)
								{
									// If we have params 4,5, and 6 filled for an export we are loading a dataset.
									if (($event['param4'] != '') && ($event['param5'] != '') && ($event['param6'] != ''))
									{
										// If the data export object hasnt been instanced yet include it.
										if (! class_exists('DataExportObj'))
										{
											require_once('../Utils/UtilsDataExport.php');
										}

										// Check the dataset exists.
										if (file_exists($event['param1']))
										{
											// Include the dataset that was generated by the trigger. This is a php file that contains the $dataSet array.
											include $event['param1'];

											// Generate the file contents based the dataset included and the event params.
											$fileContents = DataExportObj::exportDataGenerate($dataSet, $event['param4'], $event['param5'], $event['param6']);

											// Remove dataset so we dont store the dataset indefinatley
											@chmod($event['param1'], 0777);
											@unlink($event['param1']);

											// clear the dataset
											$dataSet = [];
										}
										else
										{
											// Dataset file was not found.
											$sendingResult['result'] = 1;
											$sendingResult['resultParam'] = "en Could not open the dataset file " . $event['param1'];
										}
									}
									else
									{
										// Old style data export events where file content was stored in database.
										$fileContents = $event['param1'];
									}

									fwrite($fileHandle, $fileContents);
									fclose($fileHandle);

									if ($event['task1'] != '')
									{
										$taskInfo = TaskObj::getTask($event['task1']);
										if ($taskInfo['result'] == '')
										{
											$eventResultArray = TaskObj::createEvent($event['task1'], $event['companyCode'], $event['groupCode'], $event['webBrandCode'], $taskInfo['nextRunTime'], $event['id'], '', '', '', '', '', '', '', '', $event['orderheaderid'], $event['orderitemid'], $event['userid'], '', '');
											if ($eventResultArray['result'] != '')
											{
												$result = "en Unable to create event for task 1";
											}
										}
										else
										{
											$result = "en Unable to get task1";
										}
									}

									if ($result == '')
									{
										echo $event['task2'] ;

										if ($event['task2'] != '')
										{
											$taskInfo = TaskObj::getTask($event['task2']);
											if ($taskInfo['result'] == '')
											{
												$eventResultArray = TaskObj::createEvent($event['task2'], $event['companyCode'], $event['groupCode'], $event['webBrandCode'], $taskInfo['nextRunTime'], $event['id'], '', '', '', '', '', '', '', '', $event['orderheaderid'], $event['orderitemid'], $event['userid'], '', '');
												if ($eventResultArray['result'] != '')
												{
													$result = "en Unable to create event for task 2";
												}
											}
											else
											{
												$result = "en Unable to get task2";
											}
										}

										if ($result == '')
										{
											$sendingResult['result'] = 2;
											$sendingResult['resultParam'] = "";
										}
										else
										{
											$sendingResult['result'] = 1;
											$sendingResult['resultParam'] = $result;
										}
									}
									else
									{
										$sendingResult['result'] = 1;
										$sendingResult['resultParam'] = $result;
									}
								}
								else
								{
									$sendingResult['result'] = 1;
									$sendingResult['resultParam'] = "en Could not open or create the file " . $event['param3'];
								}
							}
							else
							{
								$sendingResult['result'] = 1;
								$sendingResult['resultParam'] = "en Could not open or create the file " . $event['param3'];
							}
						}
						else
						{
							$sendingResult['result'] = 1;
							$sendingResult['resultParam'] = "en " . $result;
						}
					}
					catch(Exception $e)
					{
						$resultMessage = 'en ' . $e->getMessage();
						$sendingResult['result'] = 1;
						$sendingResult['resultParam'] = $resultMessage;
					}

					TaskObj::updateEvent($event['id'], $sendingResult['result'], $sendingResult['resultParam']);
				}
			}
			else
			{
				//return error message to taskManager
				$resultMessage = $eventsList['resultparam'];
			}
		}
		catch(Exception $e)
		{
			$resultMessage = 'en ' . $e->getMessage();
		}

		return $resultMessage;
	}
}
?>