#EXPRESS_SERVER=https://www.sandbox.paypal.com/cgi-bin/webscr
EXPRESS_SERVER=https://www.paypal.com/cgi-bin/webscr
EXPRESS_API_SERVER=https://api-3t.paypal.com/nvp
EXPRESS_API_USERNAME=administration_api1.ubabybaby.com
EXPRESS_API_PASSWORD=VBZE4Z5EYECUWA94
EXPRESS_API_SIGNATURE=AzntkZu7MFCtLl-q87KaBmBgrGUJAy4SzzqzbluDCKOiYtEvkH27AS7Z
EXPRESS_SOLUTIONTYPE=Sole

CURRENCYTRANSFORM=
LOGOUTPUT=1
LOGFILEPATH=paypal_log.txt
