<?php
// Constants for ORDERROUTING[rule]
define('TPX_ROUTE_BY_BRAND_CODE', 0);
define('TPX_ROUTE_BY_LICENCE_KEY_CODE',	1);
define('TPX_ROUTE_BY_PRODUCT_CODE', 2);
define('TPX_ROUTE_BY_SHIPPING_COUNTRY_CODE', 3);
define('TPX_ROUTE_TO_VOUCHER_OWNER_CODE', 4);
define('TPX_ROUTE_TO_BRAND_OWNER_CODE',	5);

// Constants for ORDERROUTING[condition]
define('TPX_TEST_FOR_EQUALITY',	0);
define('TPX_TEST_FOR_DIFFERENCE', 1);

// Constants for user login types
define('TPX_LOGIN_SYSTEM_ADMIN', 0);
define('TPX_LOGIN_COMPANY_ADMIN', 1);
define('TPX_LOGIN_SITE_ADMIN', 2);
define('TPX_LOGIN_PRODUCTION_USER',	3);
define('TPX_LOGIN_DISTRIBUTION_CENTRE_USER', 4);
define('TPX_LOGIN_STORE_USER', 5);
define('TPX_LOGIN_BRAND_OWNER', 6);
define('TPX_LOGIN_CREATOR_ADMIN', 7);
define('TPX_LOGIN_CUSTOMER', 100);
define('TPX_LOGIN_LICENCE_SERVER_API', 200);
define('TPX_LOGIN_API',	300);
define('TPX_LOGIN_UNLOCKSYSTEMACCOUNT_USER', 400);

// Constants for ORDERITEMS[active]
define('TPX_ORDER_STATUS_IN_PROGRESS', 0);
define('TPX_ORDER_STATUS_CANCELLED', 1);
define('TPX_ORDER_STATUS_COMPLETED', 2);
define('TPX_ORDER_STATUS_CONVERTED', 3);

// Constants for ORDERITEMS[reorderstatus]
define('TPX_ITEM_CANNOT_REORDER', 0);
define('TPX_ITEM_CAN_REORDER', 1);
define('TPX_ITEM_CANNOT_REORDER_DESKTOP_ORDER_DATA_NOT_AVAILABLE', 2);
define('TPX_ITEM_CANNOT_REORDER_ONLINE_PROJECT_FLAGGED_FOR_DELETE', 3);
define('TPX_ITEM_CANNOT_REORDER_ONLINE_PROJECT_BEING_DELETED', 4);

// Constants for ORDERITEMS[status]
define('TPX_ITEM_STATUS_AWAITING_FILES', 0);
define('TPX_ITEM_STATUS_FILES_ON_REMOTE_FTP_SERVER', 1);
define('TPX_ITEM_STATUS_DOWNLOAD_FILES_QUEUED',	2);
define('TPX_ITEM_STATUS_DOWNLOADING_FROM_REMOTE_FTP_SITE', 3);
define('TPX_ITEM_STATUS_DOWNLOAD_FILES_FTP_ERROR', 4);
define('TPX_ITEM_STATUS_FILES_RECEIVED', 5);
define('TPX_ITEM_STATUS_IMPORT_FILES_ERROR', 6);
define('TPX_ITEM_STATUS_DECRYPT_FILES_QUEUED', 10);
define('TPX_ITEM_STATUS_DECRYPTING_FILES', 11);
define('TPX_ITEM_STATUS_DECRYPTING_FILES_ERROR', 12);
define('TPX_ITEM_STATUS_DECRYPTED_FILES', 13);
define('TPX_ITEM_STATUS_RAW_FILES_READY_TO_PROCESS', 14);
define('TPX_ITEM_STATUS_RAW_FILES_QUEUED_FOR_RENDER_SUBMISSION', 15);
define('TPX_ITEM_STATUS_RAW_FILES_QUEUED_FOR_RENDERING', 16);
define('TPX_ITEM_STATUS_RAW_FILES_RENDER_ERROR', 17);
define('TPX_ITEM_STATUS_CONVERT_FILES_QUEUED', 20);
define('TPX_ITEM_STATUS_CONVERTING_FILES', 21);
define('TPX_ITEM_STATUS_CONVERTING_FILES_ERROR', 22);
define('TPX_ITEM_STATUS_CONVERTED_FILES', 23);
define('TPX_ITEM_STATUS_READY_TO_PRINT', 40);
define('TPX_ITEM_STATUS_PRINT_FILES_QUEUED', 41);
define('TPX_ITEM_STATUS_PRINTING_FILES_PRINTING', 42);
define('TPX_ITEM_STATUS_PRINTING_FILES_ERROR', 43);
define('TPX_ITEM_STATUS_PRINTING_SENT_TO_EXTERNAL_WORKFLOW', 44);
define('TPX_ITEM_STATUS_PRINTED', 45);
define('TPX_ITEM_STATUS_FINISHING_COMPLETE', 50);
define('TPX_ITEM_STATUS_SHIPPED_TO_CUSTOMER', 60);
define('TPX_ITEM_STATUS_SHIPPED_TO_DISTRIBUTION_CENTRE', 61);
define('TPX_ITEM_STATUS_SHIPPED_RECEIVED_AT_DISTRIBUTION_CENTRE', 62);
define('TPX_ITEM_STATUS_SHIPPED_TO_STORE_FROM_DISTRIBUTION_CENTRE',	63);
define('TPX_ITEM_STATUS_SHIPPED_TO_STORE_DIRECTLY', 64);
define('TPX_ITEM_STATUS_SHIPPED_RECEIVED_AT_STORE', 65);
define('TPX_ITEM_STATUS_SHIPPED_COLLECTED_BY_CUSTOMER', 66);

// Constants for production automation
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_DOWNLOAD', 0);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_DECRYPT', 1);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_CONVERT', 2);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_SUBMITTORENDERER', 3);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_PRINT', 4);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_SETASPRINTED', 5);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_SETASFINISHED', 6);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_SHIP', 7);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_COMPLETE', 8);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_CANCEL', 9);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_ACTIVATE', 10);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_SETONHOLD', 11);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_SETPAYMENTRECEIVED', 12);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_DELETELOCALDATA', 50);
define('TPX_PRODUCTIONAUTOMATION_ACTION_ORDER_DELETEOUTPUTDATA', 51);

define('TPX_PRODUCTIONAUTOMATION_NOTIFY_NO', 0);
define('TPX_PRODUCTIONAUTOMATION_NOTIFY_YES', 1);
define('TPX_PRODUCTIONAUTOMATION_NOTIFY_NOTCUSTOMER', 2);

// Constants for production events status
define('TPX_PRODUCTION_EVENT_STATUS_IDLE', 0);
define('TPX_PRODUCTION_EVENT_STATUS_RUNNING', 1);
define('TPX_PRODUCTION_EVENT_STATUS_SUCCESSFUL', 2);
define('TPX_PRODUCTION_EVENT_STATUS_FAILED', 3);


// Constants for ORDERITEMS[uploadmethod]
define('TPX_UPLOAD_DELIVERY_METHOD_INTERNET', 0);
define('TPX_UPLOAD_DELIVERY_METHOD_MAIL', 1);

// Constants for ORDERITEMS[uploaddatatype]
define('TPX_UPLOAD_DATA_TYPE_RENDERED', 0);
define('TPX_UPLOAD_DATA_TYPE_RAW', 1);

// Constants for ORDERITEMS[epwstatus]
define('TPX_EPW_STATUS_NOT_APPLICABLE', 0);
define('TPX_EPW_STATUS_SUBMITTED', 1);
define('TPX_EPW_STATUS_RECEIVED', 10);
define('TPX_EPW_STATUS_FAILED', 20);
define('TPX_EPW_STATUS_PRINTREADY', 30);
define('TPX_EPW_STATUS_PRINTED', 40);
define('TPX_EPW_STATUS_ABORTED', 99);
define('TPX_EPW_STATUS_COMPLETED', 100);

// Constants for external print workflow (EPW) completion
define('TPX_EPW_COMPLETION_STATUS_NOT_APPLICABLE', 0);
define('TPX_EPW_COMPLETION_STATUS_PRINTED', 1);
define('TPX_EPW_COMPLETION_STATUS_FINISHED', 2);
define('TPX_EPW_COMPLETION_STATUS_SHIPPED', 3);
define('TPX_EPW_COMPLETION_STATUS_SHIPPED_SEND_NOTIFICATION', 4);
define('TPX_EPW_COMPLETION_STATUS_COMPLETED', 5);

// Constants for application file types
define('TPX_APPLICATION_FILE_TYPE_PRODUCTCOLLECTION', 0);
define('TPX_APPLICATION_FILE_TYPE_MASK', 1);
define('TPX_APPLICATION_FILE_TYPE_BACKGROUND', 2);
define('TPX_APPLICATION_FILE_TYPE_PICTURE', 3);
define('TPX_APPLICATION_FILE_TYPE_FRAME', 4);
define('TPX_APPLICATION_FILE_TYPE_FONT', 5);
define('TPX_APPLICATION_FILE_TYPE_PRODUCTCOLLECTION_MASK', 101);
define('TPX_APPLICATION_FILE_TYPE_PRODUCTCOLLECTION_BACKGROUND', 102);
define('TPX_APPLICATION_FILE_TYPE_PRODUCTCOLLECTION_PICTURE', 103);
define('TPX_APPLICATION_FILE_TYPE_PRODUCTCOLLECTION_FRAME', 104);
define('TPX_APPLICATION_FILE_TYPE_PRODUCTCOLLECTION_FONT', 105);
define('TPX_APPLICATION_FILE_TYPE_USER', 106);
define('TPX_APPLICATION_FILE_TYPE_LICENSEKEY', 107);
define('TPX_APPLICATION_FILE_TYPE_CALENDARDATA', 108);
define('TPX_APPLICATION_FILE_TYPE_3DMODEL', 200);
define('TPX_APPLICATION_FILE_TYPE_APPLICATION_BUILD', 999);


// Constants for SHIPPINGRATES[payinstoreallowed]
define('TPX_PAY_IN_STORE_ALLOW', 0);
define('TPX_PAY_IN_STORE_DO_NOT_ALLOW', 1);
define('TPX_PAY_IN_STORE_ONLY', 2);

// Constants for tax address calculation
define('TPX_TAX_CALCULATION_BY_BILLING_ADDRESS', 0);
define('TPX_TAX_CALCULATION_BY_SHIPPING_ADDRESS', 1);

// Constants for SITES[sitetype]
define('TPX_SITE_TYPE_PRODUCTION', 0);
define('TPX_SITE_TYPE_DISTRIBUTION_CENTRE', 1);
define('TPX_SITE_TYPE_STORE', 2);

// Constants for table names (used for pricing)
define('TPX_TABLE_PRODUCTPRICES', 0);
define('TPX_TABLE_PAPERPRICES', 1);
define('TPX_TABLE_COVERPRICES', 2);

// Constants for external store locator script
define('TPX_EDL_CFS_SEARCH_FILTERED', 0);
define('TPX_EDL_CFS_SEARCH_UNFILTERED', 1);

define('TPX_EDL_CFS_DATA_TYPE_STORE', 0);
define('TPX_EDL_CFS_DATA_TYPE_GROUP', 1);
define('TPX_EDL_CFS_DATA_TYPE_ERROR', 2);

// Constants for Taopix pricing model
define('TPX_PRICINGMODEL_NOPRICING', 0);
define('TPX_PRICINGMODEL_PERORDER', 1);
define('TPX_PRICINGMODEL_PERLINE', 2);
define('TPX_PRICINGMODEL_PERQTY', 3);
define('TPX_PRICINGMODEL_PERPAGEQTY', 4);
define('TPX_PRICINGMODEL_PERSIDEQTY', 5);
define('TPX_PRICINGMODEL_PERCHARACTER',	6);
define('TPX_PRICINGMODEL_PERPRODCMPQTY', 7);
define('TPX_PRICINGMODEL_PERSIDEPERPRODPERCMPQTY', 8);

// Constants for Taopix component category display types
define('TPX_COMPONENTCATEGORY_DISPLAYTYPE_CHECKBOX', 0);
define('TPX_COMPONENTCATEGORY_DISPLAYTYPE_LIST', 1);

// Constants for Taopix component display list types
define('TPX_COMPONENT_LISTTYPE_RADIOBUTTONGROUP', 1);
define('TPX_COMPONENT_LISTTYPE_POPUPLIST', 2);

// for future use
define('TPX_COMPONENT_LISTTYPE_LIST', 3);


// Constants for preview
define('TPX_PREVIEW_CUSTOMER', 0);
define('TPX_PREVIEW_SHARED', 1);
define('TPX_PREVIEW_DISPLAY_HORIZ_PAGETURN', 1);
define('TPX_PREVIEW_DISPLAY_VERT_PAGETURN',	2);
define('TPX_PREVIEW_DISPLAY_SLIDESHOW',	3);
define('TPX_PREVIEW_DISPLAY_EXTERNAL',	4);

define('TPX_PREVIEW_COVER_HARD', 0);
define('TPX_PREVIEW_COVER_SOFT', 1);


// Constants for assets
define('TPX_ASSETTYPE_IMAGE', 0);
define('TPX_ASSETTYPE_PRODUCTCATEGORYDATA', 1);
define('TPX_ASSETTYPE_CALENDARDATA', 2);
define('TPX_ASSETTYPE_EMAIL_TEXT', 3);
define('TPX_ASSETTYPE_COMPONENTCATEGORY', "TAOPIXINTERNAL");
define('TPX_ASSETTYPE_COMPONENTCODE', "TAOPIXASSET");

// Constants for product tree setup
define('TPX_ORDERFOOTER_ID', -1);

// Constants for voucher types
define('TPX_VOUCHER_TYPE_DISCOUNT', 0);
define('TPX_VOUCHER_TYPE_PREPAID', 1);
define('TPX_VOUCHER_TYPE_SCRIPT', 2);
define('TPX_VOUCHER_TYPE_GIFTCARD', 5);

// Constants for form types
define('TPX_READONLY_FORM_TYPE', -1);
define('TPX_ADD_EDIT_FORM_TYPE', 0);
define('TPX_CREATE_FORM_TYPE', 1);
define('TPX_IMPORT_FORM_TYPE', 2);

// Constants for authentication modes
define('TPX_AUTHENTICATIONMODE_EXTERNAL', 0);
define('TPX_AUTHENTICATIONMODE_AUTOMATIC', 1);
define('TPX_AUTHENTICATIONMODE_LOGINPASS',2);
define('TPX_AUTHENTICATIONMODE_LOGIN',3);
define('TPX_AUTHENTICATIONMODE_USERNAME',4);
define('TPX_AUTHENTICATIONMODE_PASSWORD',5);
define('TPX_AUTHENTICATIONMODE_AUTHKEY',6);
define('TPX_AUTHENTICATIONMODE_CODE',7);
define('TPX_AUTHENTICATIONMODE_SERIALNUMBER',8);
define('TPX_AUTHENTICATIONMODE_ACTIVATIONCODE',9);

define('TPX_AUTHENTICATIONTYPE_SSO', 0);
define('TPX_AUTHENTICATIONTYPE_HIGHLEVEL', 1);
define('TPX_AUTHENTICATIONTYPE_LOWLEVEL', 2);
define('TPX_AUTHENTICATIONTYPE_EMAILUPDATE', 3);
define('TPX_AUTHENTICATIONTYPE_ASSETSERVICE', 4);

define('TPX_AUTHENTICATION_REPEAT_TRIES', 3);
define('TPX_AUTHENTICATION_FAILED_LOGINS_MINUTES', 5);

// Reasons that the authentication was blocked.
define('TPX_BLOCK_REASON_NONE', 0);
define('TPX_BLOCK_REASON_RATE_LIMIT', 1);
define('TPX_BLOCK_REASON_IP_BLOCK', 2);

define('TPX_USER_AUTH_REASON_WEB_INIT', 0);
define('TPX_USER_AUTH_REASON_WEB_LOGIN', 1);
define('TPX_USER_AUTH_REASON_WEB_CART_INIT', 2);
define('TPX_USER_AUTH_REASON_WEB_CUSTOMER_SHARE_PREVIEW', 3);
define('TPX_USER_AUTH_REASON_ONLINE_PROJECT_CREATE', 4);
define('TPX_USER_AUTH_REASON_ONLINE_PROJECT_EDIT', 5);
define('TPX_USER_AUTH_REASON_HIGHLEVEL_MYACCOUNTDISPLAY', 6);
define('TPX_USER_AUTH_REASON_HIGHLEVEL_SIGNINDISPLAY', 7);
define('TPX_USER_AUTH_REASON_HIGHLEVEL_REGISTERDISPLAY', 8);
define('TPX_USER_AUTH_REASON_HIGHLEVEL_CHECK_SESSION', 9);
define('TPX_USER_AUTH_REASON_HIGHLEVEL_ONLINE_PROJECT_CREATE', 10);
define('TPX_USER_AUTH_REASON_HIGHLEVEL_ONLINE_PROJECT_EDIT', 11);
define('TPX_USER_AUTH_REASON_HIGHLEVEL_LOGIN', 12);
define('TPX_USER_AUTH_REASON_HIGHLEVEL_CHECKOUT', 13);
define('TPX_USER_AUTH_REASON_HIGHLEVEL_ONLINE_PROJECT_CONTINUE_EDIT', 14);
define('TPX_USER_AUTH_REASON_ONLINE_REAUTHENTICATE', 15);
define('TPX_USER_AUTH_REASON_SYSTEMUSER_REAUTHENTICATE', 16);
define('TPX_USER_AUTH_REASON_LOWLEVEL_SSO', 17);
define('TPX_USER_AUTH_REASON_EMAIL_UPDATE', 18);
define('TPX_USER_AUTH_REASON_HIGHLEVEL_ONLINE_PROJECT_PREVIEW', 19);
define('TPX_USER_AUTH_REASON_ASSETSERVICE_OAUTH2LOGIN', 20);
define('TPX_USER_AUTH_REASON_ASSETSERVICE_OAUTH1LOGIN', 21);
define('TPX_USER_AUTH_REASON_WEBVIEW_SSO', 23);

// For type of thumbnail showing in emails
define('TPX_NO_THUMBNAIL', 0);
define('TPX_ATTACHED_THUMBNAIL', 1);
define('TPX_REFERENCED_THUMBNAIL', 2);

// Constants for product collection types
define('TPX_PRODUCTCOLLECTIONTYPE_PHOTOBOOK', 0);
define('TPX_PRODUCTCOLLECTIONTYPE_PROOFBOOK', 1);
define('TPX_PRODUCTCOLLECTIONTYPE_SINGLEPRINTS', 2);
define('TPX_PRODUCTCOLLECTIONTYPE_PHOTOPRINTS', 2);
define('TPX_PRODUCTCOLLECTIONTYPE_CALENDAR', 3);

// Constants for Taopix private category codes
define('TPX_PRIVATECATEGORY_SINGLEPRINT', 'SINGLEPRINT');
define('TPX_PRIVATECATEGORY_PHOTOPRINT', 'PHOTOPRINT');
define('TPX_PRIVATECATEGORY_CALENDARCUSTOMISATION', 'CALENDARCUSTOMISATION');
define('TPX_PRIVATECATEGORY_TAOPIXAI', 'TAOPIXAI');

// Constants for type of component being insertes into the ORDERITEMCOMPONENTS table
define('TPX_ORDERITEMCOMPONENTARRAYTYPE_COMPONENT', 0);
define('TPX_ORDERITEMCOMPONENTARRAYTYPE_EXTERNALASSET', 1);
define('TPX_ORDERITEMCOMPONENTARRAYTYPE_SINGLEPRINT', 2);
define('TPX_ORDERITEMCOMPONENTARRAYTYPE_PHOTOPRINT', 2);
define('TPX_ORDERITEMCOMPONENTARRAYTYPE_CALENDAR', 4);
define('TPX_ORDERITEMCOMPONENTARRAYTYPE_AI', 5);

// Constants for Taopix external asset price types
define('TPX_EXTERNALASSETPRICETYPE_IGNORE', -1);
define('TPX_EXTERNALASSETPRICETYPE_FOC', 0);
define('TPX_EXTERNALASSETPRICETYPE_ONCE', 1);
define('TPX_EXTERNALASSETPRICETYPE_EACHTIME', 2);

// Constants for Taopix password formats
define('TPX_PASSWORDFORMAT_CLEARTEXT', 0);
define('TPX_PASSWORDFORMAT_MD5', 1);

// Constants for different types of shopping charts
define('TPX_SHOPPINGCARTTYPE_INTERNAL', 0);
define('TPX_SHOPPINGCARTTYPE_EXTERNAL', 1);
define('TPX_SHOPPINGCARTTYPE_SELFPUBLISH', 2);

define('TPX_REGISTEREDTAXNUMBERTYPE_NA', 0);
define('TPX_REGISTEREDTAXNUMBERTYPE_PERSONAL', 1);
define('TPX_REGISTEREDTAXNUMBERTYPE_CORPORATE', 2);

define('TPX_SOURCE_DESKTOP', 0);
define('TPX_SOURCE_ONLINE', 1);
define('TPX_DONOTSTEAL', 'RE9OJ1RCRUFOT1NFWUZFQ0tFUg==');

//Open Modes
define('TPX_OPEN_MODE_NEW_PRODUCT', 0);
define('TPX_OPEN_MODE_EXISTING_PRODUCT', 1);
define('TPX_OPEN_MODE_NEW_PROJECT', 2);
define('TPX_OPEN_MODE_EXISTING_PROJECT', 3);
define('TPX_OPEN_MODE_ORDER', 4);
define('TPX_OPEN_MODE_PREVIEW_EXISITING', 5);

// Image Server Path Depth
define('TPX_PATH_DEPTH_YEAR', 0);
define('TPX_PATH_DEPTH_MONTH', 1);
define('TPX_PATH_DEPTH_DAY', 2);
define('TPX_PATH_DEPTH_HOUR', 3);
define('TPX_PATH_DEPTH_MINUTE', 4);
define('TPX_PATH_DEPTH_SECOND', 5);

// Update address mode
define('TPX_UPDATEADDRESSMODE_NA', 0);
define('TPX_UPDATEADDRESSMODE_RESPECT', 1);
define('TPX_UPDATEADDRESSMODE_FULL', 2);

// Guest workflow setting
define('TPX_GUESTWORKFLOWMODE_DISABLED', 0);
define('TPX_GUESTWORKFLOWMODE_OFF', 1);
define('TPX_GUESTWORKFLOWMODE_PROMPT', 2);
define('TPX_GUESTWORKFLOWMODE_AUTOMATIC', 3);

// Data deletion settings constants
define('TPX_REDACTION_DORMANT_DAYS', 365);
define('TPX_REDACTION_NOTIFICATION_DAYS', 7);
define('TPX_REDACTION_MODE_DISABLED', 0);
define('TPX_REDACTION_MODE_ADMINISTRATOR', 1);
define('TPX_REDACTION_MODE_REQUEST', 2);
define('TPX_REDACTION_MODE_ALLOW', 3);
define('TPX_REDACTION_MODE_IMMEDIATE', 4);

// Data deletion progress constants
define('TPX_REDACTION_NONE', 0);
define('TPX_REDACTION_REQUESTED', 1);
define('TPX_REDACTION_DECLINED', 2);
define('TPX_REDACTION_AUTHORISED_BY_LICENSEE', 3);
define('TPX_REDACTION_AUTHORISED_BY_USER', 4);
define('TPX_REDACTION_QUEUED', 5);
define('TPX_REDACTION_IN_PROGRESS', 6);
define('TPX_REDACTION_CONTROL_CENTRE', 7);
define('TPX_REDACTION_COMPLETE', 8);
define('TPX_REDACTION_ERROR', 99);

// Data deletion stage constants - used in connection with events for TPX_REDACTION_IN_PROGRESS
define('TPX_REDACTION_ONLINE', 0);
define('TPX_REDACTION_PRODUCTION', 1);
define('TPX_REDACTION_ORDER_UPLOAD', 2);
define('TPX_REDACTION_CONTROL_CENTRE_FILES', 3);
define('TPX_REDACTION_CONTROL_CENTRE_DATA', 4);

// redaction status
define('TPX_REDACTION_STAGE_QUEUED', 0);
define('TPX_REDACTION_STAGE_IN_PROGRESS', 1);
define('TPX_REDACTION_STAGE_COMPLETE', 2);
define('TPX_REDACTION_STAGE_ERROR', 3);

define('TPX_REDACTION_CC_FILES_VALUE', 192);
define('TPX_REDACTION_UPLOAD_VALUE', 48);
define('TPX_REDACTION_PRODUCTION_VALUE', 12);
define('TPX_REDACTION_ONLINE_VALUE', 3);

// Taopix Online errors
define('TPX_ONLINE_ERROR_NONE', 0);
define('TPX_ONLINE_ERROR_INVALIDOPENMODE', 1);
define('TPX_ONLINE_ERROR_PRODUCTNOTAVAILABLE', 2);
define('TPX_ONLINE_ERROR_INACTIVELICENSEKEY', 3);
define('TPX_ONLINE_ERROR_DEVICENOTSUPPOTRTED', 4);
define('TPX_ONLINE_ERROR_PROJECTDOESNOTEXIST', 5);
define('TPX_ONLINE_ERROR_PROJECTALREADYOPEN', 6);
define('TPX_ONLINE_ERROR_PROJECTNAMEALREADYEXISTS', 7);
define('TPX_ONLINE_ERROR_PROJECTNAMECANNOTBEEMPTY', 8);
define('TPX_ONLINE_ERROR_PROJECTINPRODUCTION', 9);
define('TPX_ONLINE_ERROR_PROJECTLOCKED', 10);
define('TPX_ONLINE_ERROR_PROJECTREFLIMIT', 11);
define('TPX_ONLINE_ERROR_BROWSERNOTSUPPORTED', 12);
define('TPX_ONLINE_ERROR_INVALIDDEVICEDETECTIONDATA', 13);
define('TPX_ONLINE_ERROR_FLIGHTCHECKINCOMPLETE', 14);
define('TPX_ONLINE_ERROR_EXTERNALASSETEXPIRED', 15);
define('TPX_ONLINE_ERROR_EXTERNALCHECKOUTERROR', 16);
define('TPX_ONLINE_ERROR_CLEARPROJECTBATCHREFERROR', 17);
define('TPX_ONLINE_ERROR_DEVICEINCOMPATIBILITY', 18);
define('TPX_ONLINE_ERROR_INVALIDPARAMETER', 19);
define('TPX_ONLINE_ERROR_MAINTENANCEMODE', 20);
define('TPX_ONLINE_ERROR_DATABASE', 21);
define('TPX_ONLINE_ERROR_HIGHLEVELAUTH', 22);
define('TPX_ONLINE_ERROR_HIGHLEVELNOTENABLED', 23);
define('TPX_ONLINE_ERROR_INVALIDUSERID', 24);
define('TPX_ONLINE_ERROR_EMPTYGROUPCODE', 25);
define('TPX_ONLINE_ERROR_ACCOUNT_MISTMATCH', 26);
define('TPX_ONLINE_ERROR_ACCOUNTTASKNOTALLOWED', 27);
define('TPX_ONLINE_ERROR_COMMUNICATION_FAILED', 28);
define('TPX_ONLINE_ERROR_PRODUCT_CONFIGURATION', 29);
define('TPX_ONLINE_ERROR_EDL_SCRIPT_RETURNERROR', 30);
define('TPX_ONLINE_ERROR_RESTORE_FAILED', 31);
define('TPX_ONLINE_ERROR_HIGHLEVELPROJECTACTIVECHECKOUTSESSION', 32);
define('TPX_ONLINE_ERROR_HIGHLEVELINTERNALERROR', 33);
define('TPX_ONLINE_ERROR_HIGHLEVELBASKETEXPIRED', 34);
define('TPX_ONLINE_ERROR_HIGHLEVELSESSIONEXPIRED', 35);
define('TPX_ONLINE_ERROR_HIGHLEVELBASKETEMPTY', 36);
define('TPX_ONLINE_ERROR_ORDERDOESNOTEXIST', 37);
define('TPX_ONLINE_ERROR_LOWLEVELINTERNALERROR', 38);

define('TPX_ONLINE_BASKETAPI_PROJECTREFLIMIT', 100);
define('TPX_ONLINE_BASKETAPI_DEFAULTBASKETREF', 'tpxgnbr');

// Invalid Basketref Reasons:
//	. Logout from product selctor
//	. Logout from customer pages
//	. Logout from online designer
//	. Basket session expiry
define('TPX_ONLINE_BASKETAPI_INVALIDATEBASKETREFREASON_PSLOGOUT', 'PSLOGOUT');
define('TPX_ONLINE_BASKETAPI_INVALIDATEBASKETREFREASON_CPLOGOUT', 'CPLOGOUT');
define('TPX_ONLINE_BASKETAPI_INVALIDATEBASKETREFREASON_OLLOGOUT', 'OLLOGOUT');
define('TPX_ONLINE_BASKETAPI_INVALIDATEBASKETREFREASON_EXPIRED', 'EXPIRED');

define('TPX_ONLINE_BASKETAPI_AUTHENTICATEDUSERSTATUS_GUEST', 0);
define('TPX_ONLINE_BASKETAPI_AUTHENTICATEDUSERSTATUS_SIGNEDINUSER', 1);
define('TPX_ONLINE_BASKETAPI_AUTHENTICATEDUSERSTATUS_SIGNEDINUSEREXPIRED', 2);

// Taopix Online Basket API Workflow Types
define('TPX_BASKETWORKFLOWTYPE_NORMAL', 0);
define('TPX_BASKETWORKFLOWTYPE_LOWLEVELAPI', 1);
define('TPX_BASKETWORKFLOWTYPE_LOWLEVELAPIEXTERNALCHECKOUT', 2);
define('TPX_BASKETWORKFLOWTYPE_HIGHLEVELAPI', 3);
define('TPX_BASKETWORKFLOWTYPE_HIGHLEVELCHECKOUT', 4);


// Taopix Online Supported Browsers
define('TPX_ONLINESUPPORTED_BROWSER_UNKNOW', 'Unkown');
define('TPX_ONLINESUPPORTED_BROWSER_INTERNETEXPLORER', 'Internet Explorer');
define('TPX_ONLINESUPPORTED_BROWSER_CHROME', 'Chrome');
define('TPX_ONLINESUPPORTED_BROWSER_FIREFOX', 'Firefox');
define('TPX_ONLINESUPPORTED_BROWSER_IPHONE', 'iPhone');
define('TPX_ONLINESUPPORTED_BROWSER_IPAD', 'iPad');
define('TPX_ONLINESUPPORTED_BROWSER_ANDROID', 'Android');
define('TPX_ONLINESUPPORTED_BROWSER_SAFARI', 'Safari');
define('TPX_ONLINESUPPORTED_BROWSER_OPERA', 'Opera');
define('TPX_ONLINESUPPORTED_BROWSER_SAMSUNG', 'SamsungBrowser');
define('TPX_ONLINESUPPORTED_BROWSER_WECHAT', 'WeChat');
define('TPX_ONLINESUPPORTED_BROWSER_FBIOS', 'Facebook Apps iPhone');

define('TPX_ONLINESUPPORTED_BROWSER_VERSION_INTERNETEXPLORER', 11);
define('TPX_ONLINESUPPORTED_BROWSER_VERSION_CHROME', 28);
define('TPX_ONLINESUPPORTED_BROWSER_VERSION_FIREFOX', 23);
define('TPX_ONLINESUPPORTED_BROWSER_VERSION_SAFARI', 15);

define('TPX_ONLINESUPPORTED_IOS_VERSION', 15);

// Taopix Online Supported Platforms
define('TPX_ONLINESUPPORTED_PLATFORM_WINDOWS', 'Windows');
define('TPX_ONLINESUPPORTED_PLATFORM_IPAD', 'iPad');
define('TPX_ONLINESUPPORTED_PLATFORM_APPLE', 'Apple');
define('TPX_ONLINESUPPORTED_PLATFORM_ANDROID', 'Android');

// Parameters used by CURL to communicate with Online.
define('TPX_CURL_TIMEOUT', 120);
define('TPX_CURL_RETRY', 5);

// Voucher Apply methods
define('TPX_VOUCHER_APPLY_EACH_MATCHING_PRODUCT', 0);
define('TPX_VOUCHER_APPLY_SPREAD_OVER_ORDER', 1);
define('TPX_VOUCHER_APPLY_LOWEST_PRICED', 2);
define('TPX_VOUCHER_APPLY_HIGHEST_PRICED', 3);

// Wizard modes
define('TPX_WIZARD_MODE_OFF', 0);
define('TPX_WIZARD_MODE_PICTURE_SELECTION_ONLY', 1);
define('TPX_WIZARD_MODE_REPLACE_LAYOUT', 2);
define('TPX_WIZARD_MODE_KEEP_LAYOUT', 3);
define('TPX_WIZARD_MODE_PICTURE_SELECTION_ONLY_WITH_AUTOFLOW', 100);

// Wizard stages
define('TPX_WIZARD_STAGE_MAIN_EDITOR', 0);
define('TPX_WIZARD_STAGE_PICTURE_SELECTION', 1);
define('TPX_WIZARD_STAGE_WIZARD_EDITOR', 2);

// Created in wizard mode
define('TPX_NOT_CREATED_BY_WIZARD', 0);
define('TPX_CREATED_BY_WIZARD', 1);

// Editor Mode.
define('TPX_ONLINE_EDITOR_MODE_EASY', 0);
define('TPX_ONLINE_EDITOR_MODE_ADVANCED', 1);

// Task manager run status
define('TPX_TASKMANAGER_STATUS_NEVERRUN', 0);
define('TPX_TASKMANAGER_STATUS_FAILED', 1);
define('TPX_TASKMANAGER_STATUS_COMPLETED', 2);
define('TPX_TASKMANAGER_STATUS_IDLE', 0);
define('TPX_TASKMANAGER_STATUS_INPROCESS', 1);

//product type
define('TPX_PRODUCT_TYPE_PHOTO_BOOK', 0);
define('TPX_PRODUCT_TYPE_PROOF_BOOK', 1);
define('TPX_PRODUCT_TYPE_SINGLE_PRINTS', 2);
define('TPX_PRODUCT_TYPE_PHOTO_PRINTS', 2);
define('TPX_PRODUCT_TYPE_CALENDAR', 3);
define('TPX_PRODUCT_TYPE_YEAR_BOOK', 4);
define('TPX_PRODUCT_TYPE_CANVAS', 5);
define('TPX_PRODUCT_TYPE_CARD', 6);

// Taopix Data API
define('TPX_DATA_API_NO_ORDER_SESSION_REF', 'NOORDERSESSIONREF');
define('TPX_DATA_API_ERROR_NONE', 0);
define('TPX_DATA_API_ERROR_DATABASE', 1);
define('TPX_DATA_API_ERROR_NOPROJECTREFS', 2);
define('TPX_DATA_API_ERROR_NOITEMSFOUND', 3);
define('TPX_DATA_API_ERROR_PARTIALORDER', 4);

// Purge Automation default minimum days
define('TPX_PURGE_MINIMUM_DORMANT_DAYS', 3);
define('TPX_PURGE_MINIMUM_ORDERED_DORMANT_DAYS', 90);
define('TPX_PURGE_MINIMUM_PURGE_DAYS', 1);
define('TPX_PURGE_MINIMUM_PURGE_WITH_EMAIL_DAYS', 7);

// project loaded status
define('TPX_PROJECT_LOADED_TEMPLATE', 0);
define('TPX_PROJECT_LOADED_PROJECT', 1);
define('TPX_PROJECT_LOADED_WORKING', 2);

// Constants for user logout reasons
define('TPX_USER_LOGOUT_REASON_USER_LOGOUT', 0);
define('TPX_USER_LOGOUT_REASON_SESSION_EXPIRED', 1);
define('TPX_USER_LOGOUT_REASON_SESSION_NOT_STARTED', 2);
define('TPX_USER_LOGOUT_REASON_HIGHLEVEL_DESIGNER', 3);
define('TPX_USER_LOGOUT_REASON_HIGHLEVEL_ACCOUNTPAGES', 4);
define('TPX_USER_LOGOUT_REASON_PAYMENT_SESSION_EXPIRED', 5);

define('TPX_SSO_ERROR_CODE_NOT_CONFIGURED', 0);
define('TPX_SSO_ERROR_CODE_EMPTY_COOKIE', 1);
define('TPX_SSO_ERROR_CODE_MISSING_COOKIE', 2);
define('TPX_SSO_ERROR_CODE_MISSING_DATABASE_RECORD', 3);
define('TPX_SSO_ERROR_CODE_MISSING_REDIRECT_URL', 4);
define('TPX_SSO_ERROR_CODE_MISSING_SESSION_REF', 5);

define('TPX_SSO_COOKIE_NAME', 'mawebssokey');
define('TPX_SSO_LL_COOKIE_NAME', 'mawebssollkey');

// CC Notification Targets
define('TPX_CCNOTIFICATION_TARGET_HLAPI', 'HLAPI');
define('TPX_CCNOTIFICATION_TARGET_LLAPI', 'LLAPI');
define('TPX_CCNOTIFICATION_TARGET_PURGE', 'PURGE');
define('TPX_CCNOTIFICATION_TARGET_DBCONVPROC', 'DBCONVPROC');

// CC Notification Actions
define('TPX_CCNOTIFICATION_ACTION_SAVEPROJECT', 'SAVEPROJECT');
define('TPX_CCNOTIFICATION_ACTION_RENAMEPROJECT', 'RENAMEPROJECT');
define('TPX_CCNOTIFICATION_ACTION_CHANGEPRODUCT', 'CHANGEPRODUCT');
define('TPX_CCNOTIFICATION_ACTION_SETREORDERSTATE', 'SETREORDERSTATE');
define('TPX_CCNOTIFICATION_ACTION_DELOLBASKETENTRY', 'DELOLBASKETENTRY');
define('TPX_CCNOTIFICATION_ACTION_CRTFLAGPROJEMAILS', 'CRTFLAGPROJEMAILS');
define('TPX_CCNOTIFICATION_ACTION_DBCONVPROCIMPORT', 'DBCONVPROCIMPORT');
define('TPX_CCNOTIFICATION_ACTION_SHOWINPROJECTLIST', 'SHOWINPROJECTLIST');

define('TPX_SSO_HIGHLEVEL_ENABLED_OFF', 0);
define('TPX_SSO_HIGHLEVEL_ENABLED_SIGNIN', 1);
define('TPX_SSO_HIGHLEVEL_ENABLED_AUTOMATIC', 2);

define('TPX_CUSTOMTAX', 'TPX_CUSTOMTAX');

define('TPX_PROJECT_STATUS_CREATIONFAILED', 0);
define('TPX_PROJECT_STATUS_CREATED', 1);
define('TPX_PROJECT_STATUS_INDATABASE', 2);
define('TPX_PROJECT_STATUS_ARCHIVED', 4);
define('TPX_PROJECT_STATUS_ARCHIVING', 8);
define('TPX_PROJECT_STATUS_RESTORING', 16);
define('TPX_PROJECT_STATUS_USERDELETED', 32);

define('TPX_ARCHIVE_RESTORE_FAILED', 1);
define('TPX_ARCHIVE_RESTORE_IN_PROGRESS', 2);

define('TPX_PRODUCTOPTION_PRICING_NON', 0);
define('TPX_PRODUCTOPTION_PRICING_PERPICTURE', 1);
define('TPX_PRODUCTOPTION_PRICING_PERCOMPONENTSUBCOMPONENT', 2);

define('TPX_PRICETRANSFORMATIONSTAGE_PRE', 1);
define('TPX_PRICETRANSFORMATIONSTAGE_POST', 2);

// system resource types
define('TPX_SYSTEM_RESOURCE_TYPE_3DMODEL', 0);

// taopix task codes
define('TPX_EXPORT', 'TAOPIX_EXPORT');

// event trigger codes
define('TPX_TRIGGER_CONVERTED_FILES', 'CONVERTEDFILES');
define('TPX_TRIGGER_CUSTOMER_ACTIVATE', 'CUSTOMERACTIVATE');
define('TPX_TRIGGER_CUSTOMER_ADD', 'CUSTOMERADD');
define('TPX_TRIGGER_CUSTOMER_DELETE', 'CUSTOMERDELETE');
define('TPX_TRIGGER_CUSTOMER_EDIT', 'CUSTOMEREDIT');
define('TPX_TRIGGER_DECRYPTED_FILES', 'DECRYPTEDFILES');
define('TPX_TRIGGER_DECRYPTED_PROJECT_ELEMENTS', 'DECRYPTEDPROJECTELEMENTS');
define('TPX_TRIGGER_DECRYPTED_RENDERED', 'DECRYPTEDRENDERED');
define('TPX_TRIGGER_FILES_PRINTED', 'FILESPRINTED');
define('TPX_TRIGGER_FILES_SENT_TO_EXTERNAL_WORKFLOW', 'FILESSENTTOEXTERNALWORKFLOW');
define('TPX_TRIGGER_FINISHING_COMPLETE', 'FINISHINGCOMPLETE');
define('TPX_TRIGGER_IMPORTED_FILES', 'IMPORTEDFILES');
define('TPX_TRIGGER_IMPORTED_PROJECT_ELEMENTS', 'IMPORTEDPROJECTELEMENTS');
define('TPX_TRIGGER_IMPORTED_RENDERED', 'IMPORTEDRENDERED');
define('TPX_TRIGGER_ORDER_ACTIVATE', 'ORDERACTIVATE');
define('TPX_TRIGGER_ORDER_CANCELLED', 'ORDERCANCELLED');
define('TPX_TRIGGER_ORDER_COMPLETE', 'ORDERCOMPLETE');
define('TPX_TRIGGER_ORDER_PAID', 'ORDERPAID');
define('TPX_TRIGGER_ORDER_CREATED', 'ORDERCREATED');
define('TPX_TRIGGER_ORDER_REROUTE', 'ORDERREROUTE');
define('TPX_TRIGGER_ORDER_SAVED_TO_DISK', 'ORDERSAVEDTODISK');
define('TPX_TRIGGER_ORDER_UPLOAD_COMPLETE', 'ORDERUPLOADCOMPLETE');
define('TPX_TRIGGER_PASSWORD_RESET', 'PASSWORDRESET');
define('TPX_TRIGGER_SHIPPED', 'SHIPPED');
define('TPX_TRIGGER_SHIPPED_DISTRIBUTION_CENTRE_RECEIVED', 'SHIPPEDDISTRIBUTIONCENTRERECEIVED');
define('TPX_TRIGGER_SHIPPED_DISTRIBUTION_CENTRE_SHIPPED', 'SHIPPEDDISTRIBUTIONCENTRESHIPPED');
define('TPX_TRIGGER_SHIPPED_STORE_CUSTOMER_COLLECTED', 'SHIPPEDSTORECUSTOMERCOLLECTED');
define('TPX_TRIGGER_SHIPPED_STORE_RECEIVED', 'SHIPPEDSTORERECEIVED');
define('TPX_TRIGGER_TEMP_ORDER_CANCELLED', 'TEMPORDERCANCELLED');
define('TPX_TRIGGER_TEMP_ORDER_CREATED', 'TEMPORDERCREATED');
define('TPX_TRIGGER_ON_HOLD_UPDATED', 'ONHOLDUPDATED');

// Smart Guides.
define('TPX_SMARTGUIDES_OBJECT_GUIDECOLOUR', '00CCFF');
define('TPX_SMARTGUIDES_PAGE_GUIDECOLOUR', 'FF00FF');

define('TPX_COORDINATE_SCALE_INCHES', 0);
define('TPX_COORDINATE_SCALE_MILLIMETRES', 1);
define('TPX_COORDINATE_SCALE_CENTIMETRES', 2); // Not in Desktop.

define('TPX_AUTOMATICALLYAPPLYPERFECTLYCLEAR_MODE_OFF', 0);
define('TPX_AUTOMATICALLYAPPLYPERFECTLYCLEAR_MODE_ON', 1);
define('TPX_AUTOMATICALLYAPPLYPERFECTLYCLEAR_MODE_TOGGLE', 2);

define('TPX_ORDERHASCOMPANIONALBUMS_UNKOWN','UNKOWN');
define('TPX_ORDERHASCOMPANIONALBUMS_YES', 'YES');
define('TPX_ORDERHASCOMPANIONALBUMS_NO', 'NO');

define('TPX_PICTURES_LOOKUP_CATEGORY_KEY', 0);
define('TPX_PICTURES_LOOKUP_SEPERATOR', '*');

// Pricing Engine Type
define('TPX_PRICINGENGINE_LEGACY', 0);
define('TPX_PRICINGENGINE_2018', 1);

// Password Reset Link Expiry Codes
define('TPX_PASSWORDRESETLINKEXPIRY_ACTIVE', 1);
define('TPX_PASSWORDRESETLINKEXPIRY_ACTIVEWITHAUTHCODE', 2);
define('TPX_PASSWORDRESETLINKEXPIRY_RESETLOOKUPFAILED', 3);
define('TPX_PASSWORDRESETLINKEXPIRY_HASHMISMATCH', 4);
define('TPX_PASSWORDRESETLINKEXPIRY_EXPIREDNATURALLY', 5);
define('TPX_PASSWORDRESETLINKEXPIRY_LOGINAFTERREQUEST', 6);
define('TPX_PASSWORDRESETLINKEXPIRY_PASSWORDRESETAFTERREQUEST', 7);
define('TPX_PASSWORDRESETLINKEXPIRY_AUTHCODEOK', 8);
define('TPX_PASSWORDRESETLINKEXPIRY_AUTHCODEFAILED', 9);
define('TPX_PASSWORDRESETLINKEXPIRY_AUTHCODELIMITREACHED', 10);

// Number of times the password reset authcode validation can fail
define('TPX_PASSWORDRESETAUTHCODE_ATTEMPTS_LIMIT', 10);

// Branding file type constants.
define('TPX_BRANDING_FILE_TYPE_CC_LOGO', 1);
define('TPX_BRANDING_FILE_TYPE_MARKETING', 2);
define('TPX_BRANDING_FILE_TYPE_EMAIL_LOGO', 3);
define('TPX_BRANDING_FILE_TYPE_OL_LOGO', 4);
define('TPX_BRANDING_FILE_TYPE_OL_LOGO_DARK', 5);
define('TPX_BRANDING_TEXT_TYPE_SIGNATURE', 101);


// S3 storage class
define('TPX_BUCKET_STORAGE_CLASS_STANDARD', 0);
define('TPX_BUCKET_STORAGE_CLASS_REDUCED_REDUNDANCY', 1);
define('TPX_BUCKET_STORAGE_CLASS_INFREQUENT_ACCESS', 2);

// Device Detection Generation Status
define('TPX_DEVICE_DETECTION_TPXGENERATE', 'tpxgdd');

define('TPX_USER_PROJECT_LIST_MODE_VIEW', 0);
define('TPX_USER_PROJECT_LIST_MODE_GET', 1);

// Customer Account Override Reasons
define('TPX_CUSTOMER_ACCOUNT_OVERRIDE_REASON_CUSTOMERREGISTER', 0);
define('TPX_CUSTOMER_ACCOUNT_OVERRIDE_REASON_CUSTOMERUPDATEDETAILS', 1);
define('TPX_CUSTOMER_ACCOUNT_OVERRIDE_REASON_CUSTOMERUPDATEDETAILSORDERPROMPT', 2);
define('TPX_CUSTOMER_ACCOUNT_OVERRIDE_REASON_ADMINCUSTOMERADD', 3);
define('TPX_CUSTOMER_ACCOUNT_OVERRIDE_REASON_ADMINCUSTOMEREDIT', 4);

// Insert/delete buttons visibility.
define('TPX_INSERTDELETEBUTTONS_VISIBILITY_HIDDEN', 0);
define('TPX_INSERTDELETEBUTTONS_VISIBILITY_VISIBLE', 1);

// Total pages.
define('TPX_TOTALPAGES_DROPDOWN_MODE_DISABLED', 0);
define('TPX_TOTALPAGES_DROPDOWN_MODE_ENABLED', 1);

// AI Mode
define('TPX_AIMODE_DISABLED', 0);
define('TPX_AIMODE_OPTIONAL', 1);
define('TPX_AIMODE_ENABLED', 2);

// Register using email options.
define('TPX_REGISTER_USING_USERNAME', 0);
define('TPX_REGISTER_USING_EMAIL', 1);

// Desktop cart item limit
define('TPX_DESKTOP_CART_MAX_ITEMS', 20);

//Connectors Status
define('TPX_CONNECTOR_NOTCONFIGURED', 0);
define('TPX_CONNECTOR_PENDING', 1);
define('TPX_CONNECTOR_READY', 2);
define('TPX_CONNECTOR_CONNECTED', 3);

// Purge task constants
define('TPX_INTERNALTASK_PURGE_VERBOSELEVEL', 0);
define('TPX_INTERNALTASK_PURGE_RECORDLIMIT', 1000);
define('TPX_INTERNALTASK_PURGE_CLEANUP_PROJECTS', 4);

// Product Group Constants
define('TPX_PRODUCTGROUP_ASSIGNEETYPE_VOUCHER', 0);

// Product collection resource kind constants
define('TPX_DESKTOP_RESOURCEKIND_NONCREATORRESOURCE', 100);

// Desktop metadata file constants
define('TPX_DESKTOP_PUBLISHVERSION_NOLIVEMETADATA', 0);
define('TPX_DESKTOP_PUBLISHVERSION_LIVEMETADATAV1', 1);

// Production in CC record limit
define('TPX_PRODUCTIONINCC_GRIDPAGESIZE', 250);

// Custom param key definition
define('TPX_CUSTOMPARAM_KEY_PREFIX', 'taopixcustomparam');

// Components display stage online constants
define('TPX_COMPONENT_DISPLAY_STAGE_NONE', 0);
define('TPX_COMPONENT_DISPLAY_STAGE_START', 1);
define('TPX_COMPONENT_DISPLAY_STAGE_ORDER', 2);
define('TPX_COMPONENT_DISPLAY_STAGE_ALL', 3);

// Component upsell settings
define('TPX_COMPONENT_UPSELL_ENABLED', 1);
define('TPX_COMPONENT_UPSELL_ALLOW_PRODUCT_QTY', 2);

define('TPX_HTTP_RESPONSE_STATUSCODE_OK', 200);
define('TPX_HTTP_RESPONSE_STATUSCODE_CREATED', 201);
define('TPX_HTTP_RESPONSE_STATUSCODE_BADREQUEST', 400);

// User Request Token types
define('TPX_USER_REQUEST_TOKEN_KIND_PASSWORD_RESET', 0);
define('TPX_USER_REQUEST_TOKEN_KIND_GOOGLE', 1);
define('TPX_USER_REQUEST_TOKEN_KIND_FACEBOOK', 2);
define('TPX_USER_REQUEST_TOKEN_KIND_FLICKR', 3);

// OAuth status types
define('TPX_OAUTH_STATUS_WAITING', 0);
define('TPX_OAUTH_STATUS_SUCCESS', 1);
define('TPX_OAUTH_STATUS_FAILURE', 2);

// OAuth Versions
define('TPX_OAUTH_VERSION_1', 1);
define('TPX_OAUTH_VERSION_2', 2);
// Data maps.
define('TPX_DATAMAP_POSITION', 0);
define('TPX_DATAMAP_DEFAULT_VALUE', 1);


// Layout configuration flags
define('TPX_LAYOUTCONFIGURATIONFLAGS_NONE', 0);
define('TPX_LAYOUTCONFIGURATIONFLAGS_CALENDARHASVARIABLEPAGEMONTHS', 1);

// Unassign / orphaned collection code for products admin screen
define('TPX_UNASSIGNED_PRODUCT_CODE', 'ZZZZZZZZZZZZZZZ999999999999999');


// Promo Panel override modes
define('TPX_DESKTOPDESIGNER_PROMOPANELOVERRIDEMODE_USEDEFAULT', 0);
define('TPX_DESKTOPDESIGNER_PROMOPANELOVERRIDEMODE_URL', 1);
define('TPX_DESKTOPDESIGNER_PROMOPANELOVERRIDEMODE_IMAGE', 2);
