#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2017-06-14';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2017.1.1';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2017r1.1';


#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;