#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2017-11-29';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2017.3.1';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2017r3.1';


#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;