#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2018-09-14';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2018.4.1';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2018r4.1';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;

