#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2018-10-05';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2018.4.2';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2018r4.2';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;

