#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2019-02-14';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2018.5.2';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2018r5.2';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;
