#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2019-04-29';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2019.1.1';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2019r1.1';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;

