#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2020-03-10';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2020.1.1';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2020r1.1';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;

