#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2020-07-17';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2020.1.3';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2020r1.3';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;

