#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2020-09-11';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2020.3.2';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2020r3.2';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;

