#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2021-01-28';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2020.6.0';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2020r6';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;

