#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2021-02-26';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2020.6.2';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2020r6.2';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;
