#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2021-03-05';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2020.6.3';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2020r6.3';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;
