#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2021-08-19';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2021.2.1';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2021r2.1';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;

