#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2021-11-01';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2021.3.2';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2021r3.2';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;

