#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2021-12-09';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2021.3.3';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2021r3.3';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;

