#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2024-02-19';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2023.1.2';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2023r1.2';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;
