#
SET FOREIGN_KEY_CHECKS = 0;

#
# DDL START
#

UPDATE `SYSTEMCONFIG` SET `webversiondate` = '2024-09-12';
UPDATE `SYSTEMCONFIG` SET `webversionnumber` = '2024.1.1';
UPDATE `SYSTEMCONFIG` SET `webversionstring`= '2024r1.1';

#
# DDL END
#

SET FOREIGN_KEY_CHECKS = 1;
