<?php

require __DIR__ . '/../../../libs/external/vendor/autoload.php';

error_reporting(E_ALL);
ini_set('log_errors', true);

// step back to the webroot directory
chdir('../../');

require_once('../Utils/UtilsCoreIncludes.php');
require_once('../Order/Order_control.php');
require_once('../Order/PaymentIntegration/PaymentIntegration.php');

// read the TAOPIX config file
$ac_config = UtilsObj::readConfigFile('../config/mediaalbumweb.conf');

// get the constants
$gConstants = DatabaseObj::getConstants();
	
// get Taopix ref passed back in order to revive gSession. 
$_GET['ref']  = $_POST['udf2'];
$_POST['ref'] = $_POST['udf2'];

$gSession = AuthenticateObj::getCurrentSessionData();	
if ($gSession['ref'] > 0)
{
	$browserLocale = UtilsObj::getBrowserLocale();
	if ($browserLocale != '')
	{
		$gSession['browserlanguagecode'] = $browserLocale;
	}
}
else
{
	global $gDefaultSiteBrandingCode;
	AuthenticateObj::setSessionWebBrand($gDefaultSiteBrandingCode);
}

// read Intesa config file
$IntesaConfig = PaymentIntegrationObj::readCCIConfigFile('../config/Intesa.conf', $gSession['order']['currencycode'], $gSession['webbrandcode']);

// If Intesa sent back no error then continue & validate data
if (! $_POST['Error'])	
{

	$paymentid = UtilsObj::getPOSTParam('paymentid');
	$tranid = UtilsObj::getPOSTParam('tranid');
	$result = UtilsObj::getPOSTParam('result');		
	$auth = UtilsObj::getPOSTParam('auth');		
	$postdate = UtilsObj::getPOSTParam('postdate');		
	$trackid = UtilsObj::getPOSTParam('trackid');		
	$ref = UtilsObj::getPOSTParam('ref');	// this ref provided by Intesa	
	$taopixRef = UtilsObj::getPOSTParam('udf2'); // this is ref generated by Taopix		
	$cardtype = UtilsObj::getPOSTParam('cardtype');		
	$payinst = UtilsObj::getPOSTParam('payinst');		
	$liability = UtilsObj::getPOSTParam('liability');
	$returnedHash = UtilsObj::getPOSTParam('udf4'); 
	$transactionType = UtilsObj::getPOSTParam('udf1'); 	
	$amount = number_format($gSession['order']['ordertotal'], $gSession['order']['currencydecimalplaces'], '.', '');		
	
	// generate hash from params passed back & gSession
	$hashString = sha1($IntesaConfig['TRANPORTALID'] . $IntesaConfig['TRANPORTALPWD'] . $parameters['action'] . $amount.
					  $gSession['order']['currencyisonumber'] . $trackid . $taopixRef);				

	// compare generated hash with the one passed back. 
	// If hashs matched, perform automatic callback & tell Intesa to redirect customer to manual callback to display ordernumber
	if ($returnedHash == $hashString)
	{
		Order_control::ccAutomaticCallback();		
		echo "REDIRECT=" . UtilsObj::correctPath($gSession['webbrandweburl']) . '?fsaction=Order.ccManualCallback&ref=' . $_POST['ref'];
	}
	else // hashs don't match, tell Intesa to redirect customer to cancel callback & display error.
	{			
		$errorMessage = urlencode("ABORT-Mismatched Signature.");
		$cancelReturnPath = UtilsObj::correctPath($gSession['webbrandweburl']) . '?fsaction=Order.ccCancelCallback&ref=' . $gSession['ref']."&error=".$errorMessage;
		echo "REDIRECT=".$cancelReturnPath;	
	}
	
}
else // Intesa sent back error, redirect customer to cancel page & display error.
{		

	$paymentId = $_POST['paymentid'];
	$errorCode = $_POST['Error'];
	$errorMessage = $_POST['ErrorText'];
			
	$errorMessage = urlencode($errorCode . "-" . $errorMessage);
	$cancelReturnPath = UtilsObj::correctPath($gSession['webbrandweburl']) . '?fsaction=Order.ccCancelCallback&ref=' . $gSession['ref'] . "&error=" . $errorMessage . "&transid=".$paymentId;
	echo "REDIRECT=" . $cancelReturnPath;		
	
}

?>