<?php

namespace PricingEngine\Enum\Voucher;

require_once __DIR__ . '/../../../Utils/UtilsConstants.php';

class DiscountMethod
{
	const ALL_MATCHING_LINES = TPX_VOUCHER_APPLY_EACH_MATCHING_PRODUCT;
	const DISTRIBUTED_OVER_MATCHING_LINES = TPX_VOUCHER_APPLY_SPREAD_OVER_ORDER;
	const LOWEST_PRICED_MATCHING_LINE = TPX_VOUCHER_APPLY_LOWEST_PRICED;
	const HIGHEST_PRICED_MATCHING_LINE = TPX_VOUCHER_APPLY_HIGHEST_PRICED;
}
