# Keywords

DROP TRIGGER IF EXISTS `AUCACHE_KEYWORDS_UPDATE`$$
CREATE TRIGGER `AUCACHE_KEYWORDS_UPDATE` AFTER UPDATE ON `KEYWORDS`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$

DROP TRIGGER IF EXISTS `AUCACHE_KEYWORDS_DELETE`$$
CREATE TRIGGER `AUCACHE_KEYWORDS_DELETE` AFTER DELETE ON `KEYWORDS`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$

# Keyword Group

DROP TRIGGER IF EXISTS `AUCACHE_KEYWORDGROUP_INSERT`$$
CREATE TRIGGER `AUCACHE_KEYWORDGROUP_INSERT` AFTER INSERT ON `KEYWORDGROUP`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$

DROP TRIGGER IF EXISTS `AUCACHE_KEYWORDGROUP_UPDATE`$$
CREATE TRIGGER `AUCACHE_KEYWORDGROUP_UPDATE` AFTER UPDATE ON `KEYWORDGROUP`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$

DROP TRIGGER IF EXISTS `AUCACHE_KEYWORDGROUP_DELETE`$$
CREATE TRIGGER `AUCACHE_KEYWORDGROUP_DELETE` AFTER DELETE ON `KEYWORDGROUP`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$

# Keyword Group Header

DROP TRIGGER IF EXISTS `AUCACHE_KEYWORDGROUPHEADER_UPDATE`$$
CREATE TRIGGER `AUCACHE_KEYWORDGROUPHEADER_UPDATE` AFTER UPDATE ON `KEYWORDGROUPHEADER`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$

DROP TRIGGER IF EXISTS `AUCACHE_KEYWORDGROUPHEADER_DELETE`$$
CREATE TRIGGER `AUCACHE_KEYWORDGROUPHEADER_DELETE` AFTER DELETE ON `KEYWORDGROUPHEADER`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$
