DROP PROCEDURE IF EXISTS AUCACHE_UPDATEVERSION$$
CREATE PROCEDURE `AUCACHE_UPDATEVERSION`(IN pOldGroupCode VARCHAR(50), IN pNewGroupCode VARCHAR(50))
BEGIN
    IF (pOldGroupCode = pNewGroupCode) AND (pOldGroupCode <> "") THEN
        UPDATE `LICENSEKEYS` SET `cacheversion` = CONCAT(NOW(), "_", floor(rand() * 100000)) WHERE `groupcode` = pOldGroupCode; 
    ELSEIF (pOldGroupCode = "") OR (pNewGroupCode = "") THEN
        UPDATE `LICENSEKEYS` SET `cacheversion` = CONCAT(NOW(), "_", floor(rand() * 100000));   
    ELSE
        UPDATE `LICENSEKEYS` SET `cacheversion` = CONCAT(NOW(), "_", floor(rand() * 100000)) WHERE (`groupcode` = pOldGroupCode) OR (`groupcode` = pNewGroupCode); 
    END IF;
END$$


#LICENSEKEYS

DROP TRIGGER IF EXISTS `AUCACHE_LICENSEKEYS_INSERT`$$
CREATE TRIGGER `AUCACHE_LICENSEKEYS_INSERT` BEFORE INSERT ON `LICENSEKEYS`
FOR EACH ROW 
BEGIN
	SET NEW.`cacheversion` = CONCAT(NOW(), "_", floor(rand() * 100000));         	
END$$


DROP TRIGGER IF EXISTS `AUCACHE_LICENSEKEYS_UPDATE`$$
CREATE TRIGGER `AUCACHE_LICENSEKEYS_UPDATE` BEFORE UPDATE ON `LICENSEKEYS`
FOR EACH ROW 
BEGIN
	SET NEW.`cacheversion` = CONCAT(NOW(), "_", floor(rand() * 100000));
END$$


#PRICELINK

DROP TRIGGER IF EXISTS `AUCACHE_PRICELINK_INSERT`$$
CREATE TRIGGER `AUCACHE_PRICELINK_INSERT` AFTER INSERT ON `PRICELINK`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION(NEW.`groupcode`, NEW.`groupcode`);
END$$


DROP TRIGGER IF EXISTS `AUCACHE_PRICELINK_UPDATE`$$
CREATE TRIGGER `AUCACHE_PRICELINK_UPDATE` AFTER UPDATE ON `PRICELINK`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION(OLD.`groupcode`, NEW.`groupcode`);
END$$


DROP TRIGGER IF EXISTS `AUCACHE_PRICELINK_DELETE`$$
CREATE TRIGGER `AUCACHE_PRICELINK_DELETE` AFTER DELETE ON `PRICELINK`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION(OLD.`groupcode`, OLD.`groupcode`);
END$$


#PRICES

DROP TRIGGER IF EXISTS `AUCACHE_PRICES_INSERT`$$
CREATE TRIGGER `AUCACHE_PRICES_INSERT` AFTER INSERT ON `PRICES`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_PRICES_UPDATE`$$
CREATE TRIGGER `AUCACHE_PRICES_UPDATE` AFTER UPDATE ON `PRICES`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_PRICES_DELETE`$$
CREATE TRIGGER `AUCACHE_PRICES_DELETE` AFTER DELETE ON `PRICES`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


#TAX RATES

DROP TRIGGER IF EXISTS `AUCACHE_TAXRATES_INSERT`$$
CREATE TRIGGER `AUCACHE_TAXRATES_INSERT` AFTER INSERT ON `TAXRATES`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_TAXRATES_UPDATE`$$
CREATE TRIGGER `AUCACHE_TAXRATES_UPDATE` AFTER UPDATE ON `TAXRATES`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_TAXRATES_DELETE`$$
CREATE TRIGGER `AUCACHE_TAXRATES_DELETE` AFTER DELETE ON `TAXRATES`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


#TAX ZONES

DROP TRIGGER IF EXISTS `AUCACHE_TAXZONES_INSERT`$$
CREATE TRIGGER `AUCACHE_TAXZONES_INSERT` AFTER INSERT ON `TAXZONES`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_TAXZONES_UPDATE`$$
CREATE TRIGGER `AUCACHE_TAXZONES_UPDATE` AFTER UPDATE ON `TAXZONES`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_TAXZONES_DELETE`$$
CREATE TRIGGER `AUCACHE_TAXZONES_DELETE` AFTER DELETE ON `TAXZONES`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


#PRODUCTS

DROP TRIGGER IF EXISTS `AUCACHE_PRODUCTS_INSERT`$$
CREATE TRIGGER `AUCACHE_PRODUCTS_INSERT` AFTER INSERT ON `PRODUCTS`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_PRODUCTS_UPDATE`$$
CREATE TRIGGER `AUCACHE_PRODUCTS_UPDATE` AFTER UPDATE ON `PRODUCTS`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_PRODUCTS_DELETE`$$
CREATE TRIGGER `AUCACHE_PRODUCTS_DELETE` AFTER DELETE ON `PRODUCTS`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


#COMPONENT CATEGORY

DROP TRIGGER IF EXISTS `AUCACHE_COMPONENTCATEGORIES_INSERT`$$
CREATE TRIGGER `AUCACHE_COMPONENTCATEGORIES_INSERT` AFTER INSERT ON `COMPONENTCATEGORIES`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_COMPONENTCATEGORIES_UPDATE`$$
CREATE TRIGGER `AUCACHE_COMPONENTCATEGORIES_UPDATE` AFTER UPDATE ON `COMPONENTCATEGORIES`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_COMPONENTCATEGORIES_DELETE`$$
CREATE TRIGGER `AUCACHE_COMPONENTCATEGORIES_DELETE` AFTER DELETE ON `COMPONENTCATEGORIES`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


#COMPONENTS

DROP TRIGGER IF EXISTS `AUCACHE_COMPONENTS_INSERT`$$
CREATE TRIGGER `AUCACHE_COMPONENTS_INSERT` AFTER INSERT ON `COMPONENTS`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_COMPONENTS_UPDATE`$$
CREATE TRIGGER `AUCACHE_COMPONENTS_UPDATE` AFTER UPDATE ON `COMPONENTS`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_COMPONENTS_DELETE`$$
CREATE TRIGGER `AUCACHE_COMPONENTS_DELETE` AFTER DELETE ON `COMPONENTS`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


#PRODUCTCOLLECTIONLINK

DROP TRIGGER IF EXISTS `AUCACHE_PRODUCTCOLLECTIONLINK_INSERT`$$
CREATE TRIGGER `AUCACHE_PRODUCTCOLLECTIONLINK_INSERT` AFTER INSERT ON `PRODUCTCOLLECTIONLINK`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_PRODUCTCOLLECTIONLINK_UPDATE`$$
CREATE TRIGGER `AUCACHE_PRODUCTCOLLECTIONLINK_UPDATE` AFTER UPDATE ON `PRODUCTCOLLECTIONLINK`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$


DROP TRIGGER IF EXISTS `AUCACHE_PRODUCTCOLLECTIONLINK_DELETE`$$
CREATE TRIGGER `AUCACHE_PRODUCTCOLLECTIONLINK_DELETE` AFTER DELETE ON `PRODUCTCOLLECTIONLINK`
FOR EACH ROW 
BEGIN
	CALL AUCACHE_UPDATEVERSION("", "");
END$$